import type { Block } from '@doc/domain/components/block-container/block-container.component';

import { Sidebar06Component } from './sidebar-06.component';

export const sidebar06Block: Block = {
  id: 'sidebar-06',
  title: 'Sidebar 06',
  description: 'A sidebar with submenus as dropdowns.',
  component: Sidebar06Component,
  category: 'Sidebar',
  image: {
    light: '/blocks/sidebar-06/light.png',
    dark: '/blocks/sidebar-06/dark.png',
  },
  // Generated by `npm run sync:blocks` from the sibling component files — do not edit by hand.
  files: [
    {
      name: 'sidebar-06.component.html',
      path: 'src/components/sidebar-06/sidebar-06.component.html',
      content: `<div class="flex min-h-screen items-center justify-center">
  <p>Sidebar 06</p>
</div>
`,
      language: 'html',
    },
    {
      name: 'sidebar-06.component.ts',
      path: 'src/components/sidebar-06/sidebar-06.component.ts',
      content: `import { Component } from '@angular/core';

@Component({
  selector: 'lib-sidebar-06',
  standalone: true,
  imports: [],
  templateUrl: './sidebar-06.component.html',
})
export class Sidebar06Component {}
`,
      language: 'typescript',
    },
  ],
};
