import type { Block } from '@doc/domain/components/block-container/block-container.component';

import { Sidebar06Component } from './sidebar-06.component';

export const sidebar06Block: Block = {
  id: 'sidebar-06',
  title: 'Sidebar 06',
  description: 'A sidebar with submenus as dropdowns.',
  component: Sidebar06Component,
  category: 'Sidebar',
  image: {
    light: '/blocks/sidebar-06/light.png',
    dark: '/blocks/sidebar-06/dark.png',
  },
  // Generated by `npm run sync:blocks` from the sibling component files — do not edit by hand.
  files: [
    {
      name: 'sidebar-06-app-sidebar.component.html',
      path: 'src/components/sidebar-06/sidebar-06-app-sidebar.component.html',
      content: `<z-sidebar>
  <div z-sidebar-header>
    <ul z-sidebar-menu>
      <li z-sidebar-menu-item>
        <a z-sidebar-menu-button zSize="lg" href="#">
          <div
            class="bg-sidebar-primary text-sidebar-primary-foreground flex aspect-square size-8 items-center justify-center rounded-lg"
          >
            <ng-icon name="lucideGalleryVerticalEnd" class="size-4" />
          </div>
          <div class="flex flex-col gap-0.5 leading-none">
            <span class="font-medium">Documentation</span>
            <span>v1.0.0</span>
          </div>
        </a>
      </li>
    </ul>
  </div>

  <z-sidebar-content>
    <lib-sidebar-06-nav-main [items]="navMain" />
  </z-sidebar-content>

  <div z-sidebar-footer>
    <div class="p-1">
      <lib-sidebar-06-sidebar-opt-in-form />
    </div>
  </div>

  <button z-sidebar-rail aria-label="Toggle Sidebar"></button>
</z-sidebar>
`,
      language: 'html',
    },
    {
      name: 'sidebar-06-app-sidebar.component.ts',
      path: 'src/components/sidebar-06/sidebar-06-app-sidebar.component.ts',
      content: `import { ChangeDetectionStrategy, Component } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideGalleryVerticalEnd } from '@ng-icons/lucide';

import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

import { Sidebar06NavMainComponent, type Sidebar06NavGroup } from './sidebar-06-nav-main.component';
import { Sidebar06SidebarOptInFormComponent } from './sidebar-06-sidebar-opt-in-form.component';

@Component({
  selector: 'lib-sidebar-06-app-sidebar',
  standalone: true,
  imports: [...ZardSidebarImports, Sidebar06NavMainComponent, Sidebar06SidebarOptInFormComponent, NgIcon],
  viewProviders: [provideIcons({ lucideGalleryVerticalEnd })],
  templateUrl: './sidebar-06-app-sidebar.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Sidebar06AppSidebarComponent {
  // This is sample data.
  protected readonly navMain: readonly Sidebar06NavGroup[] = [
    {
      title: 'Getting Started',
      url: '#',
      items: [
        { title: 'Installation', url: '#' },
        { title: 'Project Structure', url: '#' },
      ],
    },
    {
      title: 'Building Your Application',
      url: '#',
      items: [
        { title: 'Routing', url: '#' },
        { title: 'Data Fetching', url: '#', isActive: true },
        { title: 'Rendering', url: '#' },
        { title: 'Caching', url: '#' },
        { title: 'Styling', url: '#' },
        { title: 'Optimizing', url: '#' },
        { title: 'Configuring', url: '#' },
        { title: 'Testing', url: '#' },
        { title: 'Authentication', url: '#' },
        { title: 'Deploying', url: '#' },
        { title: 'Upgrading', url: '#' },
        { title: 'Examples', url: '#' },
      ],
    },
    {
      title: 'API Reference',
      url: '#',
      items: [
        { title: 'Components', url: '#' },
        { title: 'Style Guide', url: '#' },
        { title: 'Functions', url: '#' },
        { title: 'angular.json Options', url: '#' },
        { title: 'CLI', url: '#' },
        { title: 'Hydration', url: '#' },
      ],
    },
    {
      title: 'Architecture',
      url: '#',
      items: [
        { title: 'Accessibility', url: '#' },
        { title: 'Hot Module Replacement', url: '#' },
        { title: 'Angular Compiler', url: '#' },
        { title: 'Supported Browsers', url: '#' },
        { title: 'esbuild', url: '#' },
      ],
    },
  ];
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-06-nav-main.component.html',
      path: 'src/components/sidebar-06/sidebar-06-nav-main.component.html',
      content: `<div z-sidebar-group>
  <ul z-sidebar-menu>
    @for (group of items(); track group.title) {
      <li z-sidebar-menu-item>
        <button
          z-sidebar-menu-button
          z-dropdown
          [zDropdownMenu]="groupMenu"
          class="data-[state=open]:bg-sidebar-accent data-[state=open]:text-sidebar-accent-foreground"
        >
          {{ group.title }}
          <ng-icon name="lucideMoreHorizontal" class="ml-auto" />
        </button>

        <!-- Kept outside an @if: a template reference declared inside a control-flow block is not
             visible to the trigger above it. -->
        <z-dropdown-menu-content
          #groupMenu="zDropdownMenuContent"
          class="min-w-56 rounded-lg"
          zSide="right"
          zAlign="start"
        >
          @for (item of group.items; track item.title) {
            <z-dropdown-menu-item>
              <a [href]="item.url">{{ item.title }}</a>
            </z-dropdown-menu-item>
          }
        </z-dropdown-menu-content>
      </li>
    }
  </ul>
</div>
`,
      language: 'html',
    },
    {
      name: 'sidebar-06-nav-main.component.ts',
      path: 'src/components/sidebar-06/sidebar-06-nav-main.component.ts',
      content: `import { ChangeDetectionStrategy, Component, inject, input } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideMoreHorizontal } from '@ng-icons/lucide';

import { ZardDropdownImports } from '@zard/components/dropdown/dropdown.imports';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';
import { ZardSidebarService } from '@zard/components/sidebar/sidebar.service';

export interface Sidebar06NavItem {
  readonly title: string;
  readonly url: string;
  readonly isActive?: boolean;
}

export interface Sidebar06NavGroup {
  readonly title: string;
  readonly url: string;
  readonly items: readonly Sidebar06NavItem[];
}

@Component({
  selector: 'lib-sidebar-06-nav-main',
  standalone: true,
  imports: [...ZardSidebarImports, ...ZardDropdownImports, NgIcon],
  viewProviders: [provideIcons({ lucideMoreHorizontal })],
  templateUrl: './sidebar-06-nav-main.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Sidebar06NavMainComponent {
  readonly items = input<readonly Sidebar06NavGroup[]>([]);

  protected readonly sidebar = inject(ZardSidebarService);
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-06-sidebar-opt-in-form.component.html',
      path: 'src/components/sidebar-06/sidebar-06-sidebar-opt-in-form.component.html',
      content: `<z-card class="gap-2 py-4 shadow-none">
  <div z-card-header class="px-4">
    <z-card-title zTitle="Subscribe to our newsletter" class="text-sm" />
    <z-card-description zDescription="Opt-in to receive updates and news about the sidebar." />
  </div>

  <div z-card-content class="px-4">
    <form>
      <div class="grid gap-2.5">
        <input z-input z-sidebar-input type="email" placeholder="Email" />

        <button z-button zSize="sm" class="bg-sidebar-primary text-sidebar-primary-foreground w-full shadow-none">
          Subscribe
        </button>
      </div>
    </form>
  </div>
</z-card>
`,
      language: 'html',
    },
    {
      name: 'sidebar-06-sidebar-opt-in-form.component.ts',
      path: 'src/components/sidebar-06/sidebar-06-sidebar-opt-in-form.component.ts',
      content: `import { ChangeDetectionStrategy, Component } from '@angular/core';

import { ZardButtonComponent } from '@zard/components/button/button.component';
import { ZardCardImports } from '@zard/components/card/card.imports';
import { ZardInputComponent } from '@zard/components/input/input.component';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

@Component({
  selector: 'lib-sidebar-06-sidebar-opt-in-form',
  standalone: true,
  imports: [...ZardCardImports, ...ZardSidebarImports, ZardButtonComponent, ZardInputComponent],
  templateUrl: './sidebar-06-sidebar-opt-in-form.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Sidebar06SidebarOptInFormComponent {}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-06.component.html',
      path: 'src/components/sidebar-06/sidebar-06.component.html',
      content: `<z-sidebar-provider>
  <lib-sidebar-06-app-sidebar />

  <main z-sidebar-inset>
    <header class="flex h-16 shrink-0 items-center gap-2 border-b px-4">
      <button z-sidebar-trigger class="-ml-1" aria-label="Toggle Sidebar"></button>

      <z-separator
        zOrientation="vertical"
        class="mr-2 data-[orientation=vertical]:h-4 data-[orientation=vertical]:self-center"
      />

      <z-breadcrumb>
        <z-breadcrumb-item class="hidden md:block">
          <a z-breadcrumb-link href="#">Build Your Application</a>
        </z-breadcrumb-item>
        <z-breadcrumb-separator class="hidden md:block" />
        <z-breadcrumb-item>
          <span z-breadcrumb-page>Data Fetching</span>
        </z-breadcrumb-item>
      </z-breadcrumb>
    </header>

    <div class="flex flex-1 flex-col gap-4 p-4">
      <div class="grid auto-rows-min gap-4 md:grid-cols-3">
        <div class="bg-muted/50 aspect-video rounded-xl"></div>
        <div class="bg-muted/50 aspect-video rounded-xl"></div>
        <div class="bg-muted/50 aspect-video rounded-xl"></div>
      </div>
      <div class="bg-muted/50 min-h-[100vh] flex-1 rounded-xl md:min-h-min"></div>
    </div>
  </main>
</z-sidebar-provider>
`,
      language: 'html',
    },
    {
      name: 'sidebar-06.component.ts',
      path: 'src/components/sidebar-06/sidebar-06.component.ts',
      content: `import { ChangeDetectionStrategy, Component } from '@angular/core';

import { ZardBreadcrumbImports } from '@zard/components/breadcrumb/breadcrumb.imports';
import { ZardSeparatorComponent } from '@zard/components/separator/separator.component';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

import { Sidebar06AppSidebarComponent } from './sidebar-06-app-sidebar.component';

@Component({
  selector: 'lib-sidebar-06',
  standalone: true,
  imports: [...ZardSidebarImports, ...ZardBreadcrumbImports, ZardSeparatorComponent, Sidebar06AppSidebarComponent],
  templateUrl: './sidebar-06.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Sidebar06Component {}
`,
      language: 'typescript',
    },
  ],
};
