import type { Block } from '@doc/domain/components/block-container/block-container.component';

import { Sidebar10Component } from './sidebar-10.component';

export const sidebar10Block: Block = {
  id: 'sidebar-10',
  title: 'Sidebar 10',
  description: 'A sidebar in a popover.',
  component: Sidebar10Component,
  category: 'Sidebar',
  image: {
    light: '/blocks/sidebar-10/light.png',
    dark: '/blocks/sidebar-10/dark.png',
  },
  // Generated by `npm run sync:blocks` from the sibling component files — do not edit by hand.
  files: [
    {
      name: 'sidebar-10-app-sidebar.component.html',
      path: 'src/components/sidebar-10/sidebar-10-app-sidebar.component.html',
      content: `<z-sidebar class="border-r-0">
  <div z-sidebar-header>
    <lib-sidebar-10-team-switcher [teams]="teams" />
    <lib-sidebar-10-nav-main [items]="navMain" />
  </div>

  <z-sidebar-content>
    <lib-sidebar-10-nav-favorites [favorites]="favorites" />
    <lib-sidebar-10-nav-workspaces [workspaces]="workspaces" />
    <lib-sidebar-10-nav-secondary [items]="navSecondary" class="mt-auto" />
  </z-sidebar-content>

  <button z-sidebar-rail aria-label="Toggle Sidebar"></button>
</z-sidebar>
`,
      language: 'html',
    },
    {
      name: 'sidebar-10-app-sidebar.component.ts',
      path: 'src/components/sidebar-10/sidebar-10-app-sidebar.component.ts',
      content: `import { ChangeDetectionStrategy, Component } from '@angular/core';

import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

import { Sidebar10NavFavoritesComponent, type Sidebar10Favorite } from './sidebar-10-nav-favorites.component';
import { Sidebar10NavMainComponent, type Sidebar10NavItem } from './sidebar-10-nav-main.component';
import { Sidebar10NavSecondaryComponent, type Sidebar10SecondaryItem } from './sidebar-10-nav-secondary.component';
import { Sidebar10NavWorkspacesComponent, type Sidebar10Workspace } from './sidebar-10-nav-workspaces.component';
import { Sidebar10TeamSwitcherComponent, type Sidebar10Team } from './sidebar-10-team-switcher.component';

@Component({
  selector: 'lib-sidebar-10-app-sidebar',
  standalone: true,
  imports: [
    ...ZardSidebarImports,
    Sidebar10TeamSwitcherComponent,
    Sidebar10NavMainComponent,
    Sidebar10NavFavoritesComponent,
    Sidebar10NavWorkspacesComponent,
    Sidebar10NavSecondaryComponent,
  ],
  templateUrl: './sidebar-10-app-sidebar.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Sidebar10AppSidebarComponent {
  // This is sample data.
  protected readonly teams: readonly Sidebar10Team[] = [
    { name: 'Acme Inc', logo: 'lucideCommand', plan: 'Enterprise' },
    { name: 'Acme Corp.', logo: 'lucideAudioWaveform', plan: 'Startup' },
    { name: 'Evil Corp.', logo: 'lucideCommand', plan: 'Free' },
  ];

  protected readonly navMain: readonly Sidebar10NavItem[] = [
    { title: 'Search', url: '#', icon: 'lucideSearch' },
    { title: 'Ask AI', url: '#', icon: 'lucideSparkles' },
    { title: 'Home', url: '#', icon: 'lucideHouse', isActive: true },
    { title: 'Inbox', url: '#', icon: 'lucideInbox', badge: '10' },
  ];

  protected readonly navSecondary: readonly Sidebar10SecondaryItem[] = [
    { title: 'Calendar', url: '#', icon: 'lucideCalendar' },
    { title: 'Settings', url: '#', icon: 'lucideSettings2' },
    { title: 'Templates', url: '#', icon: 'lucideBlocks' },
    { title: 'Trash', url: '#', icon: 'lucideTrash2' },
    { title: 'Help', url: '#', icon: 'lucideMessageCircleQuestion' },
  ];

  protected readonly favorites: readonly Sidebar10Favorite[] = [
    { name: 'Project Management & Task Tracking', url: '#', emoji: '📊' },
    { name: 'Family Recipe Collection & Meal Planning', url: '#', emoji: '🍳' },
    { name: 'Fitness Tracker & Workout Routines', url: '#', emoji: '💪' },
    { name: 'Book Notes & Reading List', url: '#', emoji: '📚' },
    { name: 'Sustainable Gardening Tips & Plant Care', url: '#', emoji: '🌱' },
    { name: 'Language Learning Progress & Resources', url: '#', emoji: '🗣️' },
    { name: 'Home Renovation Ideas & Budget Tracker', url: '#', emoji: '🏠' },
    { name: 'Personal Finance & Investment Portfolio', url: '#', emoji: '💰' },
    { name: 'Movie & TV Show Watchlist with Reviews', url: '#', emoji: '🎬' },
    { name: 'Daily Habit Tracker & Goal Setting', url: '#', emoji: '✅' },
  ];

  protected readonly workspaces: readonly Sidebar10Workspace[] = [
    {
      name: 'Personal Life Management',
      emoji: '🏠',
      pages: [
        { name: 'Daily Journal & Reflection', emoji: '📔' },
        { name: 'Health & Wellness Tracker', emoji: '🍏' },
        { name: 'Personal Growth & Learning Goals', emoji: '🌟' },
      ],
    },
    {
      name: 'Professional Development',
      emoji: '💼',
      pages: [
        { name: 'Career Objectives & Milestones', emoji: '🎯' },
        { name: 'Skill Acquisition & Training Log', emoji: '🧠' },
        { name: 'Networking Contacts & Events', emoji: '🤝' },
      ],
    },
    {
      name: 'Creative Projects',
      emoji: '🎨',
      pages: [
        { name: 'Writing Ideas & Story Outlines', emoji: '✍️' },
        { name: 'Art & Design Portfolio', emoji: '🖼️' },
        { name: 'Music Composition & Practice Log', emoji: '🎵' },
      ],
    },
    {
      name: 'Travel & Adventure',
      emoji: '🌎',
      pages: [
        { name: 'Trip Planning & Itineraries', emoji: '🗺️' },
        { name: 'Travel Bucket List & Inspiration', emoji: '🌎' },
        { name: 'Travel Journal & Photo Gallery', emoji: '📸' },
      ],
    },
  ];
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-10-nav-actions.component.html',
      path: 'src/components/sidebar-10/sidebar-10-nav-actions.component.html',
      content: `<div class="flex items-center gap-2 text-sm">
  <div class="text-muted-foreground hidden font-medium md:inline-block">Edit Oct 08</div>

  <button z-button zType="ghost" zSize="icon" class="h-7 w-7" aria-label="Favorite">
    <ng-icon name="lucideStar" />
  </button>

  <button
    z-button
    zType="ghost"
    zSize="icon"
    class="data-[state=open]:bg-accent h-7 w-7"
    aria-label="More actions"
    [zPopover]="actions"
    zAlign="end"
  >
    <ng-icon name="lucideMoreHorizontal" />
  </button>

  <ng-template #actions>
    <div class="w-56 overflow-hidden rounded-lg p-0">
      <z-sidebar zCollapsible="none" class="bg-transparent">
        <z-sidebar-content>
          @for (group of groups; track $index) {
            <div z-sidebar-group class="border-b last:border-none">
              <div z-sidebar-group-content class="gap-0">
                <ul z-sidebar-menu>
                  @for (item of group; track item.label) {
                    <li z-sidebar-menu-item>
                      <button z-sidebar-menu-button>
                        <ng-icon [name]="item.icon" />
                        <span>{{ item.label }}</span>
                      </button>
                    </li>
                  }
                </ul>
              </div>
            </div>
          }
        </z-sidebar-content>
      </z-sidebar>
    </div>
  </ng-template>
</div>
`,
      language: 'html',
    },
    {
      name: 'sidebar-10-nav-actions.component.ts',
      path: 'src/components/sidebar-10/sidebar-10-nav-actions.component.ts',
      content: `import { ChangeDetectionStrategy, Component } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import {
  lucideArrowDown,
  lucideArrowUp,
  lucideBell,
  lucideCopy,
  lucideCornerUpLeft,
  lucideCornerUpRight,
  lucideFileText,
  lucideGalleryVerticalEnd,
  lucideLineChart,
  lucideLink,
  lucideMoreHorizontal,
  lucideSettings2,
  lucideStar,
  lucideTrash,
  lucideTrash2,
} from '@ng-icons/lucide';

import { ZardButtonComponent } from '@zard/components/button/button.component';
import { ZardPopoverImports } from '@zard/components/popover/popover.imports';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

interface ActionItem {
  readonly label: string;
  readonly icon: string;
}

@Component({
  selector: 'lib-sidebar-10-nav-actions',
  standalone: true,
  imports: [...ZardSidebarImports, ...ZardPopoverImports, ZardButtonComponent, NgIcon],
  viewProviders: [
    provideIcons({
      lucideArrowDown,
      lucideArrowUp,
      lucideBell,
      lucideCopy,
      lucideCornerUpLeft,
      lucideCornerUpRight,
      lucideFileText,
      lucideGalleryVerticalEnd,
      lucideLineChart,
      lucideLink,
      lucideMoreHorizontal,
      lucideSettings2,
      lucideStar,
      lucideTrash,
      lucideTrash2,
    }),
  ],
  templateUrl: './sidebar-10-nav-actions.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Sidebar10NavActionsComponent {
  // This is sample data.
  protected readonly groups: readonly (readonly ActionItem[])[] = [
    [
      { label: 'Customize Page', icon: 'lucideSettings2' },
      { label: 'Turn into wiki', icon: 'lucideFileText' },
    ],
    [
      { label: 'Copy Link', icon: 'lucideLink' },
      { label: 'Duplicate', icon: 'lucideCopy' },
      { label: 'Move to', icon: 'lucideCornerUpRight' },
      { label: 'Move to Trash', icon: 'lucideTrash2' },
    ],
    [
      { label: 'Undo', icon: 'lucideCornerUpLeft' },
      { label: 'View analytics', icon: 'lucideLineChart' },
      { label: 'Version History', icon: 'lucideGalleryVerticalEnd' },
      { label: 'Show delete pages', icon: 'lucideTrash' },
      { label: 'Notifications', icon: 'lucideBell' },
    ],
    [
      { label: 'Import', icon: 'lucideArrowUp' },
      { label: 'Export', icon: 'lucideArrowDown' },
    ],
  ];
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-10-nav-favorites.component.html',
      path: 'src/components/sidebar-10/sidebar-10-nav-favorites.component.html',
      content: `<div z-sidebar-group class="group-data-[collapsible=icon]:hidden">
  <div z-sidebar-group-label>Favorites</div>

  <ul z-sidebar-menu>
    @for (item of favorites(); track item.name) {
      <li z-sidebar-menu-item>
        <a z-sidebar-menu-button [href]="item.url" [title]="item.name">
          <span>{{ item.emoji }}</span>
          <span>{{ item.name }}</span>
        </a>

        <button z-sidebar-menu-action zShowOnHover z-dropdown [zDropdownMenu]="favoriteMenu">
          <ng-icon name="lucideMoreHorizontal" />
          <span class="sr-only">More</span>
        </button>

        <z-dropdown-menu-content #favoriteMenu="zDropdownMenuContent" class="w-56 rounded-lg">
          <z-dropdown-menu-item>
            <ng-icon name="lucideStarOff" class="text-muted-foreground" />
            <span>Remove from Favorites</span>
          </z-dropdown-menu-item>
          <z-dropdown-menu-separator />
          <z-dropdown-menu-item>
            <ng-icon name="lucideLink" class="text-muted-foreground" />
            <span>Copy Link</span>
          </z-dropdown-menu-item>
          <z-dropdown-menu-item>
            <ng-icon name="lucideArrowUpRight" class="text-muted-foreground" />
            <span>Open in New Tab</span>
          </z-dropdown-menu-item>
          <z-dropdown-menu-separator />
          <z-dropdown-menu-item>
            <ng-icon name="lucideTrash2" class="text-muted-foreground" />
            <span>Delete</span>
          </z-dropdown-menu-item>
        </z-dropdown-menu-content>
      </li>
    }

    <li z-sidebar-menu-item>
      <button z-sidebar-menu-button class="text-sidebar-foreground/70">
        <ng-icon name="lucideMoreHorizontal" />
        <span>More</span>
      </button>
    </li>
  </ul>
</div>
`,
      language: 'html',
    },
    {
      name: 'sidebar-10-nav-favorites.component.ts',
      path: 'src/components/sidebar-10/sidebar-10-nav-favorites.component.ts',
      content: `import { ChangeDetectionStrategy, Component, input } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideArrowUpRight, lucideLink, lucideMoreHorizontal, lucideStarOff, lucideTrash2 } from '@ng-icons/lucide';

import { ZardDropdownImports } from '@zard/components/dropdown/dropdown.imports';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

export interface Sidebar10Favorite {
  readonly name: string;
  readonly url: string;
  readonly emoji: string;
}

@Component({
  selector: 'lib-sidebar-10-nav-favorites',
  standalone: true,
  imports: [...ZardSidebarImports, ...ZardDropdownImports, NgIcon],
  viewProviders: [
    provideIcons({ lucideArrowUpRight, lucideLink, lucideMoreHorizontal, lucideStarOff, lucideTrash2 }),
  ],
  templateUrl: './sidebar-10-nav-favorites.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Sidebar10NavFavoritesComponent {
  readonly favorites = input<readonly Sidebar10Favorite[]>([]);
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-10-nav-main.component.html',
      path: 'src/components/sidebar-10/sidebar-10-nav-main.component.html',
      content: `<ul z-sidebar-menu>
  @for (item of items(); track item.title) {
    <li z-sidebar-menu-item>
      <a z-sidebar-menu-button [href]="item.url" [zActive]="!!item.isActive">
        <ng-icon [name]="item.icon" />
        <span>{{ item.title }}</span>
      </a>
    </li>
  }
</ul>
`,
      language: 'html',
    },
    {
      name: 'sidebar-10-nav-main.component.ts',
      path: 'src/components/sidebar-10/sidebar-10-nav-main.component.ts',
      content: `import { ChangeDetectionStrategy, Component, input } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideHouse, lucideInbox, lucideSearch, lucideSparkles } from '@ng-icons/lucide';

import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

export interface Sidebar10NavItem {
  readonly title: string;
  readonly url: string;
  readonly icon: string;
  readonly isActive?: boolean;
  readonly badge?: string;
}

@Component({
  selector: 'lib-sidebar-10-nav-main',
  standalone: true,
  imports: [...ZardSidebarImports, NgIcon],
  viewProviders: [provideIcons({ lucideHouse, lucideInbox, lucideSearch, lucideSparkles })],
  templateUrl: './sidebar-10-nav-main.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Sidebar10NavMainComponent {
  readonly items = input<readonly Sidebar10NavItem[]>([]);
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-10-nav-secondary.component.html',
      path: 'src/components/sidebar-10/sidebar-10-nav-secondary.component.html',
      content: `<div z-sidebar-group [class]="class()">
  <div z-sidebar-group-content>
    <ul z-sidebar-menu>
      @for (item of items(); track item.title) {
        <li z-sidebar-menu-item>
          <a z-sidebar-menu-button [href]="item.url">
            <ng-icon [name]="item.icon" />
            <span>{{ item.title }}</span>
          </a>
        </li>
        @if (item.badge) {
          <div z-sidebar-menu-badge>{{ item.badge }}</div>
        }
      }
    </ul>
  </div>
</div>
`,
      language: 'html',
    },
    {
      name: 'sidebar-10-nav-secondary.component.ts',
      path: 'src/components/sidebar-10/sidebar-10-nav-secondary.component.ts',
      content: `import { ChangeDetectionStrategy, Component, input } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideBlocks, lucideCalendar, lucideMessageCircleQuestion, lucideSettings2, lucideTrash2 } from '@ng-icons/lucide';

import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

export interface Sidebar10SecondaryItem {
  readonly title: string;
  readonly url: string;
  readonly icon: string;
  readonly badge?: string;
}

@Component({
  selector: 'lib-sidebar-10-nav-secondary',
  standalone: true,
  imports: [...ZardSidebarImports, NgIcon],
  viewProviders: [provideIcons({ lucideBlocks, lucideCalendar, lucideMessageCircleQuestion, lucideSettings2, lucideTrash2 })],
  templateUrl: './sidebar-10-nav-secondary.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Sidebar10NavSecondaryComponent {
  readonly items = input<readonly Sidebar10SecondaryItem[]>([]);
  readonly class = input<string>('');
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-10-nav-workspaces.component.html',
      path: 'src/components/sidebar-10/sidebar-10-nav-workspaces.component.html',
      content: `<div z-sidebar-group>
  <div z-sidebar-group-label>Workspaces</div>

  <div z-sidebar-group-content>
    <ul z-sidebar-menu>
      @for (workspace of workspaces(); track workspace.name) {
        <li z-sidebar-menu-item z-collapsible>
          <a z-sidebar-menu-button href="#">
            <span>{{ workspace.emoji }}</span>
            <span>{{ workspace.name }}</span>
          </a>

          <button
            z-collapsible-trigger
            z-sidebar-menu-action
            zShowOnHover
            class="bg-sidebar-accent text-sidebar-accent-foreground left-2 data-[state=open]:rotate-90"
          >
            <ng-icon name="lucideChevronRight" />
            <span class="sr-only">Toggle</span>
          </button>

          <button z-sidebar-menu-action zShowOnHover>
            <ng-icon name="lucidePlus" />
            <span class="sr-only">Add page</span>
          </button>

          <z-collapsible-content>
            <ul z-sidebar-menu-sub>
              @for (page of workspace.pages; track page.name) {
                <li z-sidebar-menu-sub-item>
                  <a z-sidebar-menu-sub-button href="#">
                    <span>{{ page.emoji }}</span>
                    <span>{{ page.name }}</span>
                  </a>
                </li>
              }
            </ul>
          </z-collapsible-content>
        </li>
      }

      <li z-sidebar-menu-item>
        <button z-sidebar-menu-button class="text-sidebar-foreground/70">
          <ng-icon name="lucideMoreHorizontal" />
          <span>More</span>
        </button>
      </li>
    </ul>
  </div>
</div>
`,
      language: 'html',
    },
    {
      name: 'sidebar-10-nav-workspaces.component.ts',
      path: 'src/components/sidebar-10/sidebar-10-nav-workspaces.component.ts',
      content: `import { ChangeDetectionStrategy, Component, input } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideChevronRight, lucideMoreHorizontal, lucidePlus } from '@ng-icons/lucide';

import { ZardCollapsibleImports } from '@zard/components/collapsible/collapsible.imports';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

export interface Sidebar10Page {
  readonly name: string;
  readonly emoji: string;
}

export interface Sidebar10Workspace {
  readonly name: string;
  readonly emoji: string;
  readonly pages: readonly Sidebar10Page[];
}

@Component({
  selector: 'lib-sidebar-10-nav-workspaces',
  standalone: true,
  imports: [...ZardSidebarImports, ...ZardCollapsibleImports, NgIcon],
  viewProviders: [provideIcons({ lucideChevronRight, lucideMoreHorizontal, lucidePlus })],
  templateUrl: './sidebar-10-nav-workspaces.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Sidebar10NavWorkspacesComponent {
  readonly workspaces = input<readonly Sidebar10Workspace[]>([]);
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-10-team-switcher.component.html',
      path: 'src/components/sidebar-10/sidebar-10-team-switcher.component.html',
      content: `<ul z-sidebar-menu>
  <li z-sidebar-menu-item>
    <button z-sidebar-menu-button z-dropdown [zDropdownMenu]="teamMenu" class="w-fit px-1.5">
      <div
        class="bg-sidebar-primary text-sidebar-primary-foreground flex aspect-square size-5 items-center justify-center rounded-md"
      >
        <ng-icon [name]="activeTeam()?.logo ?? ''" class="size-3" />
      </div>
      <span class="truncate font-medium">{{ activeTeam()?.name }}</span>
      <ng-icon name="lucideChevronDown" class="opacity-50" />
    </button>

    <z-dropdown-menu-content #teamMenu="zDropdownMenuContent" class="w-64 rounded-lg">
      <z-dropdown-menu-label class="text-muted-foreground text-xs">Teams</z-dropdown-menu-label>

      @for (team of teams(); track team.name; let index = $index) {
        <z-dropdown-menu-item class="gap-2 p-2" (click)="selectedTeam.set(team)">
          <div class="flex size-6 items-center justify-center rounded-xs border">
            <ng-icon [name]="team.logo" class="size-4 shrink-0" />
          </div>
          {{ team.name }}
          <z-dropdown-menu-shortcut>⌘{{ index + 1 }}</z-dropdown-menu-shortcut>
        </z-dropdown-menu-item>
      }

      <z-dropdown-menu-separator />

      <z-dropdown-menu-item class="gap-2 p-2">
        <div class="bg-background flex size-6 items-center justify-center rounded-md border">
          <ng-icon name="lucidePlus" class="size-4" />
        </div>
        <div class="text-muted-foreground font-medium">Add team</div>
      </z-dropdown-menu-item>
    </z-dropdown-menu-content>
  </li>
</ul>
`,
      language: 'html',
    },
    {
      name: 'sidebar-10-team-switcher.component.ts',
      path: 'src/components/sidebar-10/sidebar-10-team-switcher.component.ts',
      content: `import { ChangeDetectionStrategy, Component, input, signal } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideAudioWaveform, lucideChevronDown, lucideCommand, lucidePlus } from '@ng-icons/lucide';

import { ZardDropdownImports } from '@zard/components/dropdown/dropdown.imports';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

export interface Sidebar10Team {
  readonly name: string;
  readonly logo: string;
  readonly plan: string;
}

@Component({
  selector: 'lib-sidebar-10-team-switcher',
  standalone: true,
  imports: [...ZardSidebarImports, ...ZardDropdownImports, NgIcon],
  viewProviders: [provideIcons({ lucideAudioWaveform, lucideChevronDown, lucideCommand, lucidePlus })],
  templateUrl: './sidebar-10-team-switcher.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Sidebar10TeamSwitcherComponent {
  readonly teams = input<readonly Sidebar10Team[]>([]);

  protected readonly selectedTeam = signal<Sidebar10Team | null>(null);

  protected activeTeam(): Sidebar10Team | undefined {
    return this.selectedTeam() ?? this.teams()[0];
  }
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-10.component.html',
      path: 'src/components/sidebar-10/sidebar-10.component.html',
      content: `<z-sidebar-provider>
  <lib-sidebar-10-app-sidebar />

  <main z-sidebar-inset>
    <header class="flex h-14 shrink-0 items-center gap-2">
      <div class="flex flex-1 items-center gap-2 px-3">
        <button z-sidebar-trigger aria-label="Toggle Sidebar"></button>

        <z-separator zOrientation="vertical" class="mr-2 data-[orientation=vertical]:h-4" />

        <z-breadcrumb>
          <z-breadcrumb-item>
            <span z-breadcrumb-page class="line-clamp-1">Project Management &amp; Task Tracking</span>
          </z-breadcrumb-item>
        </z-breadcrumb>
      </div>

      <div class="ml-auto px-3">
        <lib-sidebar-10-nav-actions />
      </div>
    </header>

    <div class="flex flex-1 flex-col gap-4 px-4 py-10">
      <div class="bg-muted/50 mx-auto h-24 w-full max-w-3xl rounded-xl"></div>
      <div class="bg-muted/50 mx-auto h-full w-full max-w-3xl rounded-xl"></div>
    </div>
  </main>
</z-sidebar-provider>
`,
      language: 'html',
    },
    {
      name: 'sidebar-10.component.ts',
      path: 'src/components/sidebar-10/sidebar-10.component.ts',
      content: `import { ChangeDetectionStrategy, Component } from '@angular/core';

import { ZardBreadcrumbImports } from '@zard/components/breadcrumb/breadcrumb.imports';
import { ZardSeparatorComponent } from '@zard/components/separator/separator.component';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

import { Sidebar10AppSidebarComponent } from './sidebar-10-app-sidebar.component';
import { Sidebar10NavActionsComponent } from './sidebar-10-nav-actions.component';

@Component({
  selector: 'lib-sidebar-10',
  standalone: true,
  imports: [
    ...ZardSidebarImports,
    ...ZardBreadcrumbImports,
    ZardSeparatorComponent,
    Sidebar10AppSidebarComponent,
    Sidebar10NavActionsComponent,
  ],
  templateUrl: './sidebar-10.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Sidebar10Component {}
`,
      language: 'typescript',
    },
  ],
};
