import type { Block } from '@doc/domain/components/block-container/block-container.component';

import { Sidebar10Component } from './sidebar-10.component';

export const sidebar10Block: Block = {
  id: 'sidebar-10',
  title: 'Sidebar 10',
  description: 'A sidebar in a popover.',
  component: Sidebar10Component,
  category: 'Sidebar',
  image: {
    light: '/blocks/sidebar-10/light.png',
    dark: '/blocks/sidebar-10/dark.png',
  },
  // Generated by `npm run sync:blocks` from the sibling component files — do not edit by hand.
  files: [
    {
      name: 'sidebar-10.component.html',
      path: 'src/components/sidebar-10/sidebar-10.component.html',
      content: `<div class="flex min-h-screen items-center justify-center">
  <p>Sidebar 10</p>
</div>
`,
      language: 'html',
    },
    {
      name: 'sidebar-10.component.ts',
      path: 'src/components/sidebar-10/sidebar-10.component.ts',
      content: `import { Component } from '@angular/core';

@Component({
  selector: 'lib-sidebar-10',
  standalone: true,
  imports: [],
  templateUrl: './sidebar-10.component.html',
})
export class Sidebar10Component {}
`,
      language: 'typescript',
    },
  ],
};
