import type { Block } from '@doc/domain/components/block-container/block-container.component';

import { Signup03Component } from './signup-03.component';

export const signup03Block: Block = {
  id: 'signup-03',
  title: 'Signup with muted background',
  description: 'A signup page with a muted background color.',
  component: Signup03Component,
  category: 'Signup',
  image: {
    light: '/blocks/signup-03/light.png',
    dark: '/blocks/signup-03/dark.png',
  },
  // Generated by `npm run sync:blocks` from the sibling component files — do not edit by hand.
  files: [
    {
      name: 'signup-03.component.html',
      path: 'src/components/signup-03/signup-03.component.html',
      content: `<div class="bg-muted flex min-h-svh flex-col items-center justify-center gap-6 p-6 md:p-10">
  <div class="flex w-full max-w-sm flex-col gap-6">
    <a href="#" class="flex items-center gap-2 self-center font-medium">
      <div class="bg-primary text-primary-foreground flex size-6 items-center justify-center rounded-md">
        <ng-icon name="lucideGalleryVerticalEnd" class="size-4" />
      </div>
      Acme Inc.
    </a>
    <div class="flex flex-col gap-6">
      <z-card>
        <div z-card-header class="text-center">
          <z-card-title zTitle="Create your account" class="text-xl" />
          <z-card-description zDescription="Enter your email below to create your account" />
        </div>
        <div z-card-content>
          <form [formGroup]="signupForm" (ngSubmit)="onSubmit()">
            <div z-field-group>
              <div z-field>
                <label z-field-label for="name">Full Name</label>
                <input z-input id="name" type="text" placeholder="John Doe" formControlName="name" required />
              </div>
              <div z-field>
                <label z-field-label for="email">Email</label>
                <input z-input id="email" type="email" placeholder="m@example.com" formControlName="email" required />
              </div>
              <div z-field>
                <div z-field class="grid grid-cols-2 gap-4">
                  <div z-field>
                    <label z-field-label for="password">Password</label>
                    <input z-input id="password" type="password" formControlName="password" required />
                  </div>
                  <div z-field>
                    <label z-field-label for="confirm-password">Confirm Password</label>
                    <input z-input id="confirm-password" type="password" formControlName="confirmPassword" required />
                  </div>
                </div>
                <p z-field-description>Must be at least 8 characters long.</p>
              </div>
              <div z-field>
                <button z-button type="submit" [zLoading]="isLoading()" [zDisabled]="isLoading()">
                  Create Account
                </button>
                <p z-field-description class="text-center">
                  Already have an account?
                  <a href="#">Sign in</a>
                </p>
              </div>
            </div>
          </form>
        </div>
      </z-card>
      <!-- prettier-ignore -->
      <p z-field-description class="px-6 text-center">
        By clicking continue, you agree to our <a href="#">Terms of Service</a> and <a href="#">Privacy Policy</a>.
      </p>
    </div>
  </div>
</div>
`,
      language: 'html',
    },
    {
      name: 'signup-03.component.ts',
      path: 'src/components/signup-03/signup-03.component.ts',
      content: `import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';

import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideGalleryVerticalEnd } from '@ng-icons/lucide';

import { ZardButtonComponent } from '@zard/components/button/button.component';
import { ZardCardImports } from '@zard/components/card/card.imports';
import { ZardFieldImports } from '@zard/components/field/field.imports';
import { ZardInputComponent } from '@zard/components/input/input.component';

@Component({
  selector: 'lib-signup-03',
  imports: [
    ReactiveFormsModule,
    NgIcon,
    ZardButtonComponent,
    ZardInputComponent,
    ...ZardCardImports,
    ...ZardFieldImports,
  ],
  templateUrl: './signup-03.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  viewProviders: [provideIcons({ lucideGalleryVerticalEnd })],
})
export class Signup03Component {
  protected readonly isLoading = signal(false);

  protected readonly signupForm = new FormGroup({
    name: new FormControl('', [Validators.required]),
    email: new FormControl('', [Validators.required, Validators.email]),
    password: new FormControl('', [Validators.required, Validators.minLength(8)]),
    confirmPassword: new FormControl('', [Validators.required, Validators.minLength(8)]),
  });

  protected onSubmit(): void {
    if (this.signupForm.invalid) {
      this.signupForm.markAllAsTouched();
      return;
    }
    this.isLoading.set(true);
  }
}
`,
      language: 'typescript',
    },
  ],
};
