import type { Block } from '@doc/domain/components/block-container/block-container.component';

import { Sidebar14Component } from './sidebar-14.component';

export const sidebar14Block: Block = {
  id: 'sidebar-14',
  title: 'Sidebar 14',
  description: 'A sidebar on the right.',
  component: Sidebar14Component,
  category: 'Sidebar',
  image: {
    light: '/blocks/sidebar-14/light.png',
    dark: '/blocks/sidebar-14/dark.png',
  },
  // Generated by `npm run sync:blocks` from the sibling component files — do not edit by hand.
  files: [
    {
      name: 'sidebar-14.component.html',
      path: 'src/components/sidebar-14/sidebar-14.component.html',
      content: `<div class="flex min-h-screen items-center justify-center">
  <p>Sidebar 14</p>
</div>
`,
      language: 'html',
    },
    {
      name: 'sidebar-14.component.ts',
      path: 'src/components/sidebar-14/sidebar-14.component.ts',
      content: `import { Component } from '@angular/core';

@Component({
  selector: 'lib-sidebar-14',
  standalone: true,
  imports: [],
  templateUrl: './sidebar-14.component.html',
})
export class Sidebar14Component {}
`,
      language: 'typescript',
    },
  ],
};
