import type { Block } from '@doc/domain/components/block-container/block-container.component';

import { Sidebar14Component } from './sidebar-14.component';

export const sidebar14Block: Block = {
  id: 'sidebar-14',
  title: 'Sidebar 14',
  description: 'A sidebar on the right.',
  component: Sidebar14Component,
  category: 'Sidebar',
  image: {
    light: '/blocks/sidebar-14/light.png',
    dark: '/blocks/sidebar-14/dark.png',
  },
  // Generated by `npm run sync:blocks` from the sibling component files — do not edit by hand.
  files: [
    {
      name: 'sidebar-14-app-sidebar.component.html',
      path: 'src/components/sidebar-14/sidebar-14-app-sidebar.component.html',
      content: `<z-sidebar zSide="right">
  <z-sidebar-content>
    <div z-sidebar-group>
      <div z-sidebar-group-label>Table of Contents</div>

      <div z-sidebar-group-content>
        <ul z-sidebar-menu>
          @for (group of navMain; track group.title) {
            <li z-sidebar-menu-item>
              <a z-sidebar-menu-button [href]="group.url" class="font-medium">{{ group.title }}</a>

              @if (group.items.length) {
                <ul z-sidebar-menu-sub>
                  @for (item of group.items; track item.title) {
                    <li z-sidebar-menu-sub-item>
                      <a z-sidebar-menu-sub-button [href]="item.url" [zActive]="!!item.isActive">{{ item.title }}</a>
                    </li>
                  }
                </ul>
              }
            </li>
          }
        </ul>
      </div>
    </div>
  </z-sidebar-content>

  <button z-sidebar-rail aria-label="Toggle Sidebar"></button>
</z-sidebar>
`,
      language: 'html',
    },
    {
      name: 'sidebar-14-app-sidebar.component.ts',
      path: 'src/components/sidebar-14/sidebar-14-app-sidebar.component.ts',
      content: `import { ChangeDetectionStrategy, Component } from '@angular/core';

import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

interface NavItem {
  readonly title: string;
  readonly url: string;
  readonly isActive?: boolean;
}

interface NavGroup {
  readonly title: string;
  readonly url: string;
  readonly items: readonly NavItem[];
}

@Component({
  selector: 'lib-sidebar-14-app-sidebar',
  standalone: true,
  imports: [...ZardSidebarImports],
  templateUrl: './sidebar-14-app-sidebar.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Sidebar14AppSidebarComponent {
  // This is sample data.
  protected readonly navMain: readonly NavGroup[] = [
    {
      title: 'Getting Started',
      url: '#',
      items: [
        { title: 'Installation', url: '#' },
        { title: 'Project Structure', url: '#' },
      ],
    },
    {
      title: 'Build Your Application',
      url: '#',
      items: [
        { title: 'Routing', url: '#' },
        { title: 'Data Fetching', url: '#', isActive: true },
        { title: 'Rendering', url: '#' },
        { title: 'Caching', url: '#' },
        { title: 'Styling', url: '#' },
        { title: 'Optimizing', url: '#' },
        { title: 'Configuring', url: '#' },
        { title: 'Testing', url: '#' },
        { title: 'Authentication', url: '#' },
        { title: 'Deploying', url: '#' },
        { title: 'Upgrading', url: '#' },
        { title: 'Examples', url: '#' },
      ],
    },
    {
      title: 'API Reference',
      url: '#',
      items: [
        { title: 'Components', url: '#' },
        { title: 'File Conventions', url: '#' },
        { title: 'Functions', url: '#' },
        { title: 'next.config.js Options', url: '#' },
        { title: 'CLI', url: '#' },
        { title: 'Edge Runtime', url: '#' },
      ],
    },
    {
      title: 'Architecture',
      url: '#',
      items: [
        { title: 'Accessibility', url: '#' },
        { title: 'Fast Refresh', url: '#' },
        { title: 'Next.js Compiler', url: '#' },
        { title: 'Supported Browsers', url: '#' },
        { title: 'Turbopack', url: '#' },
      ],
    },
    {
      title: 'Community',
      url: '#',
      items: [{ title: 'Contribution Guide', url: '#' }],
    },
  ];
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-14.component.html',
      path: 'src/components/sidebar-14/sidebar-14.component.html',
      content: `<z-sidebar-provider>
  <main z-sidebar-inset>
    <header class="flex h-16 shrink-0 items-center gap-2 border-b px-4">
      <z-breadcrumb>
        <z-breadcrumb-item class="hidden md:block">
          <a z-breadcrumb-link href="#">Build Your Application</a>
        </z-breadcrumb-item>
        <z-breadcrumb-separator class="hidden md:block" />
        <z-breadcrumb-item>
          <span z-breadcrumb-page>Data Fetching</span>
        </z-breadcrumb-item>
      </z-breadcrumb>

      <button z-sidebar-trigger class="-mr-1 ml-auto rotate-180" aria-label="Toggle Sidebar"></button>
    </header>

    <div class="flex flex-1 flex-col gap-4 p-4">
      <div class="grid auto-rows-min gap-4 md:grid-cols-3">
        <div class="bg-muted/50 aspect-video rounded-xl"></div>
        <div class="bg-muted/50 aspect-video rounded-xl"></div>
        <div class="bg-muted/50 aspect-video rounded-xl"></div>
      </div>
      <div class="bg-muted/50 min-h-[100vh] flex-1 rounded-xl md:min-h-min"></div>
    </div>
  </main>

  <lib-sidebar-14-app-sidebar />
</z-sidebar-provider>
`,
      language: 'html',
    },
    {
      name: 'sidebar-14.component.ts',
      path: 'src/components/sidebar-14/sidebar-14.component.ts',
      content: `import { ChangeDetectionStrategy, Component } from '@angular/core';

import { ZardBreadcrumbImports } from '@zard/components/breadcrumb/breadcrumb.imports';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

import { Sidebar14AppSidebarComponent } from './sidebar-14-app-sidebar.component';

@Component({
  selector: 'lib-sidebar-14',
  standalone: true,
  imports: [...ZardSidebarImports, ...ZardBreadcrumbImports, Sidebar14AppSidebarComponent],
  templateUrl: './sidebar-14.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Sidebar14Component {}
`,
      language: 'typescript',
    },
  ],
};
