import type { Block } from '@doc/domain/components/block-container/block-container.component';

import { Signup01Component } from './signup-01.component';

export const signup01Block: Block = {
  id: 'signup-01',
  title: 'Signup form',
  description: 'A simple signup form.',
  component: Signup01Component,
  category: 'Signup',
  image: {
    light: '/blocks/signup-01/light.png',
    dark: '/blocks/signup-01/dark.png',
  },
  // Generated by `npm run sync:blocks` from the sibling component files — do not edit by hand.
  files: [
    {
      name: 'signup-01.component.html',
      path: 'src/components/signup-01/signup-01.component.html',
      content: `<div class="flex min-h-svh w-full items-center justify-center p-6 md:p-10">
  <div class="w-full max-w-sm">
    <z-card>
      <div z-card-header>
        <z-card-title zTitle="Create an account" />
        <z-card-description zDescription="Enter your information below to create your account" />
      </div>
      <div z-card-content>
        <form [formGroup]="signupForm" (ngSubmit)="onSubmit()">
          <div z-field-group>
            <div z-field>
              <label z-field-label for="name">Full Name</label>
              <input z-input id="name" type="text" placeholder="John Doe" formControlName="name" required />
            </div>
            <div z-field>
              <label z-field-label for="email">Email</label>
              <input z-input id="email" type="email" placeholder="m@example.com" formControlName="email" required />
              <p z-field-description>We'll use this to contact you. We will not share your email with anyone else.</p>
            </div>
            <div z-field>
              <label z-field-label for="password">Password</label>
              <input z-input id="password" type="password" formControlName="password" required />
              <p z-field-description>Must be at least 8 characters long.</p>
            </div>
            <div z-field>
              <label z-field-label for="confirm-password">Confirm Password</label>
              <input z-input id="confirm-password" type="password" formControlName="confirmPassword" required />
              <p z-field-description>Please confirm your password.</p>
            </div>
            <div z-field-group>
              <div z-field>
                <button z-button type="submit" [zLoading]="isLoading()" [zDisabled]="isLoading()">
                  Create Account
                </button>
                <button z-button zType="outline" type="button">Sign up with Google</button>
                <p z-field-description class="px-6 text-center">
                  Already have an account?
                  <a href="#">Sign in</a>
                </p>
              </div>
            </div>
          </div>
        </form>
      </div>
    </z-card>
  </div>
</div>
`,
      language: 'html',
    },
    {
      name: 'signup-01.component.ts',
      path: 'src/components/signup-01/signup-01.component.ts',
      content: `import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';

import { ZardButtonComponent } from '@zard/components/button/button.component';
import { ZardCardImports } from '@zard/components/card/card.imports';
import { ZardFieldImports } from '@zard/components/field/field.imports';
import { ZardInputComponent } from '@zard/components/input/input.component';

@Component({
  selector: 'lib-signup-01',
  imports: [ReactiveFormsModule, ZardButtonComponent, ZardInputComponent, ...ZardCardImports, ...ZardFieldImports],
  templateUrl: './signup-01.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Signup01Component {
  protected readonly isLoading = signal(false);

  protected readonly signupForm = new FormGroup({
    name: new FormControl('', [Validators.required]),
    email: new FormControl('', [Validators.required, Validators.email]),
    password: new FormControl('', [Validators.required, Validators.minLength(8)]),
    confirmPassword: new FormControl('', [Validators.required, Validators.minLength(8)]),
  });

  protected onSubmit(): void {
    if (this.signupForm.invalid) {
      this.signupForm.markAllAsTouched();
      return;
    }
    this.isLoading.set(true);
  }
}
`,
      language: 'typescript',
    },
  ],
};
