import type { Block } from '@doc/domain/components/block-container/block-container.component';

import { Sidebar04Component } from './sidebar-04.component';

export const sidebar04Block: Block = {
  id: 'sidebar-04',
  title: 'Sidebar 04',
  description: 'A floating sidebar with submenus.',
  component: Sidebar04Component,
  category: 'Sidebar',
  image: {
    light: '/blocks/sidebar-04/light.png',
    dark: '/blocks/sidebar-04/dark.png',
  },
  // Generated by `npm run sync:blocks` from the sibling component files — do not edit by hand.
  files: [
    {
      name: 'sidebar-04-app-sidebar.component.html',
      path: 'src/components/sidebar-04/sidebar-04-app-sidebar.component.html',
      content: `<z-sidebar zVariant="floating">
  <div z-sidebar-header>
    <ul z-sidebar-menu>
      <li z-sidebar-menu-item>
        <a z-sidebar-menu-button zSize="lg" href="#">
          <div
            class="bg-sidebar-primary text-sidebar-primary-foreground flex aspect-square size-8 items-center justify-center rounded-lg"
          >
            <ng-icon name="lucideGalleryVerticalEnd" class="size-4" />
          </div>
          <div class="flex flex-col gap-0.5 leading-none">
            <span class="font-medium">Documentation</span>
            <span>v1.0.0</span>
          </div>
        </a>
      </li>
    </ul>
  </div>

  <z-sidebar-content>
    <div z-sidebar-group>
      <ul z-sidebar-menu class="gap-2">
        @for (group of navMain; track group.title) {
          <li z-sidebar-menu-item>
            <a z-sidebar-menu-button [href]="group.url" class="font-medium">{{ group.title }}</a>

            @if (group.items.length) {
              <ul z-sidebar-menu-sub class="ml-0 border-l-0 px-1.5">
                @for (item of group.items; track item.title) {
                  <li z-sidebar-menu-sub-item>
                    <a z-sidebar-menu-sub-button [href]="item.url" [zActive]="!!item.isActive">{{ item.title }}</a>
                  </li>
                }
              </ul>
            }
          </li>
        }
      </ul>
    </div>
  </z-sidebar-content>
</z-sidebar>
`,
      language: 'html',
    },
    {
      name: 'sidebar-04-app-sidebar.component.ts',
      path: 'src/components/sidebar-04/sidebar-04-app-sidebar.component.ts',
      content: `import { ChangeDetectionStrategy, Component } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideGalleryVerticalEnd } from '@ng-icons/lucide';

import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

interface NavItem {
  readonly title: string;
  readonly url: string;
  readonly isActive?: boolean;
}

interface NavGroup {
  readonly title: string;
  readonly url: string;
  readonly items: readonly NavItem[];
}

@Component({
  selector: 'lib-sidebar-04-app-sidebar',
  standalone: true,
  imports: [...ZardSidebarImports, NgIcon],
  viewProviders: [provideIcons({ lucideGalleryVerticalEnd })],
  templateUrl: './sidebar-04-app-sidebar.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Sidebar04AppSidebarComponent {
  // This is sample data.
  protected readonly navMain: readonly NavGroup[] = [
    {
      title: 'Getting Started',
      url: '#',
      items: [
        { title: 'Installation', url: '#' },
        { title: 'Project Structure', url: '#' },
      ],
    },
    {
      title: 'Build Your Application',
      url: '#',
      items: [
        { title: 'Routing', url: '#' },
        { title: 'Data Fetching', url: '#', isActive: true },
        { title: 'Rendering', url: '#' },
        { title: 'Caching', url: '#' },
        { title: 'Styling', url: '#' },
        { title: 'Optimizing', url: '#' },
        { title: 'Configuring', url: '#' },
        { title: 'Testing', url: '#' },
        { title: 'Authentication', url: '#' },
        { title: 'Deploying', url: '#' },
        { title: 'Upgrading', url: '#' },
        { title: 'Examples', url: '#' },
      ],
    },
    {
      title: 'API Reference',
      url: '#',
      items: [
        { title: 'Components', url: '#' },
        { title: 'File Conventions', url: '#' },
        { title: 'Functions', url: '#' },
        { title: 'next.config.js Options', url: '#' },
        { title: 'CLI', url: '#' },
        { title: 'Edge Runtime', url: '#' },
      ],
    },
    {
      title: 'Architecture',
      url: '#',
      items: [
        { title: 'Accessibility', url: '#' },
        { title: 'Fast Refresh', url: '#' },
        { title: 'Next.js Compiler', url: '#' },
        { title: 'Supported Browsers', url: '#' },
        { title: 'Turbopack', url: '#' },
      ],
    },
    {
      title: 'Community',
      url: '#',
      items: [{ title: 'Contribution Guide', url: '#' }],
    },
  ];
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-04.component.html',
      path: 'src/components/sidebar-04/sidebar-04.component.html',
      content: `<z-sidebar-provider style="--sidebar-width: 19rem">
  <lib-sidebar-04-app-sidebar />

  <main z-sidebar-inset>
    <header class="flex h-16 shrink-0 items-center gap-2 px-4">
      <button z-sidebar-trigger class="-ml-1" aria-label="Toggle Sidebar"></button>

      <z-separator zOrientation="vertical" class="mr-2 data-[orientation=vertical]:h-4" />

      <z-breadcrumb>
        <z-breadcrumb-item class="hidden md:block">
          <a z-breadcrumb-link href="#">Build Your Application</a>
        </z-breadcrumb-item>
        <z-breadcrumb-separator class="hidden md:block" />
        <z-breadcrumb-item>
          <span z-breadcrumb-page>Data Fetching</span>
        </z-breadcrumb-item>
      </z-breadcrumb>
    </header>

    <div class="flex flex-1 flex-col gap-4 p-4 pt-0">
      <div class="grid auto-rows-min gap-4 md:grid-cols-3">
        <div class="bg-muted/50 aspect-video rounded-xl"></div>
        <div class="bg-muted/50 aspect-video rounded-xl"></div>
        <div class="bg-muted/50 aspect-video rounded-xl"></div>
      </div>
      <div class="bg-muted/50 min-h-[100vh] flex-1 rounded-xl md:min-h-min"></div>
    </div>
  </main>
</z-sidebar-provider>
`,
      language: 'html',
    },
    {
      name: 'sidebar-04.component.ts',
      path: 'src/components/sidebar-04/sidebar-04.component.ts',
      content: `import { ChangeDetectionStrategy, Component } from '@angular/core';

import { ZardBreadcrumbImports } from '@zard/components/breadcrumb/breadcrumb.imports';
import { ZardSeparatorComponent } from '@zard/components/separator/separator.component';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

import { Sidebar04AppSidebarComponent } from './sidebar-04-app-sidebar.component';

@Component({
  selector: 'lib-sidebar-04',
  standalone: true,
  imports: [...ZardSidebarImports, ...ZardBreadcrumbImports, ZardSeparatorComponent, Sidebar04AppSidebarComponent],
  templateUrl: './sidebar-04.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Sidebar04Component {}
`,
      language: 'typescript',
    },
  ],
};
