import type { Block } from '@doc/domain/components/block-container/block-container.component';

import { Dashboard01Component } from './dashboard-01.component';

export const dashboard01Block: Block = {
  id: 'dashboard-01',
  title: 'Dashboard 01',
  description: 'A dashboard with sidebar, charts and data table.',
  component: Dashboard01Component,
  category: 'Dashboard',
  image: {
    light: '/blocks/dashboard-01/light.png',
    dark: '/blocks/dashboard-01/dark.png',
  },
  // Generated by `npm run sync:blocks` from the sibling component files — do not edit by hand.
  files: [
    {
      name: 'dashboard-01-app-sidebar.component.html',
      path: 'src/components/dashboard-01/dashboard-01-app-sidebar.component.html',
      content: `<z-sidebar zCollapsible="offcanvas" zVariant="inset">
  <div z-sidebar-header>
    <ul z-sidebar-menu>
      <li z-sidebar-menu-item>
        <a z-sidebar-menu-button href="#" class="p-1.5!">
          <ng-icon name="lucideCircleDot" class="size-5!" />
          <span class="text-base font-semibold">Acme Inc.</span>
        </a>
      </li>
    </ul>
  </div>

  <z-sidebar-content>
    <lib-dashboard-01-nav-main [items]="navMain" />
    <lib-dashboard-01-nav-documents [items]="documents" />
    <lib-dashboard-01-nav-secondary [items]="navSecondary" class="mt-auto" />
  </z-sidebar-content>

  <div z-sidebar-footer>
    <lib-dashboard-01-nav-user [user]="user" />
  </div>
</z-sidebar>
`,
      language: 'html',
    },
    {
      name: 'dashboard-01-app-sidebar.component.ts',
      path: 'src/components/dashboard-01/dashboard-01-app-sidebar.component.ts',
      content: `import { ChangeDetectionStrategy, Component } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideCircleDot } from '@ng-icons/lucide';

import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

import { Dashboard01NavDocumentsComponent, type Dashboard01Document } from './dashboard-01-nav-documents.component';
import { Dashboard01NavMainComponent, type Dashboard01NavItem } from './dashboard-01-nav-main.component';
import { Dashboard01NavSecondaryComponent } from './dashboard-01-nav-secondary.component';
import { Dashboard01NavUserComponent, type Dashboard01User } from './dashboard-01-nav-user.component';

@Component({
  selector: 'lib-dashboard-01-app-sidebar',
  standalone: true,
  imports: [
    ...ZardSidebarImports,
    Dashboard01NavMainComponent,
    Dashboard01NavDocumentsComponent,
    Dashboard01NavSecondaryComponent,
    Dashboard01NavUserComponent,
    NgIcon,
  ],
  viewProviders: [provideIcons({ lucideCircleDot })],
  templateUrl: './dashboard-01-app-sidebar.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Dashboard01AppSidebarComponent {
  // This is sample data.
  protected readonly user: Dashboard01User = {
    name: 'zard ui',
    email: 'm@example.com',
    avatar: 'https://github.com/zard-ui.png',
  };

  protected readonly navMain: readonly Dashboard01NavItem[] = [
    { title: 'Dashboard', url: '#', icon: 'lucideLayoutDashboard' },
    { title: 'Lifecycle', url: '#', icon: 'lucideListTodo' },
    { title: 'Analytics', url: '#', icon: 'lucideChartBar' },
    { title: 'Projects', url: '#', icon: 'lucideFolder' },
    { title: 'Team', url: '#', icon: 'lucideUsers' },
  ];

  protected readonly navSecondary: readonly Dashboard01NavItem[] = [
    { title: 'Settings', url: '#', icon: 'lucideSettings' },
    { title: 'Get Help', url: '#', icon: 'lucideCircleHelp' },
    { title: 'Search', url: '#', icon: 'lucideSearch' },
  ];

  protected readonly documents: readonly Dashboard01Document[] = [
    { name: 'Data Library', url: '#', icon: 'lucideDatabase' },
    { name: 'Reports', url: '#', icon: 'lucideClipboardList' },
    { name: 'Word Assistant', url: '#', icon: 'lucideFileText' },
  ];
}
`,
      language: 'typescript',
    },
    {
      name: 'dashboard-01-chart-area-interactive.component.html',
      path: 'src/components/dashboard-01/dashboard-01-chart-area-interactive.component.html',
      content: `<z-card class="pt-0">
  <z-card-header class="flex items-center gap-2 space-y-0 border-b py-5 sm:flex-row">
    <div class="grid flex-1 gap-1">
      <z-card-title zTitle="Total Visitors" />
      <z-card-description zDescription="Total for the last 3 months" />
    </div>

    <z-card-action class="flex items-center gap-2">
      <z-toggle-group
        zMode="single"
        zType="outline"
        zSize="sm"
        [zItems]="ranges"
        [zValue]="range()"
        (valueChange)="onRangeChange($event)"
        class="hidden lg:flex"
        zItemClass="px-4!"
      />

      <z-select class="w-40 rounded-lg lg:hidden" [(zValue)]="range">
        @for (option of ranges; track option.value) {
          <z-select-item [zValue]="option.value">{{ option.label }}</z-select-item>
        }
      </z-select>
    </z-card-action>
  </z-card-header>

  <z-card-content class="px-2 pt-4 sm:px-6 sm:pt-6">
    <z-chart
      zType="area"
      [zConfig]="chartConfig"
      [zData]="visibleData()"
      [zSeries]="series"
      zXAxisKey="date"
      [zXAxisFormatter]="shortDate"
      zStacked
      zGradient
      class="aspect-auto h-[250px] w-full"
    >
      <z-chart-tooltip zIndicator="dot" [zLabelFormatter]="longDate" />
    </z-chart>
  </z-card-content>
</z-card>
`,
      language: 'html',
    },
    {
      name: 'dashboard-01-chart-area-interactive.component.ts',
      path: 'src/components/dashboard-01/dashboard-01-chart-area-interactive.component.ts',
      content: `import { ChangeDetectionStrategy, Component, computed, signal } from '@angular/core';

import { ZardCardImports } from '@zard/components/card/card.imports';
import { ZardChartImports } from '@zard/components/chart/chart.imports';
import type { ZardChartConfig, ZardChartSeries } from '@zard/components/chart/chart.types';
import { ZardSelectImports } from '@zard/components/select/select.imports';
import { ZardToggleGroupComponent } from '@zard/components/toggle-group/toggle-group.component';

@Component({
  selector: 'lib-dashboard-01-chart-area-interactive',
  standalone: true,
  imports: [...ZardCardImports, ...ZardChartImports, ...ZardSelectImports, ZardToggleGroupComponent],
  templateUrl: './dashboard-01-chart-area-interactive.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Dashboard01ChartAreaInteractiveComponent {
  protected readonly chartConfig: ZardChartConfig = {
    desktop: { label: 'Desktop', color: 'var(--chart-1)' },
    mobile: { label: 'Mobile', color: 'var(--chart-2)' },
  };

  protected readonly series: ZardChartSeries[] = [
    { dataKey: 'mobile', smooth: true },
    { dataKey: 'desktop', smooth: true },
  ];

  protected readonly ranges = [
    { value: '90d', label: 'Last 3 months' },
    { value: '30d', label: 'Last 30 days' },
    { value: '7d', label: 'Last 7 days' },
  ];

  protected readonly range = signal('90d');

  /** The trailing slice of the series, counted back from the newest row. */
  protected readonly visibleData = computed(() => {
    const days = this.range() === '7d' ? 7 : this.range() === '30d' ? 30 : 90;
    return this.chartData.slice(-days);
  });

  protected onRangeChange(value: string | string[]): void {
    if (typeof value === 'string' && value) {
      this.range.set(value);
    }
  }

  protected readonly shortDate = (value: string) =>
    new Date(\`\${value}T00:00:00\`).toLocaleDateString('en-US', { month: 'short', day: 'numeric' });

  protected readonly longDate = (value: string) =>
    new Date(\`\${value}T00:00:00\`).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });

  // This is sample data.
  protected readonly chartData = [
    { date: '2024-04-01', desktop: 222, mobile: 150 },
    { date: '2024-04-02', desktop: 97, mobile: 180 },
    { date: '2024-04-03', desktop: 167, mobile: 120 },
    { date: '2024-04-04', desktop: 242, mobile: 260 },
    { date: '2024-04-05', desktop: 373, mobile: 290 },
    { date: '2024-04-06', desktop: 301, mobile: 340 },
    { date: '2024-04-07', desktop: 245, mobile: 180 },
    { date: '2024-04-08', desktop: 409, mobile: 320 },
    { date: '2024-04-09', desktop: 59, mobile: 110 },
    { date: '2024-04-10', desktop: 261, mobile: 190 },
    { date: '2024-04-11', desktop: 327, mobile: 350 },
    { date: '2024-04-12', desktop: 292, mobile: 210 },
    { date: '2024-04-13', desktop: 342, mobile: 380 },
    { date: '2024-04-14', desktop: 137, mobile: 220 },
    { date: '2024-04-15', desktop: 120, mobile: 170 },
    { date: '2024-04-16', desktop: 138, mobile: 190 },
    { date: '2024-04-17', desktop: 446, mobile: 360 },
    { date: '2024-04-18', desktop: 364, mobile: 410 },
    { date: '2024-04-19', desktop: 243, mobile: 180 },
    { date: '2024-04-20', desktop: 89, mobile: 150 },
    { date: '2024-04-21', desktop: 137, mobile: 200 },
    { date: '2024-04-22', desktop: 224, mobile: 170 },
    { date: '2024-04-23', desktop: 138, mobile: 230 },
    { date: '2024-04-24', desktop: 387, mobile: 290 },
    { date: '2024-04-25', desktop: 215, mobile: 250 },
    { date: '2024-04-26', desktop: 75, mobile: 130 },
    { date: '2024-04-27', desktop: 383, mobile: 420 },
    { date: '2024-04-28', desktop: 122, mobile: 180 },
    { date: '2024-04-29', desktop: 315, mobile: 240 },
    { date: '2024-04-30', desktop: 454, mobile: 380 },
    { date: '2024-05-01', desktop: 165, mobile: 220 },
    { date: '2024-05-02', desktop: 293, mobile: 310 },
    { date: '2024-05-03', desktop: 247, mobile: 190 },
    { date: '2024-05-04', desktop: 385, mobile: 420 },
    { date: '2024-05-05', desktop: 481, mobile: 390 },
    { date: '2024-05-06', desktop: 498, mobile: 520 },
    { date: '2024-05-07', desktop: 388, mobile: 300 },
    { date: '2024-05-08', desktop: 149, mobile: 210 },
    { date: '2024-05-09', desktop: 227, mobile: 180 },
    { date: '2024-05-10', desktop: 293, mobile: 330 },
    { date: '2024-05-11', desktop: 335, mobile: 270 },
    { date: '2024-05-12', desktop: 197, mobile: 240 },
    { date: '2024-05-13', desktop: 197, mobile: 160 },
    { date: '2024-05-14', desktop: 448, mobile: 490 },
    { date: '2024-05-15', desktop: 473, mobile: 380 },
    { date: '2024-05-16', desktop: 338, mobile: 400 },
    { date: '2024-05-17', desktop: 499, mobile: 420 },
    { date: '2024-05-18', desktop: 315, mobile: 350 },
    { date: '2024-05-19', desktop: 235, mobile: 180 },
    { date: '2024-05-20', desktop: 177, mobile: 230 },
    { date: '2024-05-21', desktop: 82, mobile: 140 },
    { date: '2024-05-22', desktop: 81, mobile: 120 },
    { date: '2024-05-23', desktop: 252, mobile: 290 },
    { date: '2024-05-24', desktop: 294, mobile: 220 },
    { date: '2024-05-25', desktop: 201, mobile: 250 },
    { date: '2024-05-26', desktop: 213, mobile: 170 },
    { date: '2024-05-27', desktop: 420, mobile: 460 },
    { date: '2024-05-28', desktop: 233, mobile: 190 },
    { date: '2024-05-29', desktop: 78, mobile: 130 },
    { date: '2024-05-30', desktop: 340, mobile: 280 },
    { date: '2024-05-31', desktop: 178, mobile: 230 },
    { date: '2024-06-01', desktop: 178, mobile: 200 },
    { date: '2024-06-02', desktop: 470, mobile: 410 },
    { date: '2024-06-03', desktop: 103, mobile: 160 },
    { date: '2024-06-04', desktop: 439, mobile: 380 },
    { date: '2024-06-05', desktop: 88, mobile: 140 },
    { date: '2024-06-06', desktop: 294, mobile: 250 },
    { date: '2024-06-07', desktop: 323, mobile: 370 },
    { date: '2024-06-08', desktop: 385, mobile: 320 },
    { date: '2024-06-09', desktop: 438, mobile: 480 },
    { date: '2024-06-10', desktop: 155, mobile: 200 },
    { date: '2024-06-11', desktop: 92, mobile: 150 },
    { date: '2024-06-12', desktop: 492, mobile: 420 },
    { date: '2024-06-13', desktop: 81, mobile: 130 },
    { date: '2024-06-14', desktop: 426, mobile: 380 },
    { date: '2024-06-15', desktop: 307, mobile: 350 },
    { date: '2024-06-16', desktop: 371, mobile: 310 },
    { date: '2024-06-17', desktop: 475, mobile: 520 },
    { date: '2024-06-18', desktop: 107, mobile: 170 },
    { date: '2024-06-19', desktop: 341, mobile: 290 },
    { date: '2024-06-20', desktop: 408, mobile: 450 },
    { date: '2024-06-21', desktop: 169, mobile: 210 },
    { date: '2024-06-22', desktop: 317, mobile: 270 },
    { date: '2024-06-23', desktop: 480, mobile: 530 },
    { date: '2024-06-24', desktop: 132, mobile: 180 },
    { date: '2024-06-25', desktop: 141, mobile: 190 },
    { date: '2024-06-26', desktop: 434, mobile: 380 },
    { date: '2024-06-27', desktop: 448, mobile: 490 },
    { date: '2024-06-28', desktop: 149, mobile: 200 },
    { date: '2024-06-29', desktop: 103, mobile: 160 },
    { date: '2024-06-30', desktop: 446, mobile: 400 },
  ];
}
`,
      language: 'typescript',
    },
    {
      name: 'dashboard-01-data-table.component.html',
      path: 'src/components/dashboard-01/dashboard-01-data-table.component.html',
      content: `<div class="flex w-full flex-col justify-start gap-6">
  <div class="flex items-center justify-between px-4 lg:px-6">
    <nav [class]="navClasses" role="tablist" data-variant="default">
      @for (tab of tabs; track tab.value) {
        <button
          type="button"
          role="tab"
          [class]="buttonClasses"
          [attr.aria-selected]="activeTab() === tab.value"
          [attr.data-active]="activeTab() === tab.value ? '' : null"
          (click)="activeTab.set(tab.value)"
        >
          {{ tab.label }}
          @if (tab.badge) {
            <z-badge zType="secondary" class="ml-1">{{ tab.badge }}</z-badge>
          }
        </button>
      }
    </nav>

    <div class="flex items-center gap-2">
      <button z-button zType="outline" zSize="sm" z-dropdown [zDropdownMenu]="columnsMenu">
        <ng-icon name="lucideColumns3" />
        <span class="hidden lg:inline">Customize Columns</span>
        <span class="lg:hidden">Columns</span>
        <ng-icon name="lucideChevronDown" />
      </button>

      <z-dropdown-menu-content #columnsMenu="zDropdownMenuContent" class="w-56" zAlign="end">
        @for (column of columns; track column.key) {
          <z-dropdown-menu-checkbox-item
            [zChecked]="isVisible(column.key)"
            (zCheckedChange)="toggleColumn(column.key, $event)"
          >
            {{ column.label }}
          </z-dropdown-menu-checkbox-item>
        }
      </z-dropdown-menu-content>

      <button z-button zType="outline" zSize="sm">
        <ng-icon name="lucidePlus" />
        <span class="hidden lg:inline">Add Section</span>
      </button>
    </div>
  </div>

  <div class="relative flex flex-col gap-4 overflow-auto px-4 lg:px-6">
    <div class="overflow-hidden rounded-lg border">
      <table z-table>
        <thead z-table-header class="bg-muted sticky top-0 z-10">
          <tr z-table-row>
            <th z-table-head class="w-8"></th>
            <th z-table-head class="w-8">
              <z-checkbox
                [ngModel]="allPageRowsSelected()"
                (ngModelChange)="toggleAllOnPage($event)"
                aria-label="Select all"
              />
            </th>
            <th z-table-head>Header</th>
            @if (isVisible('type')) {
              <th z-table-head>Section Type</th>
            }
            @if (isVisible('status')) {
              <th z-table-head>Status</th>
            }
            @if (isVisible('target')) {
              <th z-table-head class="text-right">Target</th>
            }
            @if (isVisible('limit')) {
              <th z-table-head class="text-right">Limit</th>
            }
            @if (isVisible('reviewer')) {
              <th z-table-head>Reviewer</th>
            }
            <th z-table-head class="w-8"></th>
          </tr>
        </thead>

        <tbody
          z-table-body
          class="**:data-[slot=table-cell]:first:w-8"
          cdkDropList
          (cdkDropListDropped)="onRowDrop($event)"
        >
          @for (row of pageRows(); track row.id) {
            <tr z-table-row cdkDrag [attr.data-state]="isSelected(row) ? 'selected' : null" class="bg-background">
              <td z-table-cell>
                <button
                  cdkDragHandle
                  type="button"
                  class="text-muted-foreground hover:bg-accent flex size-7 cursor-grab items-center justify-center rounded-md active:cursor-grabbing"
                >
                  <ng-icon name="lucideGripVertical" class="size-3!" />
                  <span class="sr-only">Drag to reorder</span>
                </button>
              </td>

              <td z-table-cell>
                <z-checkbox
                  [ngModel]="isSelected(row)"
                  (ngModelChange)="toggleRow(row, $event)"
                  aria-label="Select row"
                />
              </td>

              <td z-table-cell>
                <button type="button" class="text-foreground w-fit px-0 text-left font-medium">
                  {{ row.header }}
                </button>
              </td>

              @if (isVisible('type')) {
                <td z-table-cell>
                  <z-badge zType="outline" class="text-muted-foreground px-1.5">{{ row.type }}</z-badge>
                </td>
              }

              @if (isVisible('status')) {
                <td z-table-cell>
                  <z-badge zType="outline" class="text-muted-foreground px-1.5">
                    @if (row.status === 'Done') {
                      <ng-icon name="lucideCircleCheck" class="text-green-500 dark:text-green-400" />
                    } @else {
                      <ng-icon name="lucideLoader" />
                    }
                    {{ row.status }}
                  </z-badge>
                </td>
              }

              @if (isVisible('target')) {
                <td z-table-cell class="text-right tabular-nums">{{ row.target }}</td>
              }

              @if (isVisible('limit')) {
                <td z-table-cell class="text-right tabular-nums">{{ row.limit }}</td>
              }

              @if (isVisible('reviewer')) {
                <td z-table-cell>
                  @if (row.reviewer) {
                    {{ row.reviewer }}
                  } @else {
                    <z-select class="h-8 w-38" zPlaceholder="Assign reviewer">
                      <z-select-item zValue="Eddie Lake">Eddie Lake</z-select-item>
                      <z-select-item zValue="Jamik Tashpulatov">Jamik Tashpulatov</z-select-item>
                      <z-select-item zValue="Emily Whalen">Emily Whalen</z-select-item>
                    </z-select>
                  }
                </td>
              }

              <td z-table-cell>
                <button
                  z-button
                  zType="ghost"
                  zSize="icon"
                  z-dropdown
                  [zDropdownMenu]="rowMenu"
                  class="text-muted-foreground data-[state=open]:bg-muted size-8"
                >
                  <ng-icon name="lucideEllipsisVertical" />
                  <span class="sr-only">Open menu</span>
                </button>

                <z-dropdown-menu-content #rowMenu="zDropdownMenuContent" class="w-32" zAlign="end">
                  <z-dropdown-menu-item>Edit</z-dropdown-menu-item>
                  <z-dropdown-menu-item>Make a copy</z-dropdown-menu-item>
                  <z-dropdown-menu-item>Favorite</z-dropdown-menu-item>
                  <z-dropdown-menu-separator />
                  <z-dropdown-menu-item zType="destructive">Delete</z-dropdown-menu-item>
                </z-dropdown-menu-content>
              </td>
            </tr>
          }
        </tbody>
      </table>
    </div>

    <div class="flex items-center justify-between px-4">
      <div class="text-muted-foreground hidden flex-1 text-sm lg:flex">
        {{ selected().size }} of {{ rows().length }} row(s) selected.
      </div>

      <div class="flex w-full items-center gap-8 lg:w-fit">
        <div class="hidden items-center gap-2 lg:flex">
          <span class="text-sm font-medium">Rows per page</span>
          <z-select class="h-8 w-20" [zValue]="pageSize()" (zSelectionChange)="onPageSizeChange($event)">
            @for (size of pageSizes; track size) {
              <z-select-item [zValue]="size">{{ size }}</z-select-item>
            }
          </z-select>
        </div>

        <div class="flex w-fit items-center justify-center text-sm font-medium">
          Page {{ pageIndex() + 1 }} of {{ pageCount() }}
        </div>

        <div class="ml-auto flex items-center gap-2 lg:ml-0">
          <button
            z-button
            zType="outline"
            zSize="icon"
            class="hidden size-8 lg:flex"
            [zDisabled]="pageIndex() === 0"
            (click)="goToPage(0)"
          >
            <span class="sr-only">Go to first page</span>
            <ng-icon name="lucideChevronsLeft" />
          </button>
          <button
            z-button
            zType="outline"
            zSize="icon"
            class="size-8"
            [zDisabled]="pageIndex() === 0"
            (click)="goToPage(pageIndex() - 1)"
          >
            <span class="sr-only">Go to previous page</span>
            <ng-icon name="lucideChevronLeft" />
          </button>
          <button
            z-button
            zType="outline"
            zSize="icon"
            class="size-8"
            [zDisabled]="pageIndex() >= pageCount() - 1"
            (click)="goToPage(pageIndex() + 1)"
          >
            <span class="sr-only">Go to next page</span>
            <ng-icon name="lucideChevronRight" />
          </button>
          <button
            z-button
            zType="outline"
            zSize="icon"
            class="hidden size-8 lg:flex"
            [zDisabled]="pageIndex() >= pageCount() - 1"
            (click)="goToPage(pageCount() - 1)"
          >
            <span class="sr-only">Go to last page</span>
            <ng-icon name="lucideChevronsRight" />
          </button>
        </div>
      </div>
    </div>
  </div>
</div>
`,
      language: 'html',
    },
    {
      name: 'dashboard-01-data-table.component.ts',
      path: 'src/components/dashboard-01/dashboard-01-data-table.component.ts',
      content: `import { CdkDrag, CdkDragDrop, CdkDragHandle, CdkDropList, moveItemInArray } from '@angular/cdk/drag-drop';
import { ChangeDetectionStrategy, Component, computed, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';

import { NgIcon, provideIcons } from '@ng-icons/core';
import {
  lucideChevronDown,
  lucideChevronLeft,
  lucideChevronRight,
  lucideChevronsLeft,
  lucideChevronsRight,
  lucideCircleCheck,
  lucideColumns3,
  lucideEllipsisVertical,
  lucideGripVertical,
  lucideLoader,
  lucidePlus,
} from '@ng-icons/lucide';

import { ZardBadgeComponent } from '@zard/components/badge/badge.component';
import { ZardButtonComponent } from '@zard/components/button/button.component';
import { ZardCheckboxComponent } from '@zard/components/checkbox/checkbox.component';
import { ZardDropdownImports } from '@zard/components/dropdown/dropdown.imports';
import { ZardSelectImports } from '@zard/components/select/select.imports';
import { ZardTableImports } from '@zard/components/table/table.imports';
import { tabButtonVariants, tabNavVariants } from '@zard/components/tabs/tabs.variants';

export interface Dashboard01Row {
  readonly id: number;
  readonly header: string;
  readonly type: string;
  readonly status: 'Done' | 'In Process';
  readonly target: string;
  readonly limit: string;
  readonly reviewer: string;
}

type ColumnKey = 'type' | 'status' | 'target' | 'limit' | 'reviewer';

const SECTION_TYPES = ['Narrative', 'Technical content', 'Legal', 'Financial', 'Capabilities'];
const REVIEWERS = ['Eddie Lake', 'Jamik Tashpulatov', 'Emily Whalen', ''];

/** Titles of the first rows, matching the shadcn sample document. */
const HEADERS = [
  'Cover page',
  'Table of contents',
  'Executive summary',
  'Technical approach',
  'Design',
  'Capabilities',
  'Integration with existing systems',
  'Innovation and Advantages',
  "Overview of EMR's Innovative Solutions",
  'Advanced Algorithms and Machine Learning',
  'Adaptive Communication Protocols',
  'Advantages Over Current Technologies',
  'Past Performance',
  'Customer Feedback and Satisfaction Levels',
  'Implementation Challenges and Solutions',
  'Return on Investment (ROI) Analysis',
  'Competitive Analysis',
  'Risk Assessment and Mitigation Strategies',
  'Compliance and Regulatory Requirements',
  'Scalability and Future Growth Projections',
  'Cost-Benefit Analysis',
  'User Training and Onboarding Plan',
  'Data Security and Privacy Measures',
  'Integration Timeline and Milestones',
  'Maintenance and Support Framework',
  'Performance Metrics and KPIs',
  'Stakeholder Communication Plan',
  'Change Management Strategy',
  'Quality Assurance Procedures',
  'Disaster Recovery Planning',
  'Vendor Management Approach',
  'Resource Allocation Model',
  'Technical Documentation Standards',
  'Testing and Validation Protocols',
];

@Component({
  selector: 'lib-dashboard-01-data-table',
  standalone: true,
  imports: [
    ...ZardTableImports,
    ...ZardDropdownImports,
    ...ZardSelectImports,
    ZardBadgeComponent,
    ZardButtonComponent,
    ZardCheckboxComponent,
    CdkDropList,
    CdkDrag,
    CdkDragHandle,
    FormsModule,
    NgIcon,
  ],
  viewProviders: [
    provideIcons({
      lucideChevronDown,
      lucideChevronLeft,
      lucideChevronRight,
      lucideChevronsLeft,
      lucideChevronsRight,
      lucideCircleCheck,
      lucideColumns3,
      lucideEllipsisVertical,
      lucideGripVertical,
      lucideLoader,
      lucidePlus,
    }),
  ],
  templateUrl: './dashboard-01-data-table.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Dashboard01DataTableComponent {
  protected readonly navClasses = tabNavVariants({ zVariant: 'default' });
  protected readonly buttonClasses = tabButtonVariants();

  protected readonly tabs = [
    { value: 'outline', label: 'Outline', badge: '' },
    { value: 'past-performance', label: 'Past Performance', badge: '3' },
    { value: 'key-personnel', label: 'Key Personnel', badge: '2' },
    { value: 'focus-documents', label: 'Focus Documents', badge: '' },
  ];

  protected readonly activeTab = signal('outline');

  protected readonly columns: { key: ColumnKey; label: string }[] = [
    { key: 'type', label: 'Type' },
    { key: 'status', label: 'Status' },
    { key: 'target', label: 'Target' },
    { key: 'limit', label: 'Limit' },
    { key: 'reviewer', label: 'Reviewer' },
  ];

  protected readonly hiddenColumns = signal<ReadonlySet<ColumnKey>>(new Set());

  // This is sample data.
  protected readonly rows = signal<Dashboard01Row[]>(
    Array.from({ length: 68 }, (_, index) => ({
      id: index + 1,
      header: HEADERS[index % HEADERS.length],
      type:
        index === 0 ? 'Cover page' : index === 1 ? 'Table of contents' : SECTION_TYPES[index % SECTION_TYPES.length],
      status: index % 3 === 0 ? ('In Process' as const) : ('Done' as const),
      target: \`\${((index * 7) % 30) + 1}\`,
      limit: \`\${((index * 11) % 30) + 1}\`,
      reviewer: REVIEWERS[index % REVIEWERS.length],
    })),
  );

  protected readonly selected = signal<ReadonlySet<number>>(new Set());

  protected readonly pageSizes = ['10', '20', '30', '40', '50'];
  protected readonly pageSize = signal('10');
  protected readonly pageIndex = signal(0);

  protected readonly pageCount = computed(() => Math.ceil(this.rows().length / Number(this.pageSize())));

  protected readonly pageRows = computed(() => {
    const size = Number(this.pageSize());
    const start = this.pageIndex() * size;
    return this.rows().slice(start, start + size);
  });

  protected readonly allPageRowsSelected = computed(() => {
    const page = this.pageRows();
    const selected = this.selected();
    return page.length > 0 && page.every(row => selected.has(row.id));
  });

  protected isVisible(column: ColumnKey): boolean {
    return !this.hiddenColumns().has(column);
  }

  protected toggleColumn(column: ColumnKey, visible: boolean): void {
    this.hiddenColumns.update(columns => {
      const next = new Set(columns);
      if (visible) {
        next.delete(column);
      } else {
        next.add(column);
      }
      return next;
    });
  }

  protected isSelected(row: Dashboard01Row): boolean {
    return this.selected().has(row.id);
  }

  protected toggleRow(row: Dashboard01Row, checked: boolean): void {
    this.selected.update(selected => {
      const next = new Set(selected);
      if (checked) {
        next.add(row.id);
      } else {
        next.delete(row.id);
      }
      return next;
    });
  }

  protected toggleAllOnPage(checked: boolean): void {
    this.selected.update(selected => {
      const next = new Set(selected);
      for (const row of this.pageRows()) {
        if (checked) {
          next.add(row.id);
        } else {
          next.delete(row.id);
        }
      }
      return next;
    });
  }

  protected onPageSizeChange(size: string | string[]): void {
    if (typeof size !== 'string' || !size) {
      return;
    }

    this.pageSize.set(size);
    this.pageIndex.set(0);
  }

  protected goToPage(index: number): void {
    this.pageIndex.set(Math.min(Math.max(index, 0), this.pageCount() - 1));
  }

  /** Reordering is scoped to the current page, which is the slice the user can actually see. */
  protected onRowDrop(event: CdkDragDrop<Dashboard01Row[]>): void {
    const offset = this.pageIndex() * Number(this.pageSize());
    this.rows.update(rows => {
      const next = [...rows];
      moveItemInArray(next, offset + event.previousIndex, offset + event.currentIndex);
      return next;
    });
  }
}
`,
      language: 'typescript',
    },
    {
      name: 'dashboard-01-nav-documents.component.html',
      path: 'src/components/dashboard-01/dashboard-01-nav-documents.component.html',
      content: `<div z-sidebar-group class="group-data-[collapsible=icon]:hidden">
  <div z-sidebar-group-label>Documents</div>

  <ul z-sidebar-menu>
    @for (item of items(); track item.name) {
      <li z-sidebar-menu-item>
        <a z-sidebar-menu-button [href]="item.url">
          <ng-icon [name]="item.icon" />
          <span>{{ item.name }}</span>
        </a>

        <button
          z-sidebar-menu-action
          zShowOnHover
          z-dropdown
          [zDropdownMenu]="documentMenu"
          class="data-[state=open]:bg-accent rounded-sm"
        >
          <ng-icon name="lucideEllipsis" />
          <span class="sr-only">More</span>
        </button>

        <z-dropdown-menu-content
          #documentMenu="zDropdownMenuContent"
          class="w-24 rounded-lg"
          [zSide]="menuSide()"
          [zAlign]="menuAlign()"
        >
          <z-dropdown-menu-item>
            <ng-icon name="lucideFolder" />
            <span>Open</span>
          </z-dropdown-menu-item>
          <z-dropdown-menu-item>
            <ng-icon name="lucideShare2" />
            <span>Share</span>
          </z-dropdown-menu-item>
          <z-dropdown-menu-separator />
          <z-dropdown-menu-item zType="destructive">
            <ng-icon name="lucideTrash2" />
            <span>Delete</span>
          </z-dropdown-menu-item>
        </z-dropdown-menu-content>
      </li>
    }

    <li z-sidebar-menu-item>
      <button z-sidebar-menu-button class="text-sidebar-foreground/70">
        <ng-icon name="lucideEllipsis" class="text-sidebar-foreground/70" />
        <span>More</span>
      </button>
    </li>
  </ul>
</div>
`,
      language: 'html',
    },
    {
      name: 'dashboard-01-nav-documents.component.ts',
      path: 'src/components/dashboard-01/dashboard-01-nav-documents.component.ts',
      content: `import { ChangeDetectionStrategy, Component, computed, inject, input } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import {
  lucideDatabase,
  lucideEllipsis,
  lucideFileText,
  lucideFolder,
  lucideShare2,
  lucideClipboardList,
  lucideTrash2,
} from '@ng-icons/lucide';

import type { ZardDropdownAlign, ZardDropdownSide } from '@zard/components/dropdown/dropdown-positions';
import { ZardDropdownImports } from '@zard/components/dropdown/dropdown.imports';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';
import { ZardSidebarService } from '@zard/components/sidebar/sidebar.service';

export interface Dashboard01Document {
  readonly name: string;
  readonly url: string;
  readonly icon: string;
}

@Component({
  selector: 'lib-dashboard-01-nav-documents',
  standalone: true,
  imports: [...ZardSidebarImports, ...ZardDropdownImports, NgIcon],
  viewProviders: [
    provideIcons({
      lucideClipboardList,
      lucideDatabase,
      lucideEllipsis,
      lucideFileText,
      lucideFolder,
      lucideShare2,
      lucideTrash2,
    }),
  ],
  templateUrl: './dashboard-01-nav-documents.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Dashboard01NavDocumentsComponent {
  private readonly sidebar = inject(ZardSidebarService);
  /** shadcn opens these menus to the side of the sidebar on desktop and below the trigger on mobile. */
  protected readonly menuSide = computed<ZardDropdownSide>(() => (this.sidebar.isMobile() ? 'bottom' : 'right'));
  protected readonly menuAlign = computed<ZardDropdownAlign>(() => (this.sidebar.isMobile() ? 'end' : 'start'));

  readonly items = input<readonly Dashboard01Document[]>([]);
}
`,
      language: 'typescript',
    },
    {
      name: 'dashboard-01-nav-main.component.html',
      path: 'src/components/dashboard-01/dashboard-01-nav-main.component.html',
      content: `<div z-sidebar-group>
  <div z-sidebar-group-content class="flex flex-col gap-2">
    <ul z-sidebar-menu>
      <li z-sidebar-menu-item class="flex items-center gap-2">
        <button
          z-sidebar-menu-button
          zTooltip="Quick Create"
          class="bg-primary text-primary-foreground hover:bg-primary/90 hover:text-primary-foreground active:bg-primary/90 active:text-primary-foreground min-w-8 duration-200 ease-linear"
        >
          <ng-icon name="lucideCirclePlus" />
          <span>Quick Create</span>
        </button>

        <button z-button zType="outline" zSize="icon" class="size-8 group-data-[collapsible=icon]:opacity-0">
          <ng-icon name="lucideMail" />
          <span class="sr-only">Inbox</span>
        </button>
      </li>
    </ul>

    <ul z-sidebar-menu>
      @for (item of items(); track item.title) {
        <li z-sidebar-menu-item>
          <button z-sidebar-menu-button [zTooltip]="item.title">
            <ng-icon [name]="item.icon" />
            <span>{{ item.title }}</span>
          </button>
        </li>
      }
    </ul>
  </div>
</div>
`,
      language: 'html',
    },
    {
      name: 'dashboard-01-nav-main.component.ts',
      path: 'src/components/dashboard-01/dashboard-01-nav-main.component.ts',
      content: `import { ChangeDetectionStrategy, Component, input } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import {
  lucideChartBar,
  lucideCirclePlus,
  lucideFolder,
  lucideLayoutDashboard,
  lucideListTodo,
  lucideMail,
  lucideUsers,
} from '@ng-icons/lucide';

import { ZardButtonComponent } from '@zard/components/button/button.component';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

export interface Dashboard01NavItem {
  readonly title: string;
  readonly url: string;
  readonly icon: string;
}

@Component({
  selector: 'lib-dashboard-01-nav-main',
  standalone: true,
  imports: [...ZardSidebarImports, ZardButtonComponent, NgIcon],
  viewProviders: [
    provideIcons({
      lucideChartBar,
      lucideCirclePlus,
      lucideFolder,
      lucideLayoutDashboard,
      lucideListTodo,
      lucideMail,
      lucideUsers,
    }),
  ],
  templateUrl: './dashboard-01-nav-main.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Dashboard01NavMainComponent {
  readonly items = input<readonly Dashboard01NavItem[]>([]);
}
`,
      language: 'typescript',
    },
    {
      name: 'dashboard-01-nav-secondary.component.html',
      path: 'src/components/dashboard-01/dashboard-01-nav-secondary.component.html',
      content: `<div z-sidebar-group [class]="class()">
  <div z-sidebar-group-content>
    <ul z-sidebar-menu>
      @for (item of items(); track item.title) {
        <li z-sidebar-menu-item>
          <a z-sidebar-menu-button [href]="item.url">
            <ng-icon [name]="item.icon" />
            <span>{{ item.title }}</span>
          </a>
        </li>
      }
    </ul>
  </div>
</div>
`,
      language: 'html',
    },
    {
      name: 'dashboard-01-nav-secondary.component.ts',
      path: 'src/components/dashboard-01/dashboard-01-nav-secondary.component.ts',
      content: `import { ChangeDetectionStrategy, Component, input } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideCircleHelp, lucideSearch, lucideSettings } from '@ng-icons/lucide';

import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

import type { Dashboard01NavItem } from './dashboard-01-nav-main.component';

@Component({
  selector: 'lib-dashboard-01-nav-secondary',
  standalone: true,
  imports: [...ZardSidebarImports, NgIcon],
  viewProviders: [provideIcons({ lucideCircleHelp, lucideSearch, lucideSettings })],
  templateUrl: './dashboard-01-nav-secondary.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Dashboard01NavSecondaryComponent {
  readonly items = input<readonly Dashboard01NavItem[]>([]);
  readonly class = input<string>('');
}
`,
      language: 'typescript',
    },
    {
      name: 'dashboard-01-nav-user.component.html',
      path: 'src/components/dashboard-01/dashboard-01-nav-user.component.html',
      content: `<ul z-sidebar-menu>
  <li z-sidebar-menu-item>
    <button
      z-sidebar-menu-button
      zSize="lg"
      z-dropdown
      [zDropdownMenu]="userMenu"
      class="data-[state=open]:bg-sidebar-accent data-[state=open]:text-sidebar-accent-foreground"
    >
      <z-avatar class="size-8 rounded-lg grayscale" [zSrc]="user().avatar" [zAlt]="user().name" zFallback="ZU" />

      <div class="grid flex-1 text-left text-sm leading-tight">
        <span class="truncate font-medium">{{ user().name }}</span>
        <span class="text-muted-foreground truncate text-xs">{{ user().email }}</span>
      </div>

      <ng-icon name="lucideEllipsisVertical" class="ml-auto size-4" />
    </button>

    <z-dropdown-menu-content
      #userMenu="zDropdownMenuContent"
      class="w-(--z-dropdown-menu-trigger-width) min-w-56 rounded-lg"
      [zSide]="menuSide()"
      zAlign="end"
    >
      <z-dropdown-menu-label class="p-0 font-normal">
        <div class="flex items-center gap-2 px-1 py-1.5 text-left text-sm">
          <z-avatar class="size-8 rounded-lg" [zSrc]="user().avatar" [zAlt]="user().name" zFallback="ZU" />

          <div class="grid flex-1 text-left text-sm leading-tight">
            <span class="truncate font-medium">{{ user().name }}</span>
            <span class="text-muted-foreground truncate text-xs">{{ user().email }}</span>
          </div>
        </div>
      </z-dropdown-menu-label>

      <z-dropdown-menu-separator />

      <z-dropdown-menu-group>
        <z-dropdown-menu-item>
          <ng-icon name="lucideUserCircle" />
          Account
        </z-dropdown-menu-item>
        <z-dropdown-menu-item>
          <ng-icon name="lucideCreditCard" />
          Billing
        </z-dropdown-menu-item>
        <z-dropdown-menu-item>
          <ng-icon name="lucideBell" />
          Notifications
        </z-dropdown-menu-item>
      </z-dropdown-menu-group>

      <z-dropdown-menu-separator />

      <z-dropdown-menu-item>
        <ng-icon name="lucideLogOut" />
        Log out
      </z-dropdown-menu-item>
    </z-dropdown-menu-content>
  </li>
</ul>
`,
      language: 'html',
    },
    {
      name: 'dashboard-01-nav-user.component.ts',
      path: 'src/components/dashboard-01/dashboard-01-nav-user.component.ts',
      content: `import { ChangeDetectionStrategy, Component, computed, inject, input } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideBell, lucideCreditCard, lucideEllipsisVertical, lucideLogOut, lucideUserCircle } from '@ng-icons/lucide';

import { ZardAvatarComponent } from '@zard/components/avatar/avatar.component';
import type { ZardDropdownSide } from '@zard/components/dropdown/dropdown-positions';
import { ZardDropdownImports } from '@zard/components/dropdown/dropdown.imports';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';
import { ZardSidebarService } from '@zard/components/sidebar/sidebar.service';

export interface Dashboard01User {
  readonly name: string;
  readonly email: string;
  readonly avatar: string;
}

@Component({
  selector: 'lib-dashboard-01-nav-user',
  standalone: true,
  imports: [...ZardSidebarImports, ...ZardDropdownImports, ZardAvatarComponent, NgIcon],
  viewProviders: [
    provideIcons({
      lucideBell,
      lucideCreditCard,
      lucideEllipsisVertical,
      lucideLogOut,
      lucideUserCircle,
    }),
  ],
  templateUrl: './dashboard-01-nav-user.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Dashboard01NavUserComponent {
  private readonly sidebar = inject(ZardSidebarService);
  /** shadcn opens these menus to the side of the sidebar on desktop and below the trigger on mobile. */
  protected readonly menuSide = computed<ZardDropdownSide>(() => (this.sidebar.isMobile() ? 'bottom' : 'right'));

  readonly user = input.required<Dashboard01User>();
}
`,
      language: 'typescript',
    },
    {
      name: 'dashboard-01-section-cards.component.html',
      path: 'src/components/dashboard-01/dashboard-01-section-cards.component.html',
      content: `<div
  class="*:data-[slot=card]:from-primary/5 *:data-[slot=card]:to-card dark:*:data-[slot=card]:bg-card grid grid-cols-1 gap-4 px-4 *:data-[slot=card]:bg-gradient-to-t *:data-[slot=card]:shadow-xs sm:grid-cols-2 lg:px-6 xl:grid-cols-4"
>
  @for (card of cards; track card.description) {
    <z-card>
      <z-card-header>
        <z-card-description [zDescription]="card.description" />
        <!-- \`z-card-title\` renders its \`zTitle\` input, not projected content. -->
        <z-card-title [zTitle]="card.value" class="text-2xl font-semibold tabular-nums lg:text-3xl" />

        <z-card-action>
          <z-badge zType="outline">
            <ng-icon [name]="trendIcon(card.trend)" />
            {{ card.badge }}
          </z-badge>
        </z-card-action>
      </z-card-header>

      <z-card-footer class="flex-col items-start gap-1.5 bg-transparent text-sm">
        <div class="line-clamp-1 flex gap-2 font-medium">
          {{ card.headline }}
          <ng-icon [name]="trendIcon(card.trend)" class="size-4" />
        </div>
        <div class="text-muted-foreground">{{ card.caption }}</div>
      </z-card-footer>
    </z-card>
  }
</div>
`,
      language: 'html',
    },
    {
      name: 'dashboard-01-section-cards.component.ts',
      path: 'src/components/dashboard-01/dashboard-01-section-cards.component.ts',
      content: `import { ChangeDetectionStrategy, Component } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideTrendingDown, lucideTrendingUp } from '@ng-icons/lucide';

import { ZardBadgeComponent } from '@zard/components/badge/badge.component';
import { ZardCardImports } from '@zard/components/card/card.imports';

interface SectionCard {
  readonly description: string;
  readonly value: string;
  readonly badge: string;
  readonly trend: 'up' | 'down';
  readonly headline: string;
  readonly caption: string;
}

@Component({
  selector: 'lib-dashboard-01-section-cards',
  standalone: true,
  imports: [...ZardCardImports, ZardBadgeComponent, NgIcon],
  viewProviders: [provideIcons({ lucideTrendingDown, lucideTrendingUp })],
  templateUrl: './dashboard-01-section-cards.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Dashboard01SectionCardsComponent {
  // This is sample data.
  protected readonly cards: readonly SectionCard[] = [
    {
      description: 'Total Revenue',
      value: '$1,250.00',
      badge: '+12.5%',
      trend: 'up',
      headline: 'Trending up this month',
      caption: 'Visitors for the last 6 months',
    },
    {
      description: 'New Customers',
      value: '1,234',
      badge: '-20%',
      trend: 'down',
      headline: 'Down 20% this period',
      caption: 'Acquisition needs attention',
    },
    {
      description: 'Active Accounts',
      value: '45,678',
      badge: '+12.5%',
      trend: 'up',
      headline: 'Strong user retention',
      caption: 'Engagement exceed targets',
    },
    {
      description: 'Growth Rate',
      value: '4.5%',
      badge: '+4.5%',
      trend: 'up',
      headline: 'Steady performance increase',
      caption: 'Meets growth projections',
    },
  ];

  protected trendIcon(trend: 'up' | 'down'): string {
    return trend === 'up' ? 'lucideTrendingUp' : 'lucideTrendingDown';
  }
}
`,
      language: 'typescript',
    },
    {
      name: 'dashboard-01-site-header.component.html',
      path: 'src/components/dashboard-01/dashboard-01-site-header.component.html',
      content: `<header
  class="flex h-(--header-height) shrink-0 items-center gap-2 border-b transition-[width,height] ease-linear group-has-data-[collapsible=icon]/sidebar-wrapper:h-(--header-height)"
>
  <div class="flex w-full items-center gap-1 px-4 lg:gap-2 lg:px-6">
    <button z-sidebar-trigger class="-ml-1" aria-label="Toggle Sidebar"></button>

    <z-separator
      zOrientation="vertical"
      class="mx-2 data-[orientation=vertical]:h-4 data-[orientation=vertical]:self-center"
    />

    <h1 class="text-base font-medium">Documents</h1>

    <div class="ml-auto flex items-center gap-2">
      <a
        z-button
        zType="ghost"
        zSize="sm"
        href="https://github.com/zard-ui/zardui"
        rel="noopener noreferrer"
        target="_blank"
        class="dark:text-foreground hidden sm:flex"
      >
        GitHub
      </a>
    </div>
  </div>
</header>
`,
      language: 'html',
    },
    {
      name: 'dashboard-01-site-header.component.ts',
      path: 'src/components/dashboard-01/dashboard-01-site-header.component.ts',
      content: `import { ChangeDetectionStrategy, Component } from '@angular/core';

import { ZardButtonComponent } from '@zard/components/button/button.component';
import { ZardSeparatorComponent } from '@zard/components/separator/separator.component';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

@Component({
  selector: 'lib-dashboard-01-site-header',
  standalone: true,
  imports: [...ZardSidebarImports, ZardSeparatorComponent, ZardButtonComponent],
  templateUrl: './dashboard-01-site-header.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Dashboard01SiteHeaderComponent {}
`,
      language: 'typescript',
    },
    {
      name: 'dashboard-01.component.html',
      path: 'src/components/dashboard-01/dashboard-01.component.html',
      content: `<z-sidebar-provider class="[--header-height:calc(--spacing(12))] [--sidebar-width:calc(--spacing(72))]">
  <lib-dashboard-01-app-sidebar />

  <main z-sidebar-inset>
    <lib-dashboard-01-site-header />

    <div class="flex flex-1 flex-col">
      <div class="flex flex-1 flex-col gap-2">
        <div class="flex flex-col gap-4 py-4 md:gap-6 md:py-6">
          <lib-dashboard-01-section-cards />

          <div class="px-4 lg:px-6">
            <lib-dashboard-01-chart-area-interactive />
          </div>

          <lib-dashboard-01-data-table />
        </div>
      </div>
    </div>
  </main>
</z-sidebar-provider>
`,
      language: 'html',
    },
    {
      name: 'dashboard-01.component.ts',
      path: 'src/components/dashboard-01/dashboard-01.component.ts',
      content: `import { ChangeDetectionStrategy, Component } from '@angular/core';

import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

import { Dashboard01AppSidebarComponent } from './dashboard-01-app-sidebar.component';
import { Dashboard01ChartAreaInteractiveComponent } from './dashboard-01-chart-area-interactive.component';
import { Dashboard01DataTableComponent } from './dashboard-01-data-table.component';
import { Dashboard01SectionCardsComponent } from './dashboard-01-section-cards.component';
import { Dashboard01SiteHeaderComponent } from './dashboard-01-site-header.component';

@Component({
  selector: 'lib-dashboard-01',
  standalone: true,
  imports: [
    ...ZardSidebarImports,
    Dashboard01AppSidebarComponent,
    Dashboard01ChartAreaInteractiveComponent,
    Dashboard01DataTableComponent,
    Dashboard01SectionCardsComponent,
    Dashboard01SiteHeaderComponent,
  ],
  templateUrl: './dashboard-01.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Dashboard01Component {}
`,
      language: 'typescript',
    },
  ],
};
