import type { Block } from '@doc/domain/components/block-container/block-container.component';

import { Sidebar08Component } from './sidebar-08.component';

export const sidebar08Block: Block = {
  id: 'sidebar-08',
  title: 'Sidebar 08',
  description: 'An inset sidebar with secondary navigation.',
  component: Sidebar08Component,
  category: 'Sidebar',
  image: {
    light: '/blocks/sidebar-08/light.png',
    dark: '/blocks/sidebar-08/dark.png',
  },
  // Generated by `npm run sync:blocks` from the sibling component files — do not edit by hand.
  files: [
    {
      name: 'sidebar-08-nav-main.component.html',
      path: 'src/components/sidebar-08/sidebar-08-nav-main.component.html',
      content: `<div z-sidebar-group>
  <div z-sidebar-group-label>Platform</div>

  <ul z-sidebar-menu>
    @for (item of items(); track item.title) {
      <li z-sidebar-menu-item z-collapsible class="group/collapsible" [zOpen]="!!item.isActive">
        <button z-collapsible-trigger z-sidebar-menu-button [zTooltip]="item.title">
          <ng-icon [name]="item.icon" />
          <span>{{ item.title }}</span>
          <ng-icon
            name="lucideChevronRight"
            class="ml-auto transition-transform duration-200 group-data-[state=open]/collapsible:rotate-90"
          />
        </button>

        <z-collapsible-content>
          <ul z-sidebar-menu-sub>
            @for (subItem of item.items; track subItem.title) {
              <li z-sidebar-menu-sub-item>
                <a z-sidebar-menu-sub-button [href]="subItem.url">
                  <span>{{ subItem.title }}</span>
                </a>
              </li>
            }
          </ul>
        </z-collapsible-content>
      </li>
    }
  </ul>
</div>
`,
      language: 'html',
    },
    {
      name: 'sidebar-08-nav-main.component.ts',
      path: 'src/components/sidebar-08/sidebar-08-nav-main.component.ts',
      content: `import { ChangeDetectionStrategy, Component, input } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideBookOpen, lucideBot, lucideChevronRight, lucideSettings2, lucideSquareTerminal } from '@ng-icons/lucide';

import { ZardCollapsibleImports } from '@zard/components/collapsible/collapsible.imports';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

export interface Sidebar08NavSubItem {
  readonly title: string;
  readonly url: string;
}

export interface Sidebar08NavItem {
  readonly title: string;
  readonly url: string;
  readonly icon: string;
  readonly isActive?: boolean;
  readonly items: readonly Sidebar08NavSubItem[];
}

@Component({
  selector: 'lib-sidebar-08-nav-main',
  standalone: true,
  imports: [...ZardSidebarImports, ...ZardCollapsibleImports, NgIcon],
  viewProviders: [
    provideIcons({ lucideBookOpen, lucideBot, lucideChevronRight, lucideSettings2, lucideSquareTerminal }),
  ],
  templateUrl: './sidebar-08-nav-main.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Sidebar08NavMainComponent {
  readonly items = input<readonly Sidebar08NavItem[]>([]);
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-08-nav-projects.component.html',
      path: 'src/components/sidebar-08/sidebar-08-nav-projects.component.html',
      content: `<div z-sidebar-group class="group-data-[collapsible=icon]:hidden">
  <div z-sidebar-group-label>Projects</div>

  <ul z-sidebar-menu>
    @for (item of projects(); track item.name) {
      <li z-sidebar-menu-item>
        <a z-sidebar-menu-button [href]="item.url">
          <ng-icon [name]="item.icon" />
          <span>{{ item.name }}</span>
        </a>

        <button z-sidebar-menu-action zShowOnHover z-dropdown [zDropdownMenu]="projectMenu">
          <ng-icon name="lucideMoreHorizontal" />
          <span class="sr-only">More</span>
        </button>

        <z-dropdown-menu-content #projectMenu="zDropdownMenuContent" class="w-48 rounded-lg">
          <z-dropdown-menu-item>
            <ng-icon name="lucideFolder" class="text-muted-foreground" />
            <span>View Project</span>
          </z-dropdown-menu-item>
          <z-dropdown-menu-item>
            <ng-icon name="lucideForward" class="text-muted-foreground" />
            <span>Share Project</span>
          </z-dropdown-menu-item>
          <z-dropdown-menu-separator />
          <z-dropdown-menu-item>
            <ng-icon name="lucideTrash2" class="text-muted-foreground" />
            <span>Delete Project</span>
          </z-dropdown-menu-item>
        </z-dropdown-menu-content>
      </li>
    }

    <li z-sidebar-menu-item>
      <button z-sidebar-menu-button class="text-sidebar-foreground/70">
        <ng-icon name="lucideMoreHorizontal" class="text-sidebar-foreground/70" />
        <span>More</span>
      </button>
    </li>
  </ul>
</div>
`,
      language: 'html',
    },
    {
      name: 'sidebar-08-nav-projects.component.ts',
      path: 'src/components/sidebar-08/sidebar-08-nav-projects.component.ts',
      content: `import { ChangeDetectionStrategy, Component, input } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import {
  lucideFolder,
  lucideForward,
  lucideFrame,
  lucideMap,
  lucideMoreHorizontal,
  lucidePieChart,
  lucideTrash2,
} from '@ng-icons/lucide';

import { ZardDropdownImports } from '@zard/components/dropdown/dropdown.imports';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

export interface Sidebar08Project {
  readonly name: string;
  readonly url: string;
  readonly icon: string;
}

@Component({
  selector: 'lib-sidebar-08-nav-projects',
  standalone: true,
  imports: [...ZardSidebarImports, ...ZardDropdownImports, NgIcon],
  viewProviders: [
    provideIcons({
      lucideFolder,
      lucideForward,
      lucideFrame,
      lucideMap,
      lucideMoreHorizontal,
      lucidePieChart,
      lucideTrash2,
    }),
  ],
  templateUrl: './sidebar-08-nav-projects.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Sidebar08NavProjectsComponent {
  readonly projects = input<readonly Sidebar08Project[]>([]);
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-08-nav-secondary.component.html',
      path: 'src/components/sidebar-08/sidebar-08-nav-secondary.component.html',
      content: `<div z-sidebar-group [class]="class()">
  <div z-sidebar-group-content>
    <ul z-sidebar-menu>
      @for (item of items(); track item.title) {
        <li z-sidebar-menu-item>
          <a z-sidebar-menu-button zSize="sm" [href]="item.url">
            <ng-icon [name]="item.icon" />
            <span>{{ item.title }}</span>
          </a>
        </li>
      }
    </ul>
  </div>
</div>
`,
      language: 'html',
    },
    {
      name: 'sidebar-08-nav-secondary.component.ts',
      path: 'src/components/sidebar-08/sidebar-08-nav-secondary.component.ts',
      content: `import { ChangeDetectionStrategy, Component, input } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideLifeBuoy, lucideSend } from '@ng-icons/lucide';

import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

export interface Sidebar08SecondaryItem {
  readonly title: string;
  readonly url: string;
  readonly icon: string;
}

@Component({
  selector: 'lib-sidebar-08-nav-secondary',
  standalone: true,
  imports: [...ZardSidebarImports, NgIcon],
  viewProviders: [provideIcons({ lucideLifeBuoy, lucideSend })],
  templateUrl: './sidebar-08-nav-secondary.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Sidebar08NavSecondaryComponent {
  readonly items = input<readonly Sidebar08SecondaryItem[]>([]);
  readonly class = input<string>('');
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-08-nav-user.component.html',
      path: 'src/components/sidebar-08/sidebar-08-nav-user.component.html',
      content: `<ul z-sidebar-menu>
  <li z-sidebar-menu-item>
    <button
      z-sidebar-menu-button
      zSize="lg"
      z-dropdown
      [zDropdownMenu]="userMenu"
      class="data-[state=open]:bg-sidebar-accent data-[state=open]:text-sidebar-accent-foreground"
    >
      <z-avatar class="size-8 rounded-lg" [zSrc]="user().avatar" [zAlt]="user().name" zFallback="CN" />

      <div class="grid flex-1 text-left text-sm leading-tight">
        <span class="truncate font-medium">{{ user().name }}</span>
        <span class="truncate text-xs">{{ user().email }}</span>
      </div>

      <ng-icon name="lucideChevronsUpDown" class="ml-auto size-4" />
    </button>

    <z-dropdown-menu-content #userMenu="zDropdownMenuContent" class="w-(--sidebar-width) min-w-56 rounded-lg">
      <z-dropdown-menu-label class="p-0 font-normal">
        <div class="flex items-center gap-2 px-1 py-1.5 text-left text-sm">
          <z-avatar class="size-8 rounded-lg" [zSrc]="user().avatar" [zAlt]="user().name" zFallback="CN" />

          <div class="grid flex-1 text-left text-sm leading-tight">
            <span class="truncate font-medium">{{ user().name }}</span>
            <span class="truncate text-xs">{{ user().email }}</span>
          </div>
        </div>
      </z-dropdown-menu-label>

      <z-dropdown-menu-separator />

      <z-dropdown-menu-group>
        <z-dropdown-menu-item>
          <ng-icon name="lucideSparkles" />
          Upgrade to Pro
        </z-dropdown-menu-item>
      </z-dropdown-menu-group>

      <z-dropdown-menu-separator />

      <z-dropdown-menu-group>
        <z-dropdown-menu-item>
          <ng-icon name="lucideBadgeCheck" />
          Account
        </z-dropdown-menu-item>
        <z-dropdown-menu-item>
          <ng-icon name="lucideCreditCard" />
          Billing
        </z-dropdown-menu-item>
        <z-dropdown-menu-item>
          <ng-icon name="lucideBell" />
          Notifications
        </z-dropdown-menu-item>
      </z-dropdown-menu-group>

      <z-dropdown-menu-separator />

      <z-dropdown-menu-item>
        <ng-icon name="lucideLogOut" />
        Log out
      </z-dropdown-menu-item>
    </z-dropdown-menu-content>
  </li>
</ul>
`,
      language: 'html',
    },
    {
      name: 'sidebar-08-nav-user.component.ts',
      path: 'src/components/sidebar-08/sidebar-08-nav-user.component.ts',
      content: `import { ChangeDetectionStrategy, Component, input } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import {
  lucideBadgeCheck,
  lucideBell,
  lucideChevronsUpDown,
  lucideCreditCard,
  lucideLogOut,
  lucideSparkles,
} from '@ng-icons/lucide';

import { ZardAvatarComponent } from '@zard/components/avatar/avatar.component';
import { ZardDropdownImports } from '@zard/components/dropdown/dropdown.imports';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

export interface Sidebar08User {
  readonly name: string;
  readonly email: string;
  readonly avatar: string;
}

@Component({
  selector: 'lib-sidebar-08-nav-user',
  standalone: true,
  imports: [...ZardSidebarImports, ...ZardDropdownImports, ZardAvatarComponent, NgIcon],
  viewProviders: [
    provideIcons({
      lucideBadgeCheck,
      lucideBell,
      lucideChevronsUpDown,
      lucideCreditCard,
      lucideLogOut,
      lucideSparkles,
    }),
  ],
  templateUrl: './sidebar-08-nav-user.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Sidebar08NavUserComponent {
  readonly user = input.required<Sidebar08User>();
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-08.component.html',
      path: 'src/components/sidebar-08/sidebar-08.component.html',
      content: `<z-sidebar-provider>
  <z-sidebar zVariant="inset">
    <div z-sidebar-header>
      <ul z-sidebar-menu>
        <li z-sidebar-menu-item>
          <a z-sidebar-menu-button zSize="lg" href="#">
            <div
              class="bg-sidebar-primary text-sidebar-primary-foreground flex aspect-square size-8 items-center justify-center rounded-lg"
            >
              <ng-icon name="lucideCommand" class="size-4" />
            </div>
            <div class="grid flex-1 text-left text-sm leading-tight">
              <span class="truncate font-medium">Acme Inc</span>
              <span class="truncate text-xs">Enterprise</span>
            </div>
          </a>
        </li>
      </ul>
    </div>

    <z-sidebar-content>
      <lib-sidebar-08-nav-main [items]="navMain" />
      <lib-sidebar-08-nav-projects [projects]="projects" />
      <lib-sidebar-08-nav-secondary [items]="navSecondary" class="mt-auto" />
    </z-sidebar-content>

    <div z-sidebar-footer>
      <lib-sidebar-08-nav-user [user]="user" />
    </div>
  </z-sidebar>

  <main z-sidebar-inset>
    <header class="flex h-16 shrink-0 items-center gap-2">
      <div class="flex items-center gap-2 px-4">
        <button z-sidebar-trigger class="-ml-1" aria-label="Toggle Sidebar"></button>

        <z-separator zOrientation="vertical" class="mr-2 data-[orientation=vertical]:h-4 data-[orientation=vertical]:self-center" />

        <z-breadcrumb>
          <z-breadcrumb-item class="hidden md:block">
            <a z-breadcrumb-link href="#">Build Your Application</a>
          </z-breadcrumb-item>
          <z-breadcrumb-separator class="hidden md:block" />
          <z-breadcrumb-item>
            <span z-breadcrumb-page>Data Fetching</span>
          </z-breadcrumb-item>
        </z-breadcrumb>
      </div>
    </header>

    <div class="flex flex-1 flex-col gap-4 p-4 pt-0">
      <div class="grid auto-rows-min gap-4 md:grid-cols-3">
        <div class="bg-muted/50 aspect-video rounded-xl"></div>
        <div class="bg-muted/50 aspect-video rounded-xl"></div>
        <div class="bg-muted/50 aspect-video rounded-xl"></div>
      </div>
      <div class="bg-muted/50 min-h-[100vh] flex-1 rounded-xl md:min-h-min"></div>
    </div>
  </main>
</z-sidebar-provider>
`,
      language: 'html',
    },
    {
      name: 'sidebar-08.component.ts',
      path: 'src/components/sidebar-08/sidebar-08.component.ts',
      content: `import { ChangeDetectionStrategy, Component } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideCommand } from '@ng-icons/lucide';

import { ZardBreadcrumbImports } from '@zard/components/breadcrumb/breadcrumb.imports';
import { ZardSeparatorComponent } from '@zard/components/separator/separator.component';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

import { Sidebar08NavMainComponent, type Sidebar08NavItem } from './sidebar-08-nav-main.component';
import { Sidebar08NavProjectsComponent, type Sidebar08Project } from './sidebar-08-nav-projects.component';
import { Sidebar08NavSecondaryComponent, type Sidebar08SecondaryItem } from './sidebar-08-nav-secondary.component';
import { Sidebar08NavUserComponent, type Sidebar08User } from './sidebar-08-nav-user.component';

/**
 * \`zVariant="inset"\` styles the inset through \`peer-data-[variant=inset]\`, and \`peer\` only reaches a
 * real DOM sibling. The sidebar therefore lives here rather than inside an app-sidebar wrapper
 * component, which is where the other blocks put it.
 */
@Component({
  selector: 'lib-sidebar-08',
  standalone: true,
  imports: [
    ...ZardSidebarImports,
    ...ZardBreadcrumbImports,
    ZardSeparatorComponent,
    Sidebar08NavMainComponent,
    Sidebar08NavProjectsComponent,
    Sidebar08NavSecondaryComponent,
    Sidebar08NavUserComponent,
    NgIcon,
  ],
  viewProviders: [provideIcons({ lucideCommand })],
  templateUrl: './sidebar-08.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Sidebar08Component {
  // This is sample data.
  protected readonly user: Sidebar08User = {
    name: 'shadcn',
    email: 'm@example.com',
    avatar: 'https://github.com/shadcn.png',
  };

  protected readonly navMain: readonly Sidebar08NavItem[] = [
    {
      title: 'Playground',
      url: '#',
      icon: 'lucideSquareTerminal',
      isActive: true,
      items: [
        { title: 'History', url: '#' },
        { title: 'Starred', url: '#' },
        { title: 'Settings', url: '#' },
      ],
    },
    {
      title: 'Models',
      url: '#',
      icon: 'lucideBot',
      items: [
        { title: 'Genesis', url: '#' },
        { title: 'Explorer', url: '#' },
        { title: 'Quantum', url: '#' },
      ],
    },
    {
      title: 'Documentation',
      url: '#',
      icon: 'lucideBookOpen',
      items: [
        { title: 'Introduction', url: '#' },
        { title: 'Get Started', url: '#' },
        { title: 'Tutorials', url: '#' },
        { title: 'Changelog', url: '#' },
      ],
    },
    {
      title: 'Settings',
      url: '#',
      icon: 'lucideSettings2',
      items: [
        { title: 'General', url: '#' },
        { title: 'Team', url: '#' },
        { title: 'Billing', url: '#' },
        { title: 'Limits', url: '#' },
      ],
    },
  ];

  protected readonly navSecondary: readonly Sidebar08SecondaryItem[] = [
    { title: 'Support', url: '#', icon: 'lucideLifeBuoy' },
    { title: 'Feedback', url: '#', icon: 'lucideSend' },
  ];

  protected readonly projects: readonly Sidebar08Project[] = [
    { name: 'Design Engineering', url: '#', icon: 'lucideFrame' },
    { name: 'Sales & Marketing', url: '#', icon: 'lucidePieChart' },
    { name: 'Travel', url: '#', icon: 'lucideMap' },
  ];
}
`,
      language: 'typescript',
    },
  ],
};
