import type { Block } from '@doc/domain/components/block-container/block-container.component';

import { Sidebar08Component } from './sidebar-08.component';

export const sidebar08Block: Block = {
  id: 'sidebar-08',
  title: 'Sidebar 08',
  description: 'An inset sidebar with secondary navigation.',
  component: Sidebar08Component,
  category: 'Sidebar',
  image: {
    light: '/blocks/sidebar-08/light.png',
    dark: '/blocks/sidebar-08/dark.png',
  },
  // Generated by `npm run sync:blocks` from the sibling component files — do not edit by hand.
  files: [
    {
      name: 'sidebar-08.component.html',
      path: 'src/components/sidebar-08/sidebar-08.component.html',
      content: `<div class="flex min-h-screen items-center justify-center">
  <p>Sidebar 08</p>
</div>
`,
      language: 'html',
    },
    {
      name: 'sidebar-08.component.ts',
      path: 'src/components/sidebar-08/sidebar-08.component.ts',
      content: `import { Component } from '@angular/core';

@Component({
  selector: 'lib-sidebar-08',
  standalone: true,
  imports: [],
  templateUrl: './sidebar-08.component.html',
})
export class Sidebar08Component {}
`,
      language: 'typescript',
    },
  ],
};
