import type { ApiSection } from '@doc/domain/components/api-reference/api-reference.types';

export const CHART_API: ApiSection[] = [
  {
    selector: 'z-chart',
    description: 'A chart container built on Apache ECharts through ngx-echarts.',
    props: [
      { name: '[class]', description: 'Additional CSS classes', type: 'ClassValue', default: "''" },
      {
        name: '[zConfig]',
        description: 'Labels, colors and icons per data key',
        type: 'ZardChartConfig',
        default: '{}',
      },
      { name: '[zData]', description: 'The rows to plot', type: 'Record<string, unknown>[]', default: '[]' },
      {
        name: '[zType]',
        description: 'Default type of every series',
        type: "'area' | 'bar' | 'line' | 'pie' | 'radar' | 'radial'",
        default: "'bar'",
      },
      {
        name: '[zSeries]',
        description: 'Series to render, either as data keys or fully described',
        type: 'string[] | ZardChartSeries[]',
        default: '[]',
      },
      { name: '[zXAxisKey]', description: 'Key used for the category axis', type: 'string', default: '-' },
      {
        name: '[zNameKey]',
        description: 'Key naming each slice or segment on pie, radar and radial charts. Falls back to zXAxisKey',
        type: 'string',
        default: '-',
      },
      { name: '[zStacked]', description: 'Stacks every series together', type: 'boolean', default: 'false' },
      {
        name: '[zStackOffset]',
        description: "'expand' normalises the stack to 0-1, the Recharts stackOffset equivalent",
        type: "'none' | 'expand'",
        default: "'none'",
      },
      { name: '[zHorizontal]', description: 'Swaps the category and value axes', type: 'boolean', default: 'false' },
      {
        name: '[zGrid]',
        description: 'Grid lines to draw, by direction. Equivalent to CartesianGrid',
        type: "boolean | 'horizontal' | 'vertical'",
        default: "'horizontal'",
      },
      { name: '[zXAxis]', description: 'Shows the category axis labels', type: 'boolean', default: 'true' },
      { name: '[zYAxis]', description: 'Shows the value axis labels', type: 'boolean', default: 'false' },
      {
        name: '[zXAxisFormatter]',
        description: 'Formats every category tick. Equivalent to tickFormatter',
        type: '(value: string) => string',
        default: '-',
      },
      {
        name: '[zYAxisFormatter]',
        description: 'Formats every value tick',
        type: '(value: number) => string',
        default: '-',
      },
      {
        name: '[zInnerRadius]',
        description: 'Inner radius of pie, donut and radial charts',
        type: 'string | number',
        default: '-',
      },
      {
        name: '[zOuterRadius]',
        description: 'Outer radius of pie, donut, radar and radial charts',
        type: 'string | number',
        default: '-',
      },
      {
        name: '[zRadialVariant]',
        description: 'How a radial chart is drawn: polar bars or a gauge',
        type: "'bar' | 'gauge'",
        default: "'bar'",
      },
      {
        name: '[zRadarShape]',
        description: 'Shape of the radar grid. Equivalent to PolarGrid gridType',
        type: "'polygon' | 'circle'",
        default: "'polygon'",
      },
      { name: '[zStartAngle]', description: 'Start angle of pie and radial charts', type: 'number', default: '-' },
      { name: '[zEndAngle]', description: 'End angle of pie and radial charts', type: 'number', default: '-' },
      { name: '[zPadAngle]', description: 'Gap between pie slices, in degrees', type: 'number', default: '0' },
      {
        name: '[zGradient]',
        description: 'Fills area series with a vertical gradient instead of a flat tint',
        type: 'boolean',
        default: 'false',
      },
      {
        name: '[zLabel]',
        description: 'Prints the value on every data point. Equivalent to LabelList',
        type: 'boolean',
        default: 'false',
      },
      {
        name: '[zCenterValue]',
        description: 'Big text in the middle of a donut or radial chart',
        type: 'string',
        default: '-',
      },
      {
        name: '[zCenterLabel]',
        description: 'Caption under zCenterValue',
        type: 'string',
        default: '-',
      },
      {
        name: '[zAccessibility]',
        description: "Enables ECharts' aria description plus role and aria-label on the canvas",
        type: 'boolean',
        default: 'true',
      },
      { name: '[zAnimation]', description: 'Animates the chart on data changes', type: 'boolean', default: 'true' },
      {
        name: '[zDataZoom]',
        description: 'ECharts extra, opt-in: adds inside and slider zooming',
        type: 'boolean',
        default: 'false',
      },
      {
        name: '[zBrush]',
        description: 'ECharts extra, opt-in: adds the brush selection toolbox',
        type: 'boolean',
        default: 'false',
      },
      {
        name: '[zToolbox]',
        description: 'ECharts extra, opt-in: adds the zoom, restore and export toolbox',
        type: 'boolean',
        default: 'false',
      },
      { name: '[zRenderer]', description: 'ECharts renderer', type: "'canvas' | 'svg'", default: "'canvas'" },
      {
        name: '[zSsrWidth]',
        description: 'Width, in pixels, of the SVG rendered on the server',
        type: 'number',
        default: '600',
      },
      {
        name: '[zSsrHeight]',
        description: 'Height, in pixels, of the SVG rendered on the server',
        type: 'number',
        default: '300',
      },
      {
        name: '[zOption]',
        description: 'Escape hatch deep-merged over the generated option, always winning',
        type: 'EChartsOption',
        default: '{}',
      },
      {
        name: '(zChartInit)',
        description: 'Emits the ECharts instance once created',
        type: 'EChartsType',
        default: '-',
      },
      {
        name: '(zChartClick)',
        description: 'Emitted when a data item is clicked',
        type: 'ECElementEvent',
        default: '-',
      },
      {
        name: '(zLegendSelectChanged)',
        description: "Emitted when ECharts' legend selection changes",
        type: 'unknown',
        default: '-',
      },
      { name: '(zDataZoomChange)', description: 'Emitted while the data zoom moves', type: 'unknown', default: '-' },
    ],
  },
  {
    selector: 'z-chart-tooltip',
    description: 'Declares the tooltip the parent chart should build. Renders no DOM of its own.',
    props: [
      {
        name: '[class]',
        description: 'Additional CSS classes on the tooltip container',
        type: 'ClassValue',
        default: "''",
      },
      {
        name: '[zIndicator]',
        description: 'Shape of the color indicator on each row',
        type: "'dot' | 'line' | 'dashed'",
        default: "'dot'",
      },
      { name: '[zHideLabel]', description: 'Hides the tooltip heading', type: 'boolean', default: 'false' },
      { name: '[zHideIndicator]', description: 'Hides the color indicator', type: 'boolean', default: 'false' },
      { name: '[zLabelKey]', description: 'Config key used for the heading', type: 'string', default: '-' },
      { name: '[zNameKey]', description: 'Config key used for each row name', type: 'string', default: '-' },
      {
        name: '[zLabelFormatter]',
        description: 'Formats the heading',
        type: '(value: string) => string',
        default: '-',
      },
      {
        name: '[zValueFormatter]',
        description: 'Formats every value',
        type: '(value: number, name: string) => string',
        default: '-',
      },
      {
        name: '[zTrigger]',
        description: "'axis' groups every series of a category, 'item' shows the hovered item only",
        type: "'axis' | 'item'",
        default: "'axis'",
      },
      {
        name: '[zLabelClass]',
        description: 'Additional CSS classes on the heading',
        type: 'ClassValue',
        default: "''",
      },
    ],
  },
  {
    selector: 'z-chart-legend',
    description: 'Renders the shadcn legend markup below (or above) the chart and toggles series on click.',
    props: [
      { name: '[class]', description: 'Additional CSS classes', type: 'ClassValue', default: "''" },
      { name: '[zNameKey]', description: 'Config key used for each entry name', type: 'string', default: '-' },
      {
        name: '[zVerticalAlign]',
        description: 'Places the legend above or below the chart',
        type: "'top' | 'bottom'",
        default: "'bottom'",
      },
    ],
  },
];
