/**
 * The translation table between icon sets.
 *
 * Each row is an icon by what it MEANS — `check`, `chevron-down` — and the
 * value is the symbol each set exports for it. Only the `lucide` column exists
 * today, the one set the library supports; supporting another one means filling
 * in its column, and nothing else along the install path changes.
 *
 * This is the copy bundled with the CLI. It is published at
 * `<registry>/icons.json`, and that is where the CLI reads it from at run time
 * — the file here is what holds when the registry does not answer, and the
 * floor the published table is generated from.
 *
 * The list covers every icon the components and demos use today. A new icon in
 * the code with no row here is an error: `icons.spec.ts` compares this table
 * against what `libs/zard` actually imports.
 *
 * The tokens come from the lucide name in kebab-case because that already is
 * the icon's semantic name (`lucideChevronDown` → `chevron-down`) — the key
 * belongs to the table, not to the set, and stays valid once lucide is no
 * longer the only column.
 */

export const ICON_MAP: Record<string, Record<string, string>> = {
  'alert-triangle': { lucide: 'lucideAlertTriangle' },
  'app-window': { lucide: 'lucideAppWindow' },
  archive: { lucide: 'lucideArchive' },
  'arrow-left': { lucide: 'lucideArrowLeft' },
  'arrow-right': { lucide: 'lucideArrowRight' },
  'arrow-up': { lucide: 'lucideArrowUp' },
  'arrow-up-right': { lucide: 'lucideArrowUpRight' },
  'audio-lines': { lucide: 'lucideAudioLines' },
  'badge-check': { lucide: 'lucideBadgeCheck' },
  bell: { lucide: 'lucideBell' },
  bluetooth: { lucide: 'lucideBluetooth' },
  bold: { lucide: 'lucideBold' },
  'book-open-check': { lucide: 'lucideBookOpenCheck' },
  bookmark: { lucide: 'lucideBookmark' },
  bot: { lucide: 'lucideBot' },
  calculator: { lucide: 'lucideCalculator' },
  calendar: { lucide: 'lucideCalendar' },
  'calendar-plus': { lucide: 'lucideCalendarPlus' },
  check: { lucide: 'lucideCheck' },
  'chevron-down': { lucide: 'lucideChevronDown' },
  'chevron-left': { lucide: 'lucideChevronLeft' },
  'chevron-right': { lucide: 'lucideChevronRight' },
  'chevron-up': { lucide: 'lucideChevronUp' },
  'chevrons-left': { lucide: 'lucideChevronsLeft' },
  'chevrons-right': { lucide: 'lucideChevronsRight' },
  'chevrons-up-down': { lucide: 'lucideChevronsUpDown' },
  'circle-alert': { lucide: 'lucideCircleAlert' },
  'circle-check': { lucide: 'lucideCircleCheck' },
  'circle-dashed': { lucide: 'lucideCircleDashed' },
  'circle-fading-arrow-up': { lucide: 'lucideCircleFadingArrowUp' },
  'circle-fading-plus': { lucide: 'lucideCircleFadingPlus' },
  'circle-help': { lucide: 'lucideCircleHelp' },
  'circle-small': { lucide: 'lucideCircleSmall' },
  'clipboard-paste': { lucide: 'lucideClipboardPaste' },
  clock: { lucide: 'lucideClock' },
  'clock-2': { lucide: 'lucideClock2' },
  cloud: { lucide: 'lucideCloud' },
  code: { lucide: 'lucideCode' },
  copy: { lucide: 'lucideCopy' },
  'corner-down-left': { lucide: 'lucideCornerDownLeft' },
  'credit-card': { lucide: 'lucideCreditCard' },
  dot: { lucide: 'lucideDot' },
  download: { lucide: 'lucideDownload' },
  ellipsis: { lucide: 'lucideEllipsis' },
  'external-link': { lucide: 'lucideExternalLink' },
  'eye-off': { lucide: 'lucideEyeOff' },
  'file-code': { lucide: 'lucideFileCode' },
  'file-code-2': { lucide: 'lucideFileCode2' },
  'file-text': { lucide: 'lucideFileText' },
  folder: { lucide: 'lucideFolder' },
  'folder-code': { lucide: 'lucideFolderCode' },
  'folder-plus': { lucide: 'lucideFolderPlus' },
  footprints: { lucide: 'lucideFootprints' },
  'gallery-vertical-end': { lucide: 'lucideGalleryVerticalEnd' },
  'git-branch': { lucide: 'lucideGitBranch' },
  globe: { lucide: 'lucideGlobe' },
  house: { lucide: 'lucideHouse' },
  image: { lucide: 'lucideImage' },
  inbox: { lucide: 'lucideInbox' },
  info: { lucide: 'lucideInfo' },
  italic: { lucide: 'lucideItalic' },
  keyboard: { lucide: 'lucideKeyboard' },
  'layout-grid': { lucide: 'lucideLayoutGrid' },
  lightbulb: { lucide: 'lucideLightbulb' },
  'lightbulb-off': { lucide: 'lucideLightbulbOff' },
  list: { lucide: 'lucideList' },
  'list-filter': { lucide: 'lucideListFilter' },
  'list-filter-plus': { lucide: 'lucideListFilterPlus' },
  loader: { lucide: 'lucideLoader' },
  'loader-2': { lucide: 'lucideLoader2' },
  'loader-circle': { lucide: 'lucideLoaderCircle' },
  'log-out': { lucide: 'lucideLogOut' },
  mail: { lucide: 'lucideMail' },
  'mail-check': { lucide: 'lucideMailCheck' },
  minus: { lucide: 'lucideMinus' },
  monitor: { lucide: 'lucideMonitor' },
  'more-horizontal': { lucide: 'lucideMoreHorizontal' },
  'octagon-x': { lucide: 'lucideOctagonX' },
  'panel-left': { lucide: 'lucidePanelLeft' },
  pencil: { lucide: 'lucidePencil' },
  plus: { lucide: 'lucidePlus' },
  'refresh-ccw': { lucide: 'lucideRefreshCcw' },
  'refresh-cw': { lucide: 'lucideRefreshCw' },
  'rotate-ccw': { lucide: 'lucideRotateCcw' },
  save: { lucide: 'lucideSave' },
  scissors: { lucide: 'lucideScissors' },
  search: { lucide: 'lucideSearch' },
  settings: { lucide: 'lucideSettings' },
  share: { lucide: 'lucideShare' },
  'shield-alert': { lucide: 'lucideShieldAlert' },
  smartphone: { lucide: 'lucideSmartphone' },
  smile: { lucide: 'lucideSmile' },
  star: { lucide: 'lucideStar' },
  sun: { lucide: 'lucideSun' },
  tag: { lucide: 'lucideTag' },
  terminal: { lucide: 'lucideTerminal' },
  'thumbs-down': { lucide: 'lucideThumbsDown' },
  'thumbs-up': { lucide: 'lucideThumbsUp' },
  trash: { lucide: 'lucideTrash' },
  'trash-2': { lucide: 'lucideTrash2' },
  'trending-up': { lucide: 'lucideTrendingUp' },
  'triangle-alert': { lucide: 'lucideTriangleAlert' },
  underline: { lucide: 'lucideUnderline' },
  user: { lucide: 'lucideUser' },
  'user-round-x': { lucide: 'lucideUserRoundX' },
  'volume-off': { lucide: 'lucideVolumeOff' },
  waves: { lucide: 'lucideWaves' },
  x: { lucide: 'lucideX' },
  'zoom-in': { lucide: 'lucideZoomIn' },
  'zoom-out': { lucide: 'lucideZoomOut' },
};
