import type { Block } from '@doc/domain/components/block-container/block-container.component';

import { Sidebar09Component } from './sidebar-09.component';

export const sidebar09Block: Block = {
  id: 'sidebar-09',
  title: 'Sidebar 09',
  description: 'Collapsible nested sidebars.',
  component: Sidebar09Component,
  category: 'Sidebar',
  image: {
    light: '/blocks/sidebar-09/light.png',
    dark: '/blocks/sidebar-09/dark.png',
  },
  // Generated by `npm run sync:blocks` from the sibling component files — do not edit by hand.
  files: [
    {
      name: 'sidebar-09-app-sidebar.component.html',
      path: 'src/components/sidebar-09/sidebar-09-app-sidebar.component.html',
      content: `<z-sidebar zCollapsible="icon" class="overflow-hidden *:data-[sidebar=sidebar]:flex-row">
  <!-- This is the first sidebar. -->
  <!-- We disable collapsible and adjust width to icon, so it appears as icons. -->
  <z-sidebar zCollapsible="none" class="w-[calc(var(--sidebar-width-icon)+1px)]! border-r">
    <div z-sidebar-header>
      <ul z-sidebar-menu>
        <li z-sidebar-menu-item>
          <a z-sidebar-menu-button zSize="lg" href="#" class="md:h-8 md:p-0">
            <div
              class="bg-sidebar-primary text-sidebar-primary-foreground flex aspect-square size-8 items-center justify-center rounded-lg"
            >
              <ng-icon name="lucideCommand" class="size-4" />
            </div>
            <div class="grid flex-1 text-left text-sm leading-tight">
              <span class="truncate font-medium">Acme Inc</span>
              <span class="truncate text-xs">Enterprise</span>
            </div>
          </a>
        </li>
      </ul>
    </div>

    <z-sidebar-content>
      <div z-sidebar-group>
        <div z-sidebar-group-content class="px-1.5 md:px-0">
          <ul z-sidebar-menu>
            @for (item of navMain; track item.title) {
              <li z-sidebar-menu-item>
                <button
                  z-sidebar-menu-button
                  class="px-2.5 md:px-2"
                  [zTooltip]="item.title"
                  [zActive]="item.title === activeItem().title"
                  (click)="activeItem.set(item)"
                >
                  <ng-icon [name]="item.icon" />
                  <span>{{ item.title }}</span>
                </button>
              </li>
            }
          </ul>
        </div>
      </div>
    </z-sidebar-content>

    <div z-sidebar-footer>
      <lib-sidebar-09-nav-user [user]="user" />
    </div>
  </z-sidebar>

  <!-- This is the second sidebar. -->
  <!-- We disable collapsible and let it fill the remaining space. -->
  <z-sidebar zCollapsible="none" class="hidden flex-1 md:flex">
    <div z-sidebar-header class="gap-3.5 border-b p-4">
      <div class="flex w-full items-center justify-between">
        <div class="text-foreground text-base font-medium">{{ activeItem().title }}</div>

        <label z-field-label for="sidebar-09-unreads" class="flex items-center gap-2 text-sm">
          <span>Unreads</span>
          <z-switch zId="sidebar-09-unreads" class="shadow-none" />
        </label>
      </div>

      <input z-input z-sidebar-input placeholder="Type to search..." />
    </div>

    <z-sidebar-content>
      <div z-sidebar-group class="px-0">
        <div z-sidebar-group-content>
          @for (mail of mails(); track mail.email) {
            <a
              href="#"
              class="hover:bg-sidebar-accent hover:text-sidebar-accent-foreground flex flex-col items-start gap-2 border-b p-4 text-sm leading-tight whitespace-nowrap last:border-b-0"
            >
              <div class="flex w-full items-center gap-2">
                <span>{{ mail.name }}</span>
                <span class="ml-auto text-xs">{{ mail.date }}</span>
              </div>
              <span class="font-medium">{{ mail.subject }}</span>
              <span class="line-clamp-2 w-[260px] text-xs whitespace-break-spaces">{{ mail.teaser }}</span>
            </a>
          }
        </div>
      </div>
    </z-sidebar-content>
  </z-sidebar>
</z-sidebar>
`,
      language: 'html',
    },
    {
      name: 'sidebar-09-app-sidebar.component.ts',
      path: 'src/components/sidebar-09/sidebar-09-app-sidebar.component.ts',
      content: `import { ChangeDetectionStrategy, Component, computed, signal } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideArchiveX, lucideCommand, lucideFile, lucideInbox, lucideSend, lucideTrash2 } from '@ng-icons/lucide';

import { ZardFieldImports } from '@zard/components/field/field.imports';
import { ZardInputComponent } from '@zard/components/input/input.component';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';
import { ZardSwitchComponent } from '@zard/components/switch/switch.component';

import { Sidebar09NavUserComponent, type Sidebar09User } from './sidebar-09-nav-user.component';

interface NavItem {
  readonly title: string;
  readonly url: string;
  readonly icon: string;
}

interface Mail {
  readonly name: string;
  readonly email: string;
  readonly subject: string;
  readonly date: string;
  readonly teaser: string;
}

@Component({
  selector: 'lib-sidebar-09-app-sidebar',
  standalone: true,
  imports: [
    ...ZardSidebarImports,
    ...ZardFieldImports,
    ZardInputComponent,
    ZardSwitchComponent,
    Sidebar09NavUserComponent,
    NgIcon,
  ],
  viewProviders: [provideIcons({ lucideArchiveX, lucideCommand, lucideFile, lucideInbox, lucideSend, lucideTrash2 })],
  templateUrl: './sidebar-09-app-sidebar.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Sidebar09AppSidebarComponent {
  // This is sample data.
  protected readonly user: Sidebar09User = {
    name: 'shadcn',
    email: 'm@example.com',
    avatar: 'https://github.com/shadcn.png',
  };

  protected readonly navMain: readonly NavItem[] = [
    { title: 'Inbox', url: '#', icon: 'lucideInbox' },
    { title: 'Drafts', url: '#', icon: 'lucideFile' },
    { title: 'Sent', url: '#', icon: 'lucideSend' },
    { title: 'Junk', url: '#', icon: 'lucideArchiveX' },
    { title: 'Trash', url: '#', icon: 'lucideTrash2' },
  ];

  protected readonly activeItem = signal<NavItem>(this.navMain[0]);

  private readonly allMails: readonly Mail[] = [
    {
      name: 'William Smith',
      email: 'williamsmith@example.com',
      subject: 'Meeting Tomorrow',
      date: '09:34 AM',
      teaser:
        'Hi team, just a reminder about our meeting tomorrow at 10 AM. Please come prepared with your project updates.',
    },
    {
      name: 'Alice Smith',
      email: 'alicesmith@example.com',
      subject: 'Re: Project Update',
      date: 'Yesterday',
      teaser: 'Thanks for the update. The progress looks great so far. Let us discuss the next steps.',
    },
    {
      name: 'Bob Johnson',
      email: 'bobjohnson@example.com',
      subject: 'Weekend Plans',
      date: '2 days ago',
      teaser: 'Hey everyone! I am thinking of organising a team outing this weekend. Would you be interested?',
    },
    {
      name: 'Emily Davis',
      email: 'emilydavis@example.com',
      subject: 'Re: Question about Budget',
      date: '2 days ago',
      teaser: 'I have reviewed the budget numbers you sent over. Can we set up a quick call to discuss?',
    },
    {
      name: 'Michael Wilson',
      email: 'michaelwilson@example.com',
      subject: 'Important Announcement',
      date: '1 week ago',
      teaser: 'Please join us for an all-hands meeting this Friday to discuss some exciting news.',
    },
    {
      name: 'Sarah Brown',
      email: 'sarahbrown@example.com',
      subject: 'Re: Feedback on Proposal',
      date: '1 week ago',
      teaser: 'Thanks for sending the proposal. I have a few thoughts on the timeline we should align on.',
    },
    {
      name: 'David Lee',
      email: 'davidlee@example.com',
      subject: 'New Project Idea',
      date: '1 week ago',
      teaser: 'I had an idea for a new project that could help us streamline our workflow.',
    },
  ];

  /**
   * shadcn reshuffles and re-slices this list with \`Math.random()\` on every click. That would drift
   * between the server and the client, so the list rotates deterministically instead.
   */
  protected readonly mails = computed(() => {
    const offset = this.navMain.indexOf(this.activeItem());

    return [...this.allMails.slice(offset), ...this.allMails.slice(0, offset)].slice(0, 5 + offset);
  });
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-09-nav-user.component.html',
      path: 'src/components/sidebar-09/sidebar-09-nav-user.component.html',
      content: `<ul z-sidebar-menu>
  <li z-sidebar-menu-item>
    <button
      z-sidebar-menu-button
      zSize="lg"
      z-dropdown
      [zDropdownMenu]="userMenu"
      class="data-[state=open]:bg-sidebar-accent data-[state=open]:text-sidebar-accent-foreground"
    >
      <z-avatar class="size-8 rounded-lg" [zSrc]="user().avatar" [zAlt]="user().name" zFallback="CN" />

      <div class="grid flex-1 text-left text-sm leading-tight">
        <span class="truncate font-medium">{{ user().name }}</span>
        <span class="truncate text-xs">{{ user().email }}</span>
      </div>

      <ng-icon name="lucideChevronsUpDown" class="ml-auto size-4" />
    </button>

    <z-dropdown-menu-content #userMenu="zDropdownMenuContent" class="w-(--sidebar-width) min-w-56 rounded-lg">
      <z-dropdown-menu-label class="p-0 font-normal">
        <div class="flex items-center gap-2 px-1 py-1.5 text-left text-sm">
          <z-avatar class="size-8 rounded-lg" [zSrc]="user().avatar" [zAlt]="user().name" zFallback="CN" />

          <div class="grid flex-1 text-left text-sm leading-tight">
            <span class="truncate font-medium">{{ user().name }}</span>
            <span class="truncate text-xs">{{ user().email }}</span>
          </div>
        </div>
      </z-dropdown-menu-label>

      <z-dropdown-menu-separator />

      <z-dropdown-menu-group>
        <z-dropdown-menu-item>
          <ng-icon name="lucideSparkles" />
          Upgrade to Pro
        </z-dropdown-menu-item>
      </z-dropdown-menu-group>

      <z-dropdown-menu-separator />

      <z-dropdown-menu-group>
        <z-dropdown-menu-item>
          <ng-icon name="lucideBadgeCheck" />
          Account
        </z-dropdown-menu-item>
        <z-dropdown-menu-item>
          <ng-icon name="lucideCreditCard" />
          Billing
        </z-dropdown-menu-item>
        <z-dropdown-menu-item>
          <ng-icon name="lucideBell" />
          Notifications
        </z-dropdown-menu-item>
      </z-dropdown-menu-group>

      <z-dropdown-menu-separator />

      <z-dropdown-menu-item>
        <ng-icon name="lucideLogOut" />
        Log out
      </z-dropdown-menu-item>
    </z-dropdown-menu-content>
  </li>
</ul>
`,
      language: 'html',
    },
    {
      name: 'sidebar-09-nav-user.component.ts',
      path: 'src/components/sidebar-09/sidebar-09-nav-user.component.ts',
      content: `import { ChangeDetectionStrategy, Component, input } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import {
  lucideBadgeCheck,
  lucideBell,
  lucideChevronsUpDown,
  lucideCreditCard,
  lucideLogOut,
  lucideSparkles,
} from '@ng-icons/lucide';

import { ZardAvatarComponent } from '@zard/components/avatar/avatar.component';
import { ZardDropdownImports } from '@zard/components/dropdown/dropdown.imports';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

export interface Sidebar09User {
  readonly name: string;
  readonly email: string;
  readonly avatar: string;
}

@Component({
  selector: 'lib-sidebar-09-nav-user',
  standalone: true,
  imports: [...ZardSidebarImports, ...ZardDropdownImports, ZardAvatarComponent, NgIcon],
  viewProviders: [
    provideIcons({
      lucideBadgeCheck,
      lucideBell,
      lucideChevronsUpDown,
      lucideCreditCard,
      lucideLogOut,
      lucideSparkles,
    }),
  ],
  templateUrl: './sidebar-09-nav-user.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Sidebar09NavUserComponent {
  readonly user = input.required<Sidebar09User>();
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-09.component.html',
      path: 'src/components/sidebar-09/sidebar-09.component.html',
      content: `<z-sidebar-provider style="--sidebar-width: 350px">
  <lib-sidebar-09-app-sidebar />

  <main z-sidebar-inset>
    <header class="bg-background sticky top-0 flex shrink-0 items-center gap-2 border-b p-4">
      <button z-sidebar-trigger class="-ml-1" aria-label="Toggle Sidebar"></button>

      <z-separator zOrientation="vertical" class="mr-2 data-[orientation=vertical]:h-4 data-[orientation=vertical]:self-center" />

      <z-breadcrumb>
        <z-breadcrumb-item class="hidden md:block">
          <a z-breadcrumb-link href="#">All Inboxes</a>
        </z-breadcrumb-item>
        <z-breadcrumb-separator class="hidden md:block" />
        <z-breadcrumb-item>
          <span z-breadcrumb-page>Inbox</span>
        </z-breadcrumb-item>
      </z-breadcrumb>
    </header>

    <div class="flex flex-1 flex-col gap-4 p-4">
      @for (item of placeholders; track item) {
        <div class="bg-muted/50 aspect-video h-12 w-full rounded-lg"></div>
      }
    </div>
  </main>
</z-sidebar-provider>
`,
      language: 'html',
    },
    {
      name: 'sidebar-09.component.ts',
      path: 'src/components/sidebar-09/sidebar-09.component.ts',
      content: `import { ChangeDetectionStrategy, Component } from '@angular/core';

import { ZardBreadcrumbImports } from '@zard/components/breadcrumb/breadcrumb.imports';
import { ZardSeparatorComponent } from '@zard/components/separator/separator.component';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

import { Sidebar09AppSidebarComponent } from './sidebar-09-app-sidebar.component';

@Component({
  selector: 'lib-sidebar-09',
  standalone: true,
  imports: [...ZardSidebarImports, ...ZardBreadcrumbImports, ZardSeparatorComponent, Sidebar09AppSidebarComponent],
  templateUrl: './sidebar-09.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Sidebar09Component {
  protected readonly placeholders = Array.from({ length: 24 }, (_, index) => index);
}
`,
      language: 'typescript',
    },
  ],
};
