import type { Block } from '@doc/domain/components/block-container/block-container.component';

import { Sidebar09Component } from './sidebar-09.component';

export const sidebar09Block: Block = {
  id: 'sidebar-09',
  title: 'Sidebar 09',
  description: 'Collapsible nested sidebars.',
  component: Sidebar09Component,
  category: 'Sidebar',
  image: {
    light: '/blocks/sidebar-09/light.png',
    dark: '/blocks/sidebar-09/dark.png',
  },
  // Generated by `npm run sync:blocks` from the sibling component files — do not edit by hand.
  files: [
    {
      name: 'sidebar-09.component.html',
      path: 'src/components/sidebar-09/sidebar-09.component.html',
      content: `<div class="flex min-h-screen items-center justify-center">
  <p>Sidebar 09</p>
</div>
`,
      language: 'html',
    },
    {
      name: 'sidebar-09.component.ts',
      path: 'src/components/sidebar-09/sidebar-09.component.ts',
      content: `import { Component } from '@angular/core';

@Component({
  selector: 'lib-sidebar-09',
  standalone: true,
  imports: [],
  templateUrl: './sidebar-09.component.html',
})
export class Sidebar09Component {}
`,
      language: 'typescript',
    },
  ],
};
