import {
  ZardSidebarMenuActionComponent,
  ZardSidebarMenuBadgeComponent,
  ZardSidebarMenuButtonComponent,
  ZardSidebarMenuComponent,
  ZardSidebarMenuItemComponent,
  ZardSidebarMenuSkeletonComponent,
  ZardSidebarMenuSubButtonComponent,
  ZardSidebarMenuSubComponent,
  ZardSidebarMenuSubItemComponent,
} from '@/shared/components/sidebar/sidebar-menu.component';
import {
  ZardSidebarContentComponent,
  ZardSidebarFooterComponent,
  ZardSidebarGroupActionComponent,
  ZardSidebarGroupComponent,
  ZardSidebarGroupContentComponent,
  ZardSidebarGroupLabelComponent,
  ZardSidebarHeaderComponent,
  ZardSidebarInputDirective,
  ZardSidebarSeparatorComponent,
} from '@/shared/components/sidebar/sidebar-primitives.component';
import {
  ZardSidebarComponent,
  ZardSidebarInsetComponent,
  ZardSidebarProviderComponent,
  ZardSidebarRailComponent,
  ZardSidebarTriggerComponent,
} from '@/shared/components/sidebar/sidebar.component';

export const ZardSidebarImports = [
  ZardSidebarProviderComponent,
  ZardSidebarComponent,
  ZardSidebarTriggerComponent,
  ZardSidebarRailComponent,
  ZardSidebarInsetComponent,
  ZardSidebarInputDirective,
  ZardSidebarHeaderComponent,
  ZardSidebarFooterComponent,
  ZardSidebarSeparatorComponent,
  ZardSidebarContentComponent,
  ZardSidebarGroupComponent,
  ZardSidebarGroupLabelComponent,
  ZardSidebarGroupActionComponent,
  ZardSidebarGroupContentComponent,
  ZardSidebarMenuComponent,
  ZardSidebarMenuItemComponent,
  ZardSidebarMenuButtonComponent,
  ZardSidebarMenuActionComponent,
  ZardSidebarMenuBadgeComponent,
  ZardSidebarMenuSkeletonComponent,
  ZardSidebarMenuSubComponent,
  ZardSidebarMenuSubItemComponent,
  ZardSidebarMenuSubButtonComponent,
] as const;
