import type { Block } from '@doc/domain/components/block-container/block-container.component';

import { Login01Component } from './login-01.component';

export const login01Block: Block = {
  id: 'login-01',
  title: 'Login form',
  description: 'A simple login form.',
  component: Login01Component,
  category: 'Login',
  image: {
    light: '/blocks/login-01/light.png',
    dark: '/blocks/login-01/dark.png',
  },
  // Generated by `npm run sync:blocks` from the sibling component files — do not edit by hand.
  files: [
    {
      name: 'login-01.component.html',
      path: 'src/components/login-01/login-01.component.html',
      content: `<div class="flex min-h-svh w-full items-center justify-center p-6 md:p-10">
  <div class="w-full max-w-sm">
    <div class="flex flex-col gap-6">
      <z-card>
        <div z-card-header>
          <z-card-title zTitle="Login to your account" />
          <z-card-description zDescription="Enter your email below to login to your account" />
        </div>
        <div z-card-content>
          <form [formGroup]="loginForm" (ngSubmit)="onSubmit()">
            <div z-field-group>
              <div z-field>
                <label z-field-label for="email">Email</label>
                <input z-input id="email" type="email" placeholder="m@example.com" formControlName="email" required />
              </div>
              <div z-field>
                <div class="flex items-center">
                  <label z-field-label for="password">Password</label>
                  <a href="#" class="ml-auto inline-block text-sm underline-offset-4 hover:underline">
                    Forgot your password?
                  </a>
                </div>
                <input z-input id="password" type="password" formControlName="password" required />
              </div>
              <div z-field>
                <button z-button type="submit" [zLoading]="isLoading()" [zDisabled]="isLoading()">Login</button>
                <button z-button zType="outline" type="button">Login with Google</button>
                <p z-field-description class="text-center">
                  Don't have an account?
                  <a href="#">Sign up</a>
                </p>
              </div>
            </div>
          </form>
        </div>
      </z-card>
    </div>
  </div>
</div>
`,
      language: 'html',
    },
    {
      name: 'login-01.component.ts',
      path: 'src/components/login-01/login-01.component.ts',
      content: `import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';

import { ZardButtonComponent } from '@zard/components/button/button.component';
import { ZardCardImports } from '@zard/components/card/card.imports';
import { ZardFieldImports } from '@zard/components/field/field.imports';
import { ZardInputComponent } from '@zard/components/input/input.component';

@Component({
  selector: 'lib-login-01',
  imports: [ReactiveFormsModule, ZardButtonComponent, ZardInputComponent, ...ZardCardImports, ...ZardFieldImports],
  templateUrl: './login-01.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Login01Component {
  protected readonly isLoading = signal(false);

  protected readonly loginForm = new FormGroup({
    email: new FormControl('', [Validators.required, Validators.email]),
    password: new FormControl('', [Validators.required, Validators.minLength(8)]),
  });

  protected onSubmit(): void {
    if (this.loginForm.invalid) {
      this.loginForm.markAllAsTouched();
      return;
    }
    this.isLoading.set(true);
  }
}
`,
      language: 'typescript',
    },
  ],
};
