import type { Block } from '@doc/domain/components/block-container/block-container.component';

import { Sidebar15Component } from './sidebar-15.component';

export const sidebar15Block: Block = {
  id: 'sidebar-15',
  title: 'Sidebar 15',
  description: 'A left and right sidebar.',
  component: Sidebar15Component,
  category: 'Sidebar',
  image: {
    light: '/blocks/sidebar-15/light.png',
    dark: '/blocks/sidebar-15/dark.png',
  },
  // Generated by `npm run sync:blocks` from the sibling component files — do not edit by hand.
  files: [
    {
      name: 'sidebar-15-calendars.component.html',
      path: 'src/components/sidebar-15/sidebar-15-calendars.component.html',
      content: `@for (calendar of calendars(); track calendar.name; let groupIndex = $index) {
  <div z-sidebar-group class="py-0">
    <div z-collapsible class="group/collapsible" [zOpen]="groupIndex === 0">
      <button
        z-collapsible-trigger
        z-sidebar-group-label
        class="group/label text-sidebar-foreground hover:bg-sidebar-accent hover:text-sidebar-accent-foreground w-full text-sm"
      >
        {{ calendar.name }}
        <ng-icon
          name="lucideChevronRight"
          class="ml-auto transition-transform group-data-[state=open]/collapsible:rotate-90"
        />
      </button>

      <z-collapsible-content>
        <div z-sidebar-group-content>
          <ul z-sidebar-menu>
            @for (item of calendar.items; track item; let itemIndex = $index) {
              <li z-sidebar-menu-item>
                <button z-sidebar-menu-button>
                  <div
                    [attr.data-active]="itemIndex < 2"
                    class="group/calendar-item border-sidebar-border text-sidebar-primary-foreground data-[active=true]:border-sidebar-primary data-[active=true]:bg-sidebar-primary flex aspect-square size-4 shrink-0 items-center justify-center rounded-sm border"
                  >
                    <!-- \`hidden!\`/\`block!\`: NgIcon's host \`display\` is declared outside any cascade
                         layer, so unprefixed display utilities cannot override it. -->
                    <ng-icon name="lucideCheck" class="hidden! size-3 group-data-[active=true]/calendar-item:block!" />
                  </div>
                  {{ item }}
                </button>
              </li>
            }
          </ul>
        </div>
      </z-collapsible-content>
    </div>
  </div>

  <z-sidebar-separator class="mx-0" />
}
`,
      language: 'html',
    },
    {
      name: 'sidebar-15-calendars.component.ts',
      path: 'src/components/sidebar-15/sidebar-15-calendars.component.ts',
      content: `import { ChangeDetectionStrategy, Component, input } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideCheck, lucideChevronRight } from '@ng-icons/lucide';

import { ZardCollapsibleImports } from '@zard/components/collapsible/collapsible.imports';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

export interface Sidebar15Calendar {
  readonly name: string;
  readonly items: readonly string[];
}

@Component({
  selector: 'lib-sidebar-15-calendars',
  standalone: true,
  imports: [...ZardSidebarImports, ...ZardCollapsibleImports, NgIcon],
  viewProviders: [provideIcons({ lucideCheck, lucideChevronRight })],
  templateUrl: './sidebar-15-calendars.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Sidebar15CalendarsComponent {
  readonly calendars = input<readonly Sidebar15Calendar[]>([]);
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-15-date-picker.component.html',
      path: 'src/components/sidebar-15/sidebar-15-date-picker.component.html',
      content: `<div z-sidebar-group class="px-0">
  <div z-sidebar-group-content>
    <!-- shadcn hooks the highlight onto react-day-picker's \`.bg-accent\` gridcell; the Zard calendar
         marks the same cell with \`data-today\`, so the selector is retargeted, not redesigned. -->
    <z-calendar
      class="[&_[role=gridcell][data-today]]:bg-sidebar-primary [&_[role=gridcell][data-today]]:text-sidebar-primary-foreground [&_[role=gridcell]]:w-[33px]"
    />
  </div>
</div>
`,
      language: 'html',
    },
    {
      name: 'sidebar-15-date-picker.component.ts',
      path: 'src/components/sidebar-15/sidebar-15-date-picker.component.ts',
      content: `import { ChangeDetectionStrategy, Component } from '@angular/core';

import { ZardCalendarComponent } from '@zard/components/calendar/calendar.component';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

@Component({
  selector: 'lib-sidebar-15-date-picker',
  standalone: true,
  imports: [...ZardSidebarImports, ZardCalendarComponent],
  templateUrl: './sidebar-15-date-picker.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Sidebar15DatePickerComponent {}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-15-nav-favorites.component.html',
      path: 'src/components/sidebar-15/sidebar-15-nav-favorites.component.html',
      content: `<div z-sidebar-group class="group-data-[collapsible=icon]:hidden">
  <div z-sidebar-group-label>Favorites</div>

  <ul z-sidebar-menu>
    @for (item of favorites(); track item.name) {
      <li z-sidebar-menu-item>
        <a z-sidebar-menu-button [href]="item.url" [title]="item.name">
          <span>{{ item.emoji }}</span>
          <span>{{ item.name }}</span>
        </a>

        <button z-sidebar-menu-action zShowOnHover z-dropdown [zDropdownMenu]="favoriteMenu">
          <ng-icon name="lucideMoreHorizontal" />
          <span class="sr-only">More</span>
        </button>

        <z-dropdown-menu-content
          #favoriteMenu="zDropdownMenuContent"
          class="w-56 rounded-lg"
          [zSide]="menuSide()"
          [zAlign]="menuAlign()"
        >
          <z-dropdown-menu-item>
            <ng-icon name="lucideStarOff" class="text-muted-foreground" />
            <span>Remove from Favorites</span>
          </z-dropdown-menu-item>
          <z-dropdown-menu-separator />
          <z-dropdown-menu-item>
            <ng-icon name="lucideLink" class="text-muted-foreground" />
            <span>Copy Link</span>
          </z-dropdown-menu-item>
          <z-dropdown-menu-item>
            <ng-icon name="lucideArrowUpRight" class="text-muted-foreground" />
            <span>Open in New Tab</span>
          </z-dropdown-menu-item>
          <z-dropdown-menu-separator />
          <z-dropdown-menu-item>
            <ng-icon name="lucideTrash2" class="text-muted-foreground" />
            <span>Delete</span>
          </z-dropdown-menu-item>
        </z-dropdown-menu-content>
      </li>
    }

    <li z-sidebar-menu-item>
      <button z-sidebar-menu-button class="text-sidebar-foreground/70">
        <ng-icon name="lucideMoreHorizontal" />
        <span>More</span>
      </button>
    </li>
  </ul>
</div>
`,
      language: 'html',
    },
    {
      name: 'sidebar-15-nav-favorites.component.ts',
      path: 'src/components/sidebar-15/sidebar-15-nav-favorites.component.ts',
      content: `import { ChangeDetectionStrategy, Component, computed, inject, input } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideArrowUpRight, lucideLink, lucideMoreHorizontal, lucideStarOff, lucideTrash2 } from '@ng-icons/lucide';

import type { ZardDropdownAlign, ZardDropdownSide } from '@zard/components/dropdown/dropdown-positions';
import { ZardDropdownImports } from '@zard/components/dropdown/dropdown.imports';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';
import { ZardSidebarService } from '@zard/components/sidebar/sidebar.service';

export interface Sidebar15Favorite {
  readonly name: string;
  readonly url: string;
  readonly emoji: string;
}

@Component({
  selector: 'lib-sidebar-15-nav-favorites',
  standalone: true,
  imports: [...ZardSidebarImports, ...ZardDropdownImports, NgIcon],
  viewProviders: [provideIcons({ lucideArrowUpRight, lucideLink, lucideMoreHorizontal, lucideStarOff, lucideTrash2 })],
  templateUrl: './sidebar-15-nav-favorites.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Sidebar15NavFavoritesComponent {
  private readonly sidebar = inject(ZardSidebarService);
  /** shadcn opens these menus to the side of the sidebar on desktop and below the trigger on mobile. */
  protected readonly menuSide = computed<ZardDropdownSide>(() => (this.sidebar.isMobile() ? 'bottom' : 'right'));
  protected readonly menuAlign = computed<ZardDropdownAlign>(() => (this.sidebar.isMobile() ? 'end' : 'start'));

  readonly favorites = input<readonly Sidebar15Favorite[]>([]);
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-15-nav-main.component.html',
      path: 'src/components/sidebar-15/sidebar-15-nav-main.component.html',
      content: `<ul z-sidebar-menu>
  @for (item of items(); track item.title) {
    <li z-sidebar-menu-item>
      <a z-sidebar-menu-button [href]="item.url" [zActive]="!!item.isActive">
        <ng-icon [name]="item.icon" />
        <span>{{ item.title }}</span>
      </a>
    </li>
  }
</ul>
`,
      language: 'html',
    },
    {
      name: 'sidebar-15-nav-main.component.ts',
      path: 'src/components/sidebar-15/sidebar-15-nav-main.component.ts',
      content: `import { ChangeDetectionStrategy, Component, input } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideHouse, lucideInbox, lucideSearch, lucideSparkles } from '@ng-icons/lucide';

import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

export interface Sidebar15NavItem {
  readonly title: string;
  readonly url: string;
  readonly icon: string;
  readonly isActive?: boolean;
  readonly badge?: string;
}

@Component({
  selector: 'lib-sidebar-15-nav-main',
  standalone: true,
  imports: [...ZardSidebarImports, NgIcon],
  viewProviders: [provideIcons({ lucideHouse, lucideInbox, lucideSearch, lucideSparkles })],
  templateUrl: './sidebar-15-nav-main.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Sidebar15NavMainComponent {
  readonly items = input<readonly Sidebar15NavItem[]>([]);
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-15-nav-secondary.component.html',
      path: 'src/components/sidebar-15/sidebar-15-nav-secondary.component.html',
      content: `<div z-sidebar-group [class]="class()">
  <div z-sidebar-group-content>
    <ul z-sidebar-menu>
      @for (item of items(); track item.title) {
        <li z-sidebar-menu-item>
          <a z-sidebar-menu-button [href]="item.url">
            <ng-icon [name]="item.icon" />
            <span>{{ item.title }}</span>
          </a>
        </li>
        @if (item.badge) {
          <div z-sidebar-menu-badge>{{ item.badge }}</div>
        }
      }
    </ul>
  </div>
</div>
`,
      language: 'html',
    },
    {
      name: 'sidebar-15-nav-secondary.component.ts',
      path: 'src/components/sidebar-15/sidebar-15-nav-secondary.component.ts',
      content: `import { ChangeDetectionStrategy, Component, input } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import {
  lucideBlocks,
  lucideCalendar,
  lucideMessageCircleQuestion,
  lucideSettings2,
  lucideTrash2,
} from '@ng-icons/lucide';

import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

export interface Sidebar15SecondaryItem {
  readonly title: string;
  readonly url: string;
  readonly icon: string;
  readonly badge?: string;
}

@Component({
  selector: 'lib-sidebar-15-nav-secondary',
  standalone: true,
  imports: [...ZardSidebarImports, NgIcon],
  viewProviders: [
    provideIcons({ lucideBlocks, lucideCalendar, lucideMessageCircleQuestion, lucideSettings2, lucideTrash2 }),
  ],
  templateUrl: './sidebar-15-nav-secondary.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Sidebar15NavSecondaryComponent {
  readonly items = input<readonly Sidebar15SecondaryItem[]>([]);
  readonly class = input<string>('');
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-15-nav-user.component.html',
      path: 'src/components/sidebar-15/sidebar-15-nav-user.component.html',
      content: `<ul z-sidebar-menu>
  <li z-sidebar-menu-item>
    <button
      z-sidebar-menu-button
      zSize="lg"
      z-dropdown
      [zDropdownMenu]="userMenu"
      class="data-[state=open]:bg-sidebar-accent data-[state=open]:text-sidebar-accent-foreground"
    >
      <z-avatar class="size-8 rounded-lg" [zSrc]="user().avatar" [zAlt]="user().name" zFallback="ZU" />

      <div class="grid flex-1 text-left text-sm leading-tight">
        <span class="truncate font-medium">{{ user().name }}</span>
        <span class="truncate text-xs">{{ user().email }}</span>
      </div>

      <ng-icon name="lucideChevronsUpDown" class="ml-auto size-4" />
    </button>

    <z-dropdown-menu-content
      #userMenu="zDropdownMenuContent"
      class="w-(--z-dropdown-menu-trigger-width) min-w-56 rounded-lg"
      [zSide]="menuSide()"
      zAlign="end"
    >
      <z-dropdown-menu-label class="p-0 font-normal">
        <div class="flex items-center gap-2 px-1 py-1.5 text-left text-sm">
          <z-avatar class="size-8 rounded-lg" [zSrc]="user().avatar" [zAlt]="user().name" zFallback="ZU" />

          <div class="grid flex-1 text-left text-sm leading-tight">
            <span class="truncate font-medium">{{ user().name }}</span>
            <span class="truncate text-xs">{{ user().email }}</span>
          </div>
        </div>
      </z-dropdown-menu-label>

      <z-dropdown-menu-separator />

      <z-dropdown-menu-group>
        <z-dropdown-menu-item>
          <ng-icon name="lucideSparkles" />
          Upgrade to Pro
        </z-dropdown-menu-item>
      </z-dropdown-menu-group>

      <z-dropdown-menu-separator />

      <z-dropdown-menu-group>
        <z-dropdown-menu-item>
          <ng-icon name="lucideBadgeCheck" />
          Account
        </z-dropdown-menu-item>
        <z-dropdown-menu-item>
          <ng-icon name="lucideCreditCard" />
          Billing
        </z-dropdown-menu-item>
        <z-dropdown-menu-item>
          <ng-icon name="lucideBell" />
          Notifications
        </z-dropdown-menu-item>
      </z-dropdown-menu-group>

      <z-dropdown-menu-separator />

      <z-dropdown-menu-item>
        <ng-icon name="lucideLogOut" />
        Log out
      </z-dropdown-menu-item>
    </z-dropdown-menu-content>
  </li>
</ul>
`,
      language: 'html',
    },
    {
      name: 'sidebar-15-nav-user.component.ts',
      path: 'src/components/sidebar-15/sidebar-15-nav-user.component.ts',
      content: `import { ChangeDetectionStrategy, Component, computed, inject, input } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import {
  lucideBadgeCheck,
  lucideBell,
  lucideChevronsUpDown,
  lucideCreditCard,
  lucideLogOut,
  lucideSparkles,
} from '@ng-icons/lucide';

import { ZardAvatarComponent } from '@zard/components/avatar/avatar.component';
import type { ZardDropdownSide } from '@zard/components/dropdown/dropdown-positions';
import { ZardDropdownImports } from '@zard/components/dropdown/dropdown.imports';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';
import { ZardSidebarService } from '@zard/components/sidebar/sidebar.service';

export interface Sidebar15User {
  readonly name: string;
  readonly email: string;
  readonly avatar: string;
}

@Component({
  selector: 'lib-sidebar-15-nav-user',
  standalone: true,
  imports: [...ZardSidebarImports, ...ZardDropdownImports, ZardAvatarComponent, NgIcon],
  viewProviders: [
    provideIcons({
      lucideBadgeCheck,
      lucideBell,
      lucideChevronsUpDown,
      lucideCreditCard,
      lucideLogOut,
      lucideSparkles,
    }),
  ],
  templateUrl: './sidebar-15-nav-user.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Sidebar15NavUserComponent {
  private readonly sidebar = inject(ZardSidebarService);
  /** shadcn opens these menus to the side of the sidebar on desktop and below the trigger on mobile. */
  protected readonly menuSide = computed<ZardDropdownSide>(() => (this.sidebar.isMobile() ? 'bottom' : 'right'));

  readonly user = input.required<Sidebar15User>();
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-15-nav-workspaces.component.html',
      path: 'src/components/sidebar-15/sidebar-15-nav-workspaces.component.html',
      content: `<div z-sidebar-group>
  <div z-sidebar-group-label>Workspaces</div>

  <div z-sidebar-group-content>
    <ul z-sidebar-menu>
      @for (workspace of workspaces(); track workspace.name) {
        <li z-sidebar-menu-item z-collapsible>
          <a z-sidebar-menu-button href="#">
            <span>{{ workspace.emoji }}</span>
            <span>{{ workspace.name }}</span>
          </a>

          <button
            z-collapsible-trigger
            z-sidebar-menu-action
            zShowOnHover
            class="bg-sidebar-accent text-sidebar-accent-foreground left-2 data-[state=open]:rotate-90"
          >
            <ng-icon name="lucideChevronRight" />
            <span class="sr-only">Toggle</span>
          </button>

          <button z-sidebar-menu-action zShowOnHover>
            <ng-icon name="lucidePlus" />
            <span class="sr-only">Add page</span>
          </button>

          <z-collapsible-content>
            <ul z-sidebar-menu-sub>
              @for (page of workspace.pages; track page.name) {
                <li z-sidebar-menu-sub-item>
                  <a z-sidebar-menu-sub-button href="#">
                    <span>{{ page.emoji }}</span>
                    <span>{{ page.name }}</span>
                  </a>
                </li>
              }
            </ul>
          </z-collapsible-content>
        </li>
      }

      <li z-sidebar-menu-item>
        <button z-sidebar-menu-button class="text-sidebar-foreground/70">
          <ng-icon name="lucideMoreHorizontal" />
          <span>More</span>
        </button>
      </li>
    </ul>
  </div>
</div>
`,
      language: 'html',
    },
    {
      name: 'sidebar-15-nav-workspaces.component.ts',
      path: 'src/components/sidebar-15/sidebar-15-nav-workspaces.component.ts',
      content: `import { ChangeDetectionStrategy, Component, input } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideChevronRight, lucideMoreHorizontal, lucidePlus } from '@ng-icons/lucide';

import { ZardCollapsibleImports } from '@zard/components/collapsible/collapsible.imports';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

export interface Sidebar15Page {
  readonly name: string;
  readonly emoji: string;
}

export interface Sidebar15Workspace {
  readonly name: string;
  readonly emoji: string;
  readonly pages: readonly Sidebar15Page[];
}

@Component({
  selector: 'lib-sidebar-15-nav-workspaces',
  standalone: true,
  imports: [...ZardSidebarImports, ...ZardCollapsibleImports, NgIcon],
  viewProviders: [provideIcons({ lucideChevronRight, lucideMoreHorizontal, lucidePlus })],
  templateUrl: './sidebar-15-nav-workspaces.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Sidebar15NavWorkspacesComponent {
  readonly workspaces = input<readonly Sidebar15Workspace[]>([]);
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-15-sidebar-left.component.html',
      path: 'src/components/sidebar-15/sidebar-15-sidebar-left.component.html',
      content: `<z-sidebar class="border-r-0">
  <div z-sidebar-header>
    <lib-sidebar-15-team-switcher [teams]="teams" />
    <lib-sidebar-15-nav-main [items]="navMain" />
  </div>

  <z-sidebar-content>
    <lib-sidebar-15-nav-favorites [favorites]="favorites" />
    <lib-sidebar-15-nav-workspaces [workspaces]="workspaces" />
    <lib-sidebar-15-nav-secondary [items]="navSecondary" class="mt-auto" />
  </z-sidebar-content>

  <button z-sidebar-rail aria-label="Toggle Sidebar"></button>
</z-sidebar>
`,
      language: 'html',
    },
    {
      name: 'sidebar-15-sidebar-left.component.ts',
      path: 'src/components/sidebar-15/sidebar-15-sidebar-left.component.ts',
      content: `import { ChangeDetectionStrategy, Component } from '@angular/core';

import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

import { Sidebar15NavFavoritesComponent, type Sidebar15Favorite } from './sidebar-15-nav-favorites.component';
import { Sidebar15NavMainComponent, type Sidebar15NavItem } from './sidebar-15-nav-main.component';
import { Sidebar15NavSecondaryComponent, type Sidebar15SecondaryItem } from './sidebar-15-nav-secondary.component';
import { Sidebar15NavWorkspacesComponent, type Sidebar15Workspace } from './sidebar-15-nav-workspaces.component';
import { Sidebar15TeamSwitcherComponent, type Sidebar15Team } from './sidebar-15-team-switcher.component';

@Component({
  selector: 'lib-sidebar-15-sidebar-left',
  standalone: true,
  imports: [
    ...ZardSidebarImports,
    Sidebar15TeamSwitcherComponent,
    Sidebar15NavMainComponent,
    Sidebar15NavFavoritesComponent,
    Sidebar15NavWorkspacesComponent,
    Sidebar15NavSecondaryComponent,
  ],
  templateUrl: './sidebar-15-sidebar-left.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Sidebar15SidebarLeftComponent {
  // This is sample data.
  protected readonly teams: readonly Sidebar15Team[] = [
    { name: 'Acme Inc', logo: 'lucideCommand', plan: 'Enterprise' },
    { name: 'Acme Corp.', logo: 'lucideAudioWaveform', plan: 'Startup' },
    { name: 'Evil Corp.', logo: 'lucideCommand', plan: 'Free' },
  ];

  protected readonly navMain: readonly Sidebar15NavItem[] = [
    { title: 'Search', url: '#', icon: 'lucideSearch' },
    { title: 'Ask AI', url: '#', icon: 'lucideSparkles' },
    { title: 'Home', url: '#', icon: 'lucideHouse', isActive: true },
    { title: 'Inbox', url: '#', icon: 'lucideInbox', badge: '10' },
  ];

  protected readonly navSecondary: readonly Sidebar15SecondaryItem[] = [
    { title: 'Calendar', url: '#', icon: 'lucideCalendar' },
    { title: 'Settings', url: '#', icon: 'lucideSettings2' },
    { title: 'Templates', url: '#', icon: 'lucideBlocks' },
    { title: 'Trash', url: '#', icon: 'lucideTrash2' },
    { title: 'Help', url: '#', icon: 'lucideMessageCircleQuestion' },
  ];

  protected readonly favorites: readonly Sidebar15Favorite[] = [
    { name: 'Project Management & Task Tracking', url: '#', emoji: '📊' },
    { name: 'Family Recipe Collection & Meal Planning', url: '#', emoji: '🍳' },
    { name: 'Fitness Tracker & Workout Routines', url: '#', emoji: '💪' },
    { name: 'Book Notes & Reading List', url: '#', emoji: '📚' },
    { name: 'Sustainable Gardening Tips & Plant Care', url: '#', emoji: '🌱' },
    { name: 'Language Learning Progress & Resources', url: '#', emoji: '🗣️' },
    { name: 'Home Renovation Ideas & Budget Tracker', url: '#', emoji: '🏠' },
    { name: 'Personal Finance & Investment Portfolio', url: '#', emoji: '💰' },
    { name: 'Movie & TV Show Watchlist with Reviews', url: '#', emoji: '🎬' },
    { name: 'Daily Habit Tracker & Goal Setting', url: '#', emoji: '✅' },
  ];

  protected readonly workspaces: readonly Sidebar15Workspace[] = [
    {
      name: 'Personal Life Management',
      emoji: '🏠',
      pages: [
        { name: 'Daily Journal & Reflection', emoji: '📔' },
        { name: 'Health & Wellness Tracker', emoji: '🍏' },
        { name: 'Personal Growth & Learning Goals', emoji: '🌟' },
      ],
    },
    {
      name: 'Professional Development',
      emoji: '💼',
      pages: [
        { name: 'Career Objectives & Milestones', emoji: '🎯' },
        { name: 'Skill Acquisition & Training Log', emoji: '🧠' },
        { name: 'Networking Contacts & Events', emoji: '🤝' },
      ],
    },
    {
      name: 'Creative Projects',
      emoji: '🎨',
      pages: [
        { name: 'Writing Ideas & Story Outlines', emoji: '✍️' },
        { name: 'Art & Design Portfolio', emoji: '🖼️' },
        { name: 'Music Composition & Practice Log', emoji: '🎵' },
      ],
    },
    {
      name: 'Travel & Adventure',
      emoji: '🌎',
      pages: [
        { name: 'Trip Planning & Itineraries', emoji: '🗺️' },
        { name: 'Travel Bucket List & Inspiration', emoji: '🌎' },
        { name: 'Travel Journal & Photo Gallery', emoji: '📸' },
      ],
    },
  ];
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-15-sidebar-right.component.html',
      path: 'src/components/sidebar-15/sidebar-15-sidebar-right.component.html',
      content: `<z-sidebar zCollapsible="none" class="sticky top-0 hidden h-svh border-l lg:flex">
  <div z-sidebar-header class="border-sidebar-border h-16 border-b">
    <lib-sidebar-15-nav-user [user]="user" />
  </div>

  <z-sidebar-content>
    <lib-sidebar-15-date-picker />
    <z-sidebar-separator class="mx-0" />
    <lib-sidebar-15-calendars [calendars]="calendars" />
  </z-sidebar-content>

  <div z-sidebar-footer>
    <ul z-sidebar-menu>
      <li z-sidebar-menu-item>
        <button z-sidebar-menu-button>
          <ng-icon name="lucidePlus" />
          <span>New Calendar</span>
        </button>
      </li>
    </ul>
  </div>
</z-sidebar>
`,
      language: 'html',
    },
    {
      name: 'sidebar-15-sidebar-right.component.ts',
      path: 'src/components/sidebar-15/sidebar-15-sidebar-right.component.ts',
      content: `import { ChangeDetectionStrategy, Component } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucidePlus } from '@ng-icons/lucide';

import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

import { Sidebar15CalendarsComponent, type Sidebar15Calendar } from './sidebar-15-calendars.component';
import { Sidebar15DatePickerComponent } from './sidebar-15-date-picker.component';
import { Sidebar15NavUserComponent, type Sidebar15User } from './sidebar-15-nav-user.component';

@Component({
  selector: 'lib-sidebar-15-sidebar-right',
  standalone: true,
  imports: [
    ...ZardSidebarImports,
    Sidebar15NavUserComponent,
    Sidebar15DatePickerComponent,
    Sidebar15CalendarsComponent,
    NgIcon,
  ],
  viewProviders: [provideIcons({ lucidePlus })],
  templateUrl: './sidebar-15-sidebar-right.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Sidebar15SidebarRightComponent {
  // This is sample data.
  protected readonly user: Sidebar15User = {
    name: 'zard ui',
    email: 'm@example.com',
    avatar: 'https://github.com/zard-ui.png',
  };

  protected readonly calendars: readonly Sidebar15Calendar[] = [
    { name: 'My Calendars', items: ['Personal', 'Work', 'Family'] },
    { name: 'Favorites', items: ['Holidays', 'Birthdays'] },
    { name: 'Other', items: ['Travel', 'Reminders', 'Deadlines'] },
  ];
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-15-team-switcher.component.html',
      path: 'src/components/sidebar-15/sidebar-15-team-switcher.component.html',
      content: `<ul z-sidebar-menu>
  <li z-sidebar-menu-item>
    <button z-sidebar-menu-button z-dropdown [zDropdownMenu]="teamMenu" class="w-fit px-1.5">
      <div
        class="bg-sidebar-primary text-sidebar-primary-foreground flex aspect-square size-5 items-center justify-center rounded-md"
      >
        <ng-icon [name]="activeTeam()?.logo ?? ''" class="size-3" />
      </div>
      <span class="truncate font-medium">{{ activeTeam()?.name }}</span>
      <ng-icon name="lucideChevronDown" class="opacity-50" />
    </button>

    <z-dropdown-menu-content #teamMenu="zDropdownMenuContent" class="w-64 rounded-lg">
      <z-dropdown-menu-label class="text-muted-foreground text-xs">Teams</z-dropdown-menu-label>

      @for (team of teams(); track team.name; let index = $index) {
        <z-dropdown-menu-item class="gap-2 p-2" (click)="selectedTeam.set(team)">
          <div class="flex size-6 items-center justify-center rounded-xs border">
            <ng-icon [name]="team.logo" class="size-4 shrink-0" />
          </div>
          {{ team.name }}
          <z-dropdown-menu-shortcut>⌘{{ index + 1 }}</z-dropdown-menu-shortcut>
        </z-dropdown-menu-item>
      }

      <z-dropdown-menu-separator />

      <z-dropdown-menu-item class="gap-2 p-2">
        <div class="bg-background flex size-6 items-center justify-center rounded-md border">
          <ng-icon name="lucidePlus" class="size-4" />
        </div>
        <div class="text-muted-foreground font-medium">Add team</div>
      </z-dropdown-menu-item>
    </z-dropdown-menu-content>
  </li>
</ul>
`,
      language: 'html',
    },
    {
      name: 'sidebar-15-team-switcher.component.ts',
      path: 'src/components/sidebar-15/sidebar-15-team-switcher.component.ts',
      content: `import { ChangeDetectionStrategy, Component, input, signal } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideAudioWaveform, lucideChevronDown, lucideCommand, lucidePlus } from '@ng-icons/lucide';

import { ZardDropdownImports } from '@zard/components/dropdown/dropdown.imports';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

export interface Sidebar15Team {
  readonly name: string;
  readonly logo: string;
  readonly plan: string;
}

@Component({
  selector: 'lib-sidebar-15-team-switcher',
  standalone: true,
  imports: [...ZardSidebarImports, ...ZardDropdownImports, NgIcon],
  viewProviders: [provideIcons({ lucideAudioWaveform, lucideChevronDown, lucideCommand, lucidePlus })],
  templateUrl: './sidebar-15-team-switcher.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Sidebar15TeamSwitcherComponent {
  readonly teams = input<readonly Sidebar15Team[]>([]);

  protected readonly selectedTeam = signal<Sidebar15Team | null>(null);

  protected activeTeam(): Sidebar15Team | undefined {
    return this.selectedTeam() ?? this.teams()[0];
  }
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-15.component.html',
      path: 'src/components/sidebar-15/sidebar-15.component.html',
      content: `<z-sidebar-provider>
  <lib-sidebar-15-sidebar-left />

  <main z-sidebar-inset>
    <header class="bg-background sticky top-0 flex h-14 shrink-0 items-center gap-2">
      <div class="flex flex-1 items-center gap-2 px-3">
        <button z-sidebar-trigger aria-label="Toggle Sidebar"></button>

        <z-separator
          zOrientation="vertical"
          class="mr-2 data-[orientation=vertical]:h-4 data-[orientation=vertical]:self-center"
        />

        <z-breadcrumb>
          <z-breadcrumb-item>
            <span z-breadcrumb-page class="line-clamp-1">Project Management &amp; Task Tracking</span>
          </z-breadcrumb-item>
        </z-breadcrumb>
      </div>
    </header>

    <div class="flex flex-1 flex-col gap-4 p-4">
      <div class="bg-muted/50 mx-auto h-24 w-full max-w-3xl rounded-xl"></div>
      <div class="bg-muted/50 mx-auto h-[100vh] w-full max-w-3xl rounded-xl"></div>
    </div>
  </main>

  <lib-sidebar-15-sidebar-right />
</z-sidebar-provider>
`,
      language: 'html',
    },
    {
      name: 'sidebar-15.component.ts',
      path: 'src/components/sidebar-15/sidebar-15.component.ts',
      content: `import { ChangeDetectionStrategy, Component } from '@angular/core';

import { ZardBreadcrumbImports } from '@zard/components/breadcrumb/breadcrumb.imports';
import { ZardSeparatorComponent } from '@zard/components/separator/separator.component';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

import { Sidebar15SidebarLeftComponent } from './sidebar-15-sidebar-left.component';
import { Sidebar15SidebarRightComponent } from './sidebar-15-sidebar-right.component';

@Component({
  selector: 'lib-sidebar-15',
  standalone: true,
  imports: [
    ...ZardSidebarImports,
    ...ZardBreadcrumbImports,
    ZardSeparatorComponent,
    Sidebar15SidebarLeftComponent,
    Sidebar15SidebarRightComponent,
  ],
  templateUrl: './sidebar-15.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Sidebar15Component {}
`,
      language: 'typescript',
    },
  ],
};
