import type { Block } from '@doc/domain/components/block-container/block-container.component';

import { Sidebar15Component } from './sidebar-15.component';

export const sidebar15Block: Block = {
  id: 'sidebar-15',
  title: 'Sidebar 15',
  description: 'A left and right sidebar.',
  component: Sidebar15Component,
  category: 'Sidebar',
  image: {
    light: '/blocks/sidebar-15/light.png',
    dark: '/blocks/sidebar-15/dark.png',
  },
  // Generated by `npm run sync:blocks` from the sibling component files — do not edit by hand.
  files: [
    {
      name: 'sidebar-15.component.html',
      path: 'src/components/sidebar-15/sidebar-15.component.html',
      content: `<div class="flex min-h-screen items-center justify-center">
  <p>Sidebar 15</p>
</div>
`,
      language: 'html',
    },
    {
      name: 'sidebar-15.component.ts',
      path: 'src/components/sidebar-15/sidebar-15.component.ts',
      content: `import { Component } from '@angular/core';

@Component({
  selector: 'lib-sidebar-15',
  standalone: true,
  imports: [],
  templateUrl: './sidebar-15.component.html',
})
export class Sidebar15Component {}
`,
      language: 'typescript',
    },
  ],
};
