import type { Block } from '@doc/domain/components/block-container/block-container.component';

import { Login03Component } from './login-03.component';

export const login03Block: Block = {
  id: 'login-03',
  title: 'Login with muted background',
  description: 'A login page with a muted background color.',
  component: Login03Component,
  category: 'Login',
  image: {
    light: '/blocks/login-03/light.png',
    dark: '/blocks/login-03/dark.png',
  },
  // Generated by `npm run sync:blocks` from the sibling component files — do not edit by hand.
  files: [
    {
      name: 'login-03.component.html',
      path: 'src/components/login-03/login-03.component.html',
      content: `<div class="bg-muted flex min-h-svh flex-col items-center justify-center gap-6 p-6 md:p-10">
  <div class="flex w-full max-w-sm flex-col gap-6">
    <a href="#" class="flex items-center gap-2 self-center font-medium">
      <div class="bg-primary text-primary-foreground flex size-6 items-center justify-center rounded-md">
        <ng-icon name="lucideGalleryVerticalEnd" class="size-4" />
      </div>
      Acme Inc.
    </a>
    <div class="flex flex-col gap-6">
      <z-card>
        <div z-card-header class="text-center">
          <z-card-title zTitle="Welcome back" class="text-xl" />
          <z-card-description zDescription="Login with your Apple or Google account" />
        </div>
        <div z-card-content>
          <form [formGroup]="loginForm" (ngSubmit)="onSubmit()">
            <div z-field-group>
              <div z-field>
                <button z-button zType="outline" type="button">
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                    <path
                      d="M12.152 6.896c-.948 0-2.415-1.078-3.96-1.04-2.04.027-3.91 1.183-4.961 3.014-2.117 3.675-.546 9.103 1.519 12.09 1.013 1.454 2.208 3.09 3.792 3.039 1.52-.065 2.09-.987 3.935-.987 1.831 0 2.35.987 3.96.948 1.637-.026 2.676-1.48 3.676-2.948 1.156-1.688 1.636-3.325 1.662-3.415-.039-.013-3.182-1.221-3.22-4.857-.026-3.04 2.48-4.494 2.597-4.559-1.429-2.09-3.623-2.324-4.39-2.376-2-.156-3.675 1.09-4.61 1.09zM15.53 3.83c.843-1.012 1.4-2.427 1.245-3.83-1.207.052-2.662.805-3.532 1.818-.78.896-1.454 2.338-1.273 3.714 1.338.104 2.715-.688 3.559-1.701"
                      fill="currentColor"
                    />
                  </svg>
                  Login with Apple
                </button>
                <button z-button zType="outline" type="button">
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                    <path
                      d="M12.48 10.92v3.28h7.84c-.24 1.84-.853 3.187-1.787 4.133-1.147 1.147-2.933 2.4-6.053 2.4-4.827 0-8.6-3.893-8.6-8.72s3.773-8.72 8.6-8.72c2.6 0 4.507 1.027 5.907 2.347l2.307-2.307C18.747 1.44 16.133 0 12.48 0 5.867 0 .307 5.387.307 12s5.56 12 12.173 12c3.573 0 6.267-1.173 8.373-3.36 2.16-2.16 2.84-5.213 2.84-7.667 0-.76-.053-1.467-.173-2.053H12.48z"
                      fill="currentColor"
                    />
                  </svg>
                  Login with Google
                </button>
              </div>
              <z-field-separator zContent="Or continue with" class="*:data-[slot=field-separator-content]:bg-card" />
              <div z-field>
                <label z-field-label for="email">Email</label>
                <input z-input id="email" type="email" placeholder="m@example.com" formControlName="email" required />
              </div>
              <div z-field>
                <div class="flex items-center">
                  <label z-field-label for="password">Password</label>
                  <a href="#" class="ml-auto text-sm underline-offset-4 hover:underline">Forgot your password?</a>
                </div>
                <input z-input id="password" type="password" formControlName="password" required />
              </div>
              <div z-field>
                <button z-button type="submit" [zLoading]="isLoading()" [zDisabled]="isLoading()">Login</button>
                <p z-field-description class="text-center">
                  Don't have an account?
                  <a href="#">Sign up</a>
                </p>
              </div>
            </div>
          </form>
        </div>
      </z-card>
      <!-- prettier-ignore -->
      <p z-field-description class="px-6 text-center">
        By clicking continue, you agree to our <a href="#">Terms of Service</a> and <a href="#">Privacy Policy</a>.
      </p>
    </div>
  </div>
</div>
`,
      language: 'html',
    },
    {
      name: 'login-03.component.ts',
      path: 'src/components/login-03/login-03.component.ts',
      content: `import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';

import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideGalleryVerticalEnd } from '@ng-icons/lucide';

import { ZardButtonComponent } from '@zard/components/button/button.component';
import { ZardCardImports } from '@zard/components/card/card.imports';
import { ZardFieldImports } from '@zard/components/field/field.imports';
import { ZardInputComponent } from '@zard/components/input/input.component';

@Component({
  selector: 'lib-login-03',
  imports: [
    ReactiveFormsModule,
    NgIcon,
    ZardButtonComponent,
    ZardInputComponent,
    ...ZardCardImports,
    ...ZardFieldImports,
  ],
  templateUrl: './login-03.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  viewProviders: [provideIcons({ lucideGalleryVerticalEnd })],
})
export class Login03Component {
  protected readonly isLoading = signal(false);

  protected readonly loginForm = new FormGroup({
    email: new FormControl('', [Validators.required, Validators.email]),
    password: new FormControl('', [Validators.required, Validators.minLength(8)]),
  });

  protected onSubmit(): void {
    if (this.loginForm.invalid) {
      this.loginForm.markAllAsTouched();
      return;
    }
    this.isLoading.set(true);
  }
}
`,
      language: 'typescript',
    },
  ],
};
