import type { Block } from '@doc/domain/components/block-container/block-container.component';

import { Sidebar11Component } from './sidebar-11.component';

export const sidebar11Block: Block = {
  id: 'sidebar-11',
  title: 'Sidebar 11',
  description: 'A sidebar with a collapsible file tree.',
  component: Sidebar11Component,
  category: 'Sidebar',
  image: {
    light: '/blocks/sidebar-11/light.png',
    dark: '/blocks/sidebar-11/dark.png',
  },
  // Generated by `npm run sync:blocks` from the sibling component files — do not edit by hand.
  files: [
    {
      name: 'sidebar-11.component.html',
      path: 'src/components/sidebar-11/sidebar-11.component.html',
      content: `<div class="flex min-h-screen items-center justify-center">
  <p>Sidebar 11</p>
</div>
`,
      language: 'html',
    },
    {
      name: 'sidebar-11.component.ts',
      path: 'src/components/sidebar-11/sidebar-11.component.ts',
      content: `import { Component } from '@angular/core';

@Component({
  selector: 'lib-sidebar-11',
  standalone: true,
  imports: [],
  templateUrl: './sidebar-11.component.html',
})
export class Sidebar11Component {}
`,
      language: 'typescript',
    },
  ],
};
