import type { Block } from '@doc/domain/components/block-container/block-container.component';

import { Sidebar11Component } from './sidebar-11.component';

export const sidebar11Block: Block = {
  id: 'sidebar-11',
  title: 'Sidebar 11',
  description: 'A sidebar with a collapsible file tree.',
  component: Sidebar11Component,
  category: 'Sidebar',
  image: {
    light: '/blocks/sidebar-11/light.png',
    dark: '/blocks/sidebar-11/dark.png',
  },
  // Generated by `npm run sync:blocks` from the sibling component files — do not edit by hand.
  files: [
    {
      name: 'sidebar-11-app-sidebar.component.html',
      path: 'src/components/sidebar-11/sidebar-11-app-sidebar.component.html',
      content: `<z-sidebar>
  <z-sidebar-content>
    <div z-sidebar-group>
      <div z-sidebar-group-label>Changes</div>

      <div z-sidebar-group-content>
        <ul z-sidebar-menu>
          @for (item of changes; track item.file) {
            <li z-sidebar-menu-item>
              <button z-sidebar-menu-button>
                <ng-icon name="lucideFile" />
                {{ item.file }}
              </button>
              <div z-sidebar-menu-badge>{{ item.state }}</div>
            </li>
          }
        </ul>
      </div>
    </div>

    <div z-sidebar-group>
      <div z-sidebar-group-label>Files</div>

      <div z-sidebar-group-content>
        <ul z-sidebar-menu>
          @for (node of tree; track node.name) {
            <ng-container [ngTemplateOutlet]="treeNode" [ngTemplateOutletContext]="{ $implicit: node }" />
          }
        </ul>
      </div>
    </div>
  </z-sidebar-content>

  <button z-sidebar-rail aria-label="Toggle Sidebar"></button>
</z-sidebar>

<!-- Recursive template: Angular's answer to shadcn's self-referencing <Tree /> component. -->
<ng-template #treeNode let-node>
  @if (!node.children) {
    <button z-sidebar-menu-button class="data-[active=true]:bg-transparent" [zActive]="node.name === 'button.tsx'">
      <ng-icon name="lucideFile" />
      {{ node.name }}
    </button>
  } @else {
    <li z-sidebar-menu-item>
      <div
        z-collapsible
        class="group/collapsible [&[data-state=open]>button>ng-icon:first-child]:rotate-90"
        [zOpen]="isOpenByDefault(node)"
      >
        <button z-collapsible-trigger z-sidebar-menu-button>
          <ng-icon name="lucideChevronRight" class="transition-transform" />
          <ng-icon name="lucideFolder" />
          {{ node.name }}
        </button>

        <z-collapsible-content>
          <ul z-sidebar-menu-sub>
            @for (child of node.children; track child.name) {
              <ng-container [ngTemplateOutlet]="treeNode" [ngTemplateOutletContext]="{ $implicit: child }" />
            }
          </ul>
        </z-collapsible-content>
      </div>
    </li>
  }
</ng-template>
`,
      language: 'html',
    },
    {
      name: 'sidebar-11-app-sidebar.component.ts',
      path: 'src/components/sidebar-11/sidebar-11-app-sidebar.component.ts',
      content: `import { NgTemplateOutlet } from '@angular/common';
import { ChangeDetectionStrategy, Component } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideChevronRight, lucideFile, lucideFolder } from '@ng-icons/lucide';

import { ZardCollapsibleImports } from '@zard/components/collapsible/collapsible.imports';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

interface Change {
  readonly file: string;
  readonly state: string;
}

/** shadcn models the tree as nested arrays; a typed node keeps the recursive template readable. */
interface TreeNode {
  readonly name: string;
  readonly children?: readonly TreeNode[];
}

const file = (name: string): TreeNode => ({ name });
const folder = (name: string, children: readonly TreeNode[]): TreeNode => ({ name, children });

@Component({
  selector: 'lib-sidebar-11-app-sidebar',
  standalone: true,
  imports: [...ZardSidebarImports, ...ZardCollapsibleImports, NgTemplateOutlet, NgIcon],
  viewProviders: [provideIcons({ lucideChevronRight, lucideFile, lucideFolder })],
  templateUrl: './sidebar-11-app-sidebar.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Sidebar11AppSidebarComponent {
  // This is sample data.
  protected readonly changes: readonly Change[] = [
    { file: 'README.md', state: 'M' },
    { file: 'api/hello/route.ts', state: 'U' },
    { file: 'app/layout.tsx', state: 'M' },
  ];

  protected readonly tree: readonly TreeNode[] = [
    folder('app', [
      folder('api', [folder('hello', [file('route.ts')])]),
      file('page.tsx'),
      file('layout.tsx'),
      folder('blog', [file('page.tsx')]),
    ]),
    folder('components', [
      folder('ui', [file('button.tsx'), file('card.tsx')]),
      file('header.tsx'),
      file('footer.tsx'),
    ]),
    folder('lib', [file('util.ts')]),
    folder('public', [file('favicon.ico'), file('vercel.svg')]),
    file('.eslintrc.json'),
    file('.gitignore'),
    file('next.config.js'),
    file('tailwind.config.js'),
    file('package.json'),
    file('README.md'),
  ];

  protected isOpenByDefault(node: TreeNode): boolean {
    return node.name === 'components' || node.name === 'ui';
  }
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-11.component.html',
      path: 'src/components/sidebar-11/sidebar-11.component.html',
      content: `<z-sidebar-provider>
  <lib-sidebar-11-app-sidebar />

  <main z-sidebar-inset>
    <header class="flex h-16 shrink-0 items-center gap-2 border-b px-4">
      <button z-sidebar-trigger class="-ml-1" aria-label="Toggle Sidebar"></button>

      <z-separator zOrientation="vertical" class="mr-2 data-[orientation=vertical]:h-4" />

      <z-breadcrumb>
        <z-breadcrumb-item class="hidden md:block">
          <a z-breadcrumb-link href="#">components</a>
        </z-breadcrumb-item>
        <z-breadcrumb-separator class="hidden md:block" />
        <z-breadcrumb-item class="hidden md:block">
          <a z-breadcrumb-link href="#">ui</a>
        </z-breadcrumb-item>
        <z-breadcrumb-separator class="hidden md:block" />
        <z-breadcrumb-item>
          <span z-breadcrumb-page>button.tsx</span>
        </z-breadcrumb-item>
      </z-breadcrumb>
    </header>

    <div class="flex flex-1 flex-col gap-4 p-4">
      <div class="grid auto-rows-min gap-4 md:grid-cols-3">
        <div class="bg-muted/50 aspect-video rounded-xl"></div>
        <div class="bg-muted/50 aspect-video rounded-xl"></div>
        <div class="bg-muted/50 aspect-video rounded-xl"></div>
      </div>
      <div class="bg-muted/50 min-h-[100vh] flex-1 rounded-xl md:min-h-min"></div>
    </div>
  </main>
</z-sidebar-provider>
`,
      language: 'html',
    },
    {
      name: 'sidebar-11.component.ts',
      path: 'src/components/sidebar-11/sidebar-11.component.ts',
      content: `import { ChangeDetectionStrategy, Component } from '@angular/core';

import { ZardBreadcrumbImports } from '@zard/components/breadcrumb/breadcrumb.imports';
import { ZardSeparatorComponent } from '@zard/components/separator/separator.component';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

import { Sidebar11AppSidebarComponent } from './sidebar-11-app-sidebar.component';

@Component({
  selector: 'lib-sidebar-11',
  standalone: true,
  imports: [...ZardSidebarImports, ...ZardBreadcrumbImports, ZardSeparatorComponent, Sidebar11AppSidebarComponent],
  templateUrl: './sidebar-11.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Sidebar11Component {}
`,
      language: 'typescript',
    },
  ],
};
