import type { Block } from '@doc/domain/components/block-container/block-container.component';

import { Sidebar16Component } from './sidebar-16.component';

export const sidebar16Block: Block = {
  id: 'sidebar-16',
  title: 'Sidebar 16',
  description: 'A sidebar with a sticky site header.',
  component: Sidebar16Component,
  category: 'Sidebar',
  image: {
    light: '/blocks/sidebar-16/light.png',
    dark: '/blocks/sidebar-16/dark.png',
  },
  // Generated by `npm run sync:blocks` from the sibling component files — do not edit by hand.
  files: [
    {
      name: 'sidebar-16.component.html',
      path: 'src/components/sidebar-16/sidebar-16.component.html',
      content: `<div class="flex min-h-screen items-center justify-center">
  <p>Sidebar 16</p>
</div>
`,
      language: 'html',
    },
    {
      name: 'sidebar-16.component.ts',
      path: 'src/components/sidebar-16/sidebar-16.component.ts',
      content: `import { Component } from '@angular/core';

@Component({
  selector: 'lib-sidebar-16',
  standalone: true,
  imports: [],
  templateUrl: './sidebar-16.component.html',
})
export class Sidebar16Component {}
`,
      language: 'typescript',
    },
  ],
};
