import type { Block } from '@doc/domain/components/block-container/block-container.component';

import { Sidebar16Component } from './sidebar-16.component';

export const sidebar16Block: Block = {
  id: 'sidebar-16',
  title: 'Sidebar 16',
  description: 'A sidebar with a sticky site header.',
  component: Sidebar16Component,
  category: 'Sidebar',
  image: {
    light: '/blocks/sidebar-16/light.png',
    dark: '/blocks/sidebar-16/dark.png',
  },
  // Generated by `npm run sync:blocks` from the sibling component files — do not edit by hand.
  files: [
    {
      name: 'sidebar-16-nav-main.component.html',
      path: 'src/components/sidebar-16/sidebar-16-nav-main.component.html',
      content: `<div z-sidebar-group>
  <div z-sidebar-group-label>Platform</div>

  <ul z-sidebar-menu>
    @for (item of items(); track item.title) {
      <li z-sidebar-menu-item z-collapsible [zOpen]="!!item.isActive">
        <a z-sidebar-menu-button [href]="item.url" [zTooltip]="item.title">
          <ng-icon [name]="item.icon" />
          <span>{{ item.title }}</span>
        </a>

        @if (item.items.length) {
          <button z-collapsible-trigger z-sidebar-menu-action class="data-[state=open]:rotate-90">
            <ng-icon name="lucideChevronRight" />
            <span class="sr-only">Toggle</span>
          </button>

          <z-collapsible-content>
            <ul z-sidebar-menu-sub>
              @for (subItem of item.items; track subItem.title) {
                <li z-sidebar-menu-sub-item>
                  <a z-sidebar-menu-sub-button [href]="subItem.url">
                    <span>{{ subItem.title }}</span>
                  </a>
                </li>
              }
            </ul>
          </z-collapsible-content>
        }
      </li>
    }
  </ul>
</div>
`,
      language: 'html',
    },
    {
      name: 'sidebar-16-nav-main.component.ts',
      path: 'src/components/sidebar-16/sidebar-16-nav-main.component.ts',
      content: `import { ChangeDetectionStrategy, Component, input } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideBookOpen, lucideBot, lucideChevronRight, lucideSettings2, lucideSquareTerminal } from '@ng-icons/lucide';

import { ZardCollapsibleImports } from '@zard/components/collapsible/collapsible.imports';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

export interface Sidebar16NavSubItem {
  readonly title: string;
  readonly url: string;
}

export interface Sidebar16NavItem {
  readonly title: string;
  readonly url: string;
  readonly icon: string;
  readonly isActive?: boolean;
  readonly items: readonly Sidebar16NavSubItem[];
}

@Component({
  selector: 'lib-sidebar-16-nav-main',
  standalone: true,
  imports: [...ZardSidebarImports, ...ZardCollapsibleImports, NgIcon],
  viewProviders: [
    provideIcons({ lucideBookOpen, lucideBot, lucideChevronRight, lucideSettings2, lucideSquareTerminal }),
  ],
  templateUrl: './sidebar-16-nav-main.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Sidebar16NavMainComponent {
  readonly items = input<readonly Sidebar16NavItem[]>([]);
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-16-nav-projects.component.html',
      path: 'src/components/sidebar-16/sidebar-16-nav-projects.component.html',
      content: `<div z-sidebar-group class="group-data-[collapsible=icon]:hidden">
  <div z-sidebar-group-label>Projects</div>

  <ul z-sidebar-menu>
    @for (item of projects(); track item.name) {
      <li z-sidebar-menu-item>
        <a z-sidebar-menu-button [href]="item.url">
          <ng-icon [name]="item.icon" />
          <span>{{ item.name }}</span>
        </a>

        <button z-sidebar-menu-action zShowOnHover z-dropdown [zDropdownMenu]="projectMenu">
          <ng-icon name="lucideMoreHorizontal" />
          <span class="sr-only">More</span>
        </button>

        <z-dropdown-menu-content #projectMenu="zDropdownMenuContent" class="w-48 rounded-lg">
          <z-dropdown-menu-item>
            <ng-icon name="lucideFolder" class="text-muted-foreground" />
            <span>View Project</span>
          </z-dropdown-menu-item>
          <z-dropdown-menu-item>
            <ng-icon name="lucideForward" class="text-muted-foreground" />
            <span>Share Project</span>
          </z-dropdown-menu-item>
          <z-dropdown-menu-separator />
          <z-dropdown-menu-item>
            <ng-icon name="lucideTrash2" class="text-muted-foreground" />
            <span>Delete Project</span>
          </z-dropdown-menu-item>
        </z-dropdown-menu-content>
      </li>
    }

    <li z-sidebar-menu-item>
      <button z-sidebar-menu-button class="text-sidebar-foreground/70">
        <ng-icon name="lucideMoreHorizontal" class="text-sidebar-foreground/70" />
        <span>More</span>
      </button>
    </li>
  </ul>
</div>
`,
      language: 'html',
    },
    {
      name: 'sidebar-16-nav-projects.component.ts',
      path: 'src/components/sidebar-16/sidebar-16-nav-projects.component.ts',
      content: `import { ChangeDetectionStrategy, Component, input } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import {
  lucideFolder,
  lucideForward,
  lucideFrame,
  lucideMap,
  lucideMoreHorizontal,
  lucidePieChart,
  lucideTrash2,
} from '@ng-icons/lucide';

import { ZardDropdownImports } from '@zard/components/dropdown/dropdown.imports';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

export interface Sidebar16Project {
  readonly name: string;
  readonly url: string;
  readonly icon: string;
}

@Component({
  selector: 'lib-sidebar-16-nav-projects',
  standalone: true,
  imports: [...ZardSidebarImports, ...ZardDropdownImports, NgIcon],
  viewProviders: [
    provideIcons({
      lucideFolder,
      lucideForward,
      lucideFrame,
      lucideMap,
      lucideMoreHorizontal,
      lucidePieChart,
      lucideTrash2,
    }),
  ],
  templateUrl: './sidebar-16-nav-projects.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Sidebar16NavProjectsComponent {
  readonly projects = input<readonly Sidebar16Project[]>([]);
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-16-nav-secondary.component.html',
      path: 'src/components/sidebar-16/sidebar-16-nav-secondary.component.html',
      content: `<div z-sidebar-group [class]="class()">
  <div z-sidebar-group-content>
    <ul z-sidebar-menu>
      @for (item of items(); track item.title) {
        <li z-sidebar-menu-item>
          <a z-sidebar-menu-button zSize="sm" [href]="item.url">
            <ng-icon [name]="item.icon" />
            <span>{{ item.title }}</span>
          </a>
        </li>
      }
    </ul>
  </div>
</div>
`,
      language: 'html',
    },
    {
      name: 'sidebar-16-nav-secondary.component.ts',
      path: 'src/components/sidebar-16/sidebar-16-nav-secondary.component.ts',
      content: `import { ChangeDetectionStrategy, Component, input } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideLifeBuoy, lucideSend } from '@ng-icons/lucide';

import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

export interface Sidebar16SecondaryItem {
  readonly title: string;
  readonly url: string;
  readonly icon: string;
}

@Component({
  selector: 'lib-sidebar-16-nav-secondary',
  standalone: true,
  imports: [...ZardSidebarImports, NgIcon],
  viewProviders: [provideIcons({ lucideLifeBuoy, lucideSend })],
  templateUrl: './sidebar-16-nav-secondary.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Sidebar16NavSecondaryComponent {
  readonly items = input<readonly Sidebar16SecondaryItem[]>([]);
  readonly class = input<string>('');
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-16-nav-user.component.html',
      path: 'src/components/sidebar-16/sidebar-16-nav-user.component.html',
      content: `<ul z-sidebar-menu>
  <li z-sidebar-menu-item>
    <button
      z-sidebar-menu-button
      zSize="lg"
      z-dropdown
      [zDropdownMenu]="userMenu"
      class="data-[state=open]:bg-sidebar-accent data-[state=open]:text-sidebar-accent-foreground"
    >
      <z-avatar class="size-8 rounded-lg" [zSrc]="user().avatar" [zAlt]="user().name" zFallback="CN" />

      <div class="grid flex-1 text-left text-sm leading-tight">
        <span class="truncate font-medium">{{ user().name }}</span>
        <span class="truncate text-xs">{{ user().email }}</span>
      </div>

      <ng-icon name="lucideChevronsUpDown" class="ml-auto size-4" />
    </button>

    <z-dropdown-menu-content #userMenu="zDropdownMenuContent" class="w-(--sidebar-width) min-w-56 rounded-lg">
      <z-dropdown-menu-label class="p-0 font-normal">
        <div class="flex items-center gap-2 px-1 py-1.5 text-left text-sm">
          <z-avatar class="size-8 rounded-lg" [zSrc]="user().avatar" [zAlt]="user().name" zFallback="CN" />

          <div class="grid flex-1 text-left text-sm leading-tight">
            <span class="truncate font-medium">{{ user().name }}</span>
            <span class="truncate text-xs">{{ user().email }}</span>
          </div>
        </div>
      </z-dropdown-menu-label>

      <z-dropdown-menu-separator />

      <z-dropdown-menu-group>
        <z-dropdown-menu-item>
          <ng-icon name="lucideSparkles" />
          Upgrade to Pro
        </z-dropdown-menu-item>
      </z-dropdown-menu-group>

      <z-dropdown-menu-separator />

      <z-dropdown-menu-group>
        <z-dropdown-menu-item>
          <ng-icon name="lucideBadgeCheck" />
          Account
        </z-dropdown-menu-item>
        <z-dropdown-menu-item>
          <ng-icon name="lucideCreditCard" />
          Billing
        </z-dropdown-menu-item>
        <z-dropdown-menu-item>
          <ng-icon name="lucideBell" />
          Notifications
        </z-dropdown-menu-item>
      </z-dropdown-menu-group>

      <z-dropdown-menu-separator />

      <z-dropdown-menu-item>
        <ng-icon name="lucideLogOut" />
        Log out
      </z-dropdown-menu-item>
    </z-dropdown-menu-content>
  </li>
</ul>
`,
      language: 'html',
    },
    {
      name: 'sidebar-16-nav-user.component.ts',
      path: 'src/components/sidebar-16/sidebar-16-nav-user.component.ts',
      content: `import { ChangeDetectionStrategy, Component, input } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import {
  lucideBadgeCheck,
  lucideBell,
  lucideChevronsUpDown,
  lucideCreditCard,
  lucideLogOut,
  lucideSparkles,
} from '@ng-icons/lucide';

import { ZardAvatarComponent } from '@zard/components/avatar/avatar.component';
import { ZardDropdownImports } from '@zard/components/dropdown/dropdown.imports';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

export interface Sidebar16User {
  readonly name: string;
  readonly email: string;
  readonly avatar: string;
}

@Component({
  selector: 'lib-sidebar-16-nav-user',
  standalone: true,
  imports: [...ZardSidebarImports, ...ZardDropdownImports, ZardAvatarComponent, NgIcon],
  viewProviders: [
    provideIcons({
      lucideBadgeCheck,
      lucideBell,
      lucideChevronsUpDown,
      lucideCreditCard,
      lucideLogOut,
      lucideSparkles,
    }),
  ],
  templateUrl: './sidebar-16-nav-user.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Sidebar16NavUserComponent {
  readonly user = input.required<Sidebar16User>();
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-16-search-form.component.html',
      path: 'src/components/sidebar-16/sidebar-16-search-form.component.html',
      content: `<form [class]="class()">
  <div class="relative">
    <label z-field-label for="search" class="sr-only">Search</label>

    <input z-input z-sidebar-input id="search" placeholder="Type to search..." class="h-8 pl-7" />

    <ng-icon
      name="lucideSearch"
      class="pointer-events-none absolute top-1/2 left-2 size-4 -translate-y-1/2 opacity-50 select-none"
    />
  </div>
</form>
`,
      language: 'html',
    },
    {
      name: 'sidebar-16-search-form.component.ts',
      path: 'src/components/sidebar-16/sidebar-16-search-form.component.ts',
      content: `import { ChangeDetectionStrategy, Component, input } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideSearch } from '@ng-icons/lucide';

import { ZardFieldImports } from '@zard/components/field/field.imports';
import { ZardInputComponent } from '@zard/components/input/input.component';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

@Component({
  selector: 'lib-sidebar-16-search-form',
  standalone: true,
  imports: [...ZardSidebarImports, ...ZardFieldImports, ZardInputComponent, NgIcon],
  viewProviders: [provideIcons({ lucideSearch })],
  templateUrl: './sidebar-16-search-form.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Sidebar16SearchFormComponent {
  readonly class = input<string>('');
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-16-site-header.component.html',
      path: 'src/components/sidebar-16/sidebar-16-site-header.component.html',
      content: `<header class="bg-background sticky top-0 z-50 flex w-full items-center border-b">
  <div class="flex h-(--header-height) w-full items-center gap-2 px-4">
    <button
      z-button
      zType="ghost"
      zSize="icon"
      class="h-8 w-8"
      aria-label="Toggle Sidebar"
      (click)="sidebar.toggleSidebar()"
    >
      <ng-icon name="lucidePanelLeft" />
    </button>

    <z-separator zOrientation="vertical" class="mr-2 h-4" />

    <z-breadcrumb class="hidden sm:block">
      <z-breadcrumb-item>
        <a z-breadcrumb-link href="#">Build Your Application</a>
      </z-breadcrumb-item>
      <z-breadcrumb-separator />
      <z-breadcrumb-item>
        <span z-breadcrumb-page>Data Fetching</span>
      </z-breadcrumb-item>
    </z-breadcrumb>

    <lib-sidebar-16-search-form class="w-full sm:ml-auto sm:w-auto" />
  </div>
</header>
`,
      language: 'html',
    },
    {
      name: 'sidebar-16-site-header.component.ts',
      path: 'src/components/sidebar-16/sidebar-16-site-header.component.ts',
      content: `import { ChangeDetectionStrategy, Component, inject } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucidePanelLeft } from '@ng-icons/lucide';

import { ZardBreadcrumbImports } from '@zard/components/breadcrumb/breadcrumb.imports';
import { ZardButtonComponent } from '@zard/components/button/button.component';
import { ZardSeparatorComponent } from '@zard/components/separator/separator.component';
import { ZardSidebarService } from '@zard/components/sidebar/sidebar.service';

import { Sidebar16SearchFormComponent } from './sidebar-16-search-form.component';

@Component({
  selector: 'lib-sidebar-16-site-header',
  standalone: true,
  imports: [
    ...ZardBreadcrumbImports,
    ZardButtonComponent,
    ZardSeparatorComponent,
    Sidebar16SearchFormComponent,
    NgIcon,
  ],
  viewProviders: [provideIcons({ lucidePanelLeft })],
  templateUrl: './sidebar-16-site-header.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Sidebar16SiteHeaderComponent {
  protected readonly sidebar = inject(ZardSidebarService);
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-16.component.html',
      path: 'src/components/sidebar-16/sidebar-16.component.html',
      content: `<div class="[--header-height:calc(--spacing(14))]">
  <z-sidebar-provider class="flex-col">
    <lib-sidebar-16-site-header />

    <div class="flex flex-1">
      <z-sidebar class="top-(--header-height) h-[calc(100svh-var(--header-height))]!">
        <div z-sidebar-header>
          <ul z-sidebar-menu>
            <li z-sidebar-menu-item>
              <a z-sidebar-menu-button zSize="lg" href="#">
                <div
                  class="bg-sidebar-primary text-sidebar-primary-foreground flex aspect-square size-8 items-center justify-center rounded-lg"
                >
                  <ng-icon name="lucideCommand" class="size-4" />
                </div>
                <div class="grid flex-1 text-left text-sm leading-tight">
                  <span class="truncate font-medium">Acme Inc</span>
                  <span class="truncate text-xs">Enterprise</span>
                </div>
              </a>
            </li>
          </ul>
        </div>

        <z-sidebar-content>
          <lib-sidebar-16-nav-main [items]="navMain" />
          <lib-sidebar-16-nav-projects [projects]="projects" />
          <lib-sidebar-16-nav-secondary [items]="navSecondary" class="mt-auto" />
        </z-sidebar-content>

        <div z-sidebar-footer>
          <lib-sidebar-16-nav-user [user]="user" />
        </div>
      </z-sidebar>

      <main z-sidebar-inset>
        <div class="flex flex-1 flex-col gap-4 p-4">
          <div class="grid auto-rows-min gap-4 md:grid-cols-3">
            <div class="bg-muted/50 aspect-video rounded-xl"></div>
            <div class="bg-muted/50 aspect-video rounded-xl"></div>
            <div class="bg-muted/50 aspect-video rounded-xl"></div>
          </div>
          <div class="bg-muted/50 min-h-[100vh] flex-1 rounded-xl md:min-h-min"></div>
        </div>
      </main>
    </div>
  </z-sidebar-provider>
</div>
`,
      language: 'html',
    },
    {
      name: 'sidebar-16.component.ts',
      path: 'src/components/sidebar-16/sidebar-16.component.ts',
      content: `import { ChangeDetectionStrategy, Component } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideCommand } from '@ng-icons/lucide';

import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

import { Sidebar16NavMainComponent, type Sidebar16NavItem } from './sidebar-16-nav-main.component';
import { Sidebar16NavProjectsComponent, type Sidebar16Project } from './sidebar-16-nav-projects.component';
import { Sidebar16NavSecondaryComponent, type Sidebar16SecondaryItem } from './sidebar-16-nav-secondary.component';
import { Sidebar16NavUserComponent, type Sidebar16User } from './sidebar-16-nav-user.component';
import { Sidebar16SiteHeaderComponent } from './sidebar-16-site-header.component';

@Component({
  selector: 'lib-sidebar-16',
  standalone: true,
  imports: [
    ...ZardSidebarImports,
    Sidebar16NavMainComponent,
    Sidebar16NavProjectsComponent,
    Sidebar16NavSecondaryComponent,
    Sidebar16NavUserComponent,
    Sidebar16SiteHeaderComponent,
    NgIcon,
  ],
  viewProviders: [provideIcons({ lucideCommand })],
  templateUrl: './sidebar-16.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Sidebar16Component {
  // This is sample data.
  protected readonly user: Sidebar16User = {
    name: 'shadcn',
    email: 'm@example.com',
    avatar: 'https://github.com/shadcn.png',
  };

  protected readonly navMain: readonly Sidebar16NavItem[] = [
    {
      title: 'Playground',
      url: '#',
      icon: 'lucideSquareTerminal',
      isActive: true,
      items: [
        { title: 'History', url: '#' },
        { title: 'Starred', url: '#' },
        { title: 'Settings', url: '#' },
      ],
    },
    {
      title: 'Models',
      url: '#',
      icon: 'lucideBot',
      items: [
        { title: 'Genesis', url: '#' },
        { title: 'Explorer', url: '#' },
        { title: 'Quantum', url: '#' },
      ],
    },
    {
      title: 'Documentation',
      url: '#',
      icon: 'lucideBookOpen',
      items: [
        { title: 'Introduction', url: '#' },
        { title: 'Get Started', url: '#' },
        { title: 'Tutorials', url: '#' },
        { title: 'Changelog', url: '#' },
      ],
    },
    {
      title: 'Settings',
      url: '#',
      icon: 'lucideSettings2',
      items: [
        { title: 'General', url: '#' },
        { title: 'Team', url: '#' },
        { title: 'Billing', url: '#' },
        { title: 'Limits', url: '#' },
      ],
    },
  ];

  protected readonly navSecondary: readonly Sidebar16SecondaryItem[] = [
    { title: 'Support', url: '#', icon: 'lucideLifeBuoy' },
    { title: 'Feedback', url: '#', icon: 'lucideSend' },
  ];

  protected readonly projects: readonly Sidebar16Project[] = [
    { name: 'Design Engineering', url: '#', icon: 'lucideFrame' },
    { name: 'Sales & Marketing', url: '#', icon: 'lucidePieChart' },
    { name: 'Travel', url: '#', icon: 'lucideMap' },
  ];
}
`,
      language: 'typescript',
    },
  ],
};
