import type { Block } from '@doc/domain/components/block-container/block-container.component';

import { Sidebar07Component } from './sidebar-07.component';

export const sidebar07Block: Block = {
  id: 'sidebar-07',
  title: 'Sidebar 07',
  description: 'A sidebar that collapses to icons.',
  component: Sidebar07Component,
  category: 'Sidebar',
  image: {
    light: '/blocks/sidebar-07/light.png',
    dark: '/blocks/sidebar-07/dark.png',
  },
  // Generated by `npm run sync:blocks` from the sibling component files — do not edit by hand.
  files: [
    {
      name: 'sidebar-07.component.html',
      path: 'src/components/sidebar-07/sidebar-07.component.html',
      content: `<div class="flex min-h-screen items-center justify-center">
  <p>Sidebar 07</p>
</div>
`,
      language: 'html',
    },
    {
      name: 'sidebar-07.component.ts',
      path: 'src/components/sidebar-07/sidebar-07.component.ts',
      content: `import { Component } from '@angular/core';

@Component({
  selector: 'lib-sidebar-07',
  standalone: true,
  imports: [],
  templateUrl: './sidebar-07.component.html',
})
export class Sidebar07Component {}
`,
      language: 'typescript',
    },
  ],
};
