import type { Block } from '@doc/domain/components/block-container/block-container.component';

import { Sidebar07Component } from './sidebar-07.component';

export const sidebar07Block: Block = {
  id: 'sidebar-07',
  title: 'Sidebar 07',
  description: 'A sidebar that collapses to icons.',
  component: Sidebar07Component,
  category: 'Sidebar',
  image: {
    light: '/blocks/sidebar-07/light.png',
    dark: '/blocks/sidebar-07/dark.png',
  },
  // Generated by `npm run sync:blocks` from the sibling component files — do not edit by hand.
  files: [
    {
      name: 'sidebar-07-app-sidebar.component.html',
      path: 'src/components/sidebar-07/sidebar-07-app-sidebar.component.html',
      content: `<z-sidebar zCollapsible="icon">
  <div z-sidebar-header>
    <lib-sidebar-07-team-switcher [teams]="teams" />
  </div>

  <z-sidebar-content>
    <lib-sidebar-07-nav-main [items]="navMain" />
    <lib-sidebar-07-nav-projects [projects]="projects" />
  </z-sidebar-content>

  <div z-sidebar-footer>
    <lib-sidebar-07-nav-user [user]="user" />
  </div>

  <button z-sidebar-rail aria-label="Toggle Sidebar"></button>
</z-sidebar>
`,
      language: 'html',
    },
    {
      name: 'sidebar-07-app-sidebar.component.ts',
      path: 'src/components/sidebar-07/sidebar-07-app-sidebar.component.ts',
      content: `import { ChangeDetectionStrategy, Component } from '@angular/core';

import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

import { Sidebar07NavMainComponent, type Sidebar07NavItem } from './sidebar-07-nav-main.component';
import { Sidebar07NavProjectsComponent, type Sidebar07Project } from './sidebar-07-nav-projects.component';
import { Sidebar07NavUserComponent, type Sidebar07User } from './sidebar-07-nav-user.component';
import { Sidebar07TeamSwitcherComponent, type Sidebar07Team } from './sidebar-07-team-switcher.component';

@Component({
  selector: 'lib-sidebar-07-app-sidebar',
  standalone: true,
  imports: [
    ...ZardSidebarImports,
    Sidebar07TeamSwitcherComponent,
    Sidebar07NavMainComponent,
    Sidebar07NavProjectsComponent,
    Sidebar07NavUserComponent,
  ],
  templateUrl: './sidebar-07-app-sidebar.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Sidebar07AppSidebarComponent {
  // This is sample data.
  protected readonly user: Sidebar07User = {
    name: 'zard ui',
    email: 'm@example.com',
    avatar: 'https://github.com/zard-ui.png',
  };

  protected readonly teams: readonly Sidebar07Team[] = [
    { name: 'Acme Inc', logo: 'lucideGalleryVerticalEnd', plan: 'Enterprise' },
    { name: 'Acme Corp.', logo: 'lucideAudioWaveform', plan: 'Startup' },
    { name: 'Evil Corp.', logo: 'lucideCommand', plan: 'Free' },
  ];

  protected readonly navMain: readonly Sidebar07NavItem[] = [
    {
      title: 'Playground',
      url: '#',
      icon: 'lucideSquareTerminal',
      isActive: true,
      items: [
        { title: 'History', url: '#' },
        { title: 'Starred', url: '#' },
        { title: 'Settings', url: '#' },
      ],
    },
    {
      title: 'Models',
      url: '#',
      icon: 'lucideBot',
      items: [
        { title: 'Genesis', url: '#' },
        { title: 'Explorer', url: '#' },
        { title: 'Quantum', url: '#' },
      ],
    },
    {
      title: 'Documentation',
      url: '#',
      icon: 'lucideBookOpen',
      items: [
        { title: 'Introduction', url: '#' },
        { title: 'Get Started', url: '#' },
        { title: 'Tutorials', url: '#' },
        { title: 'Changelog', url: '#' },
      ],
    },
    {
      title: 'Settings',
      url: '#',
      icon: 'lucideSettings2',
      items: [
        { title: 'General', url: '#' },
        { title: 'Team', url: '#' },
        { title: 'Billing', url: '#' },
        { title: 'Limits', url: '#' },
      ],
    },
  ];

  protected readonly projects: readonly Sidebar07Project[] = [
    { name: 'Design Engineering', url: '#', icon: 'lucideFrame' },
    { name: 'Sales & Marketing', url: '#', icon: 'lucidePieChart' },
    { name: 'Travel', url: '#', icon: 'lucideMap' },
  ];
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-07-nav-main.component.html',
      path: 'src/components/sidebar-07/sidebar-07-nav-main.component.html',
      content: `<div z-sidebar-group>
  <div z-sidebar-group-label>Platform</div>

  <ul z-sidebar-menu>
    @for (item of items(); track item.title) {
      <li z-sidebar-menu-item z-collapsible class="group/collapsible" [zOpen]="!!item.isActive">
        <button z-collapsible-trigger z-sidebar-menu-button [zTooltip]="item.title">
          <ng-icon [name]="item.icon" />
          <span>{{ item.title }}</span>
          <ng-icon
            name="lucideChevronRight"
            class="ml-auto transition-transform duration-200 group-data-[state=open]/collapsible:rotate-90"
          />
        </button>

        <z-collapsible-content>
          <ul z-sidebar-menu-sub>
            @for (subItem of item.items; track subItem.title) {
              <li z-sidebar-menu-sub-item>
                <a z-sidebar-menu-sub-button [href]="subItem.url">
                  <span>{{ subItem.title }}</span>
                </a>
              </li>
            }
          </ul>
        </z-collapsible-content>
      </li>
    }
  </ul>
</div>
`,
      language: 'html',
    },
    {
      name: 'sidebar-07-nav-main.component.ts',
      path: 'src/components/sidebar-07/sidebar-07-nav-main.component.ts',
      content: `import { ChangeDetectionStrategy, Component, input } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideBookOpen, lucideBot, lucideChevronRight, lucideSettings2, lucideSquareTerminal } from '@ng-icons/lucide';

import { ZardCollapsibleImports } from '@zard/components/collapsible/collapsible.imports';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

export interface Sidebar07NavSubItem {
  readonly title: string;
  readonly url: string;
}

export interface Sidebar07NavItem {
  readonly title: string;
  readonly url: string;
  readonly icon: string;
  readonly isActive?: boolean;
  readonly items: readonly Sidebar07NavSubItem[];
}

@Component({
  selector: 'lib-sidebar-07-nav-main',
  standalone: true,
  imports: [...ZardSidebarImports, ...ZardCollapsibleImports, NgIcon],
  viewProviders: [
    provideIcons({ lucideBookOpen, lucideBot, lucideChevronRight, lucideSettings2, lucideSquareTerminal }),
  ],
  templateUrl: './sidebar-07-nav-main.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Sidebar07NavMainComponent {
  readonly items = input<readonly Sidebar07NavItem[]>([]);
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-07-nav-projects.component.html',
      path: 'src/components/sidebar-07/sidebar-07-nav-projects.component.html',
      content: `<div z-sidebar-group class="group-data-[collapsible=icon]:hidden">
  <div z-sidebar-group-label>Projects</div>

  <ul z-sidebar-menu>
    @for (item of projects(); track item.name) {
      <li z-sidebar-menu-item>
        <a z-sidebar-menu-button [href]="item.url">
          <ng-icon [name]="item.icon" />
          <span>{{ item.name }}</span>
        </a>

        <button z-sidebar-menu-action zShowOnHover z-dropdown [zDropdownMenu]="projectMenu">
          <ng-icon name="lucideMoreHorizontal" />
          <span class="sr-only">More</span>
        </button>

        <z-dropdown-menu-content
          #projectMenu="zDropdownMenuContent"
          class="w-48 rounded-lg"
          [zSide]="menuSide()"
          [zAlign]="menuAlign()"
        >
          <z-dropdown-menu-item>
            <ng-icon name="lucideFolder" class="text-muted-foreground" />
            <span>View Project</span>
          </z-dropdown-menu-item>
          <z-dropdown-menu-item>
            <ng-icon name="lucideForward" class="text-muted-foreground" />
            <span>Share Project</span>
          </z-dropdown-menu-item>
          <z-dropdown-menu-separator />
          <z-dropdown-menu-item>
            <ng-icon name="lucideTrash2" class="text-muted-foreground" />
            <span>Delete Project</span>
          </z-dropdown-menu-item>
        </z-dropdown-menu-content>
      </li>
    }

    <li z-sidebar-menu-item>
      <button z-sidebar-menu-button class="text-sidebar-foreground/70">
        <ng-icon name="lucideMoreHorizontal" class="text-sidebar-foreground/70" />
        <span>More</span>
      </button>
    </li>
  </ul>
</div>
`,
      language: 'html',
    },
    {
      name: 'sidebar-07-nav-projects.component.ts',
      path: 'src/components/sidebar-07/sidebar-07-nav-projects.component.ts',
      content: `import { ChangeDetectionStrategy, Component, computed, inject, input } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import {
  lucideFolder,
  lucideForward,
  lucideFrame,
  lucideMap,
  lucideMoreHorizontal,
  lucidePieChart,
  lucideTrash2,
} from '@ng-icons/lucide';

import type { ZardDropdownAlign, ZardDropdownSide } from '@zard/components/dropdown/dropdown-positions';
import { ZardDropdownImports } from '@zard/components/dropdown/dropdown.imports';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';
import { ZardSidebarService } from '@zard/components/sidebar/sidebar.service';

export interface Sidebar07Project {
  readonly name: string;
  readonly url: string;
  readonly icon: string;
}

@Component({
  selector: 'lib-sidebar-07-nav-projects',
  standalone: true,
  imports: [...ZardSidebarImports, ...ZardDropdownImports, NgIcon],
  viewProviders: [
    provideIcons({
      lucideFolder,
      lucideForward,
      lucideFrame,
      lucideMap,
      lucideMoreHorizontal,
      lucidePieChart,
      lucideTrash2,
    }),
  ],
  templateUrl: './sidebar-07-nav-projects.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Sidebar07NavProjectsComponent {
  private readonly sidebar = inject(ZardSidebarService);
  /** shadcn opens these menus to the side of the sidebar on desktop and below the trigger on mobile. */
  protected readonly menuSide = computed<ZardDropdownSide>(() => (this.sidebar.isMobile() ? 'bottom' : 'right'));
  protected readonly menuAlign = computed<ZardDropdownAlign>(() => (this.sidebar.isMobile() ? 'end' : 'start'));

  readonly projects = input<readonly Sidebar07Project[]>([]);
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-07-nav-user.component.html',
      path: 'src/components/sidebar-07/sidebar-07-nav-user.component.html',
      content: `<ul z-sidebar-menu>
  <li z-sidebar-menu-item>
    <button
      z-sidebar-menu-button
      zSize="lg"
      z-dropdown
      [zDropdownMenu]="userMenu"
      class="data-[state=open]:bg-sidebar-accent data-[state=open]:text-sidebar-accent-foreground"
    >
      <z-avatar class="size-8 rounded-lg" [zSrc]="user().avatar" [zAlt]="user().name" zFallback="ZU" />

      <div class="grid flex-1 text-left text-sm leading-tight">
        <span class="truncate font-medium">{{ user().name }}</span>
        <span class="truncate text-xs">{{ user().email }}</span>
      </div>

      <ng-icon name="lucideChevronsUpDown" class="ml-auto size-4" />
    </button>

    <z-dropdown-menu-content
      #userMenu="zDropdownMenuContent"
      class="w-(--z-dropdown-menu-trigger-width) min-w-56 rounded-lg"
      [zSide]="menuSide()"
      zAlign="end"
    >
      <z-dropdown-menu-label class="p-0 font-normal">
        <div class="flex items-center gap-2 px-1 py-1.5 text-left text-sm">
          <z-avatar class="size-8 rounded-lg" [zSrc]="user().avatar" [zAlt]="user().name" zFallback="ZU" />

          <div class="grid flex-1 text-left text-sm leading-tight">
            <span class="truncate font-medium">{{ user().name }}</span>
            <span class="truncate text-xs">{{ user().email }}</span>
          </div>
        </div>
      </z-dropdown-menu-label>

      <z-dropdown-menu-separator />

      <z-dropdown-menu-group>
        <z-dropdown-menu-item>
          <ng-icon name="lucideSparkles" />
          Upgrade to Pro
        </z-dropdown-menu-item>
      </z-dropdown-menu-group>

      <z-dropdown-menu-separator />

      <z-dropdown-menu-group>
        <z-dropdown-menu-item>
          <ng-icon name="lucideBadgeCheck" />
          Account
        </z-dropdown-menu-item>
        <z-dropdown-menu-item>
          <ng-icon name="lucideCreditCard" />
          Billing
        </z-dropdown-menu-item>
        <z-dropdown-menu-item>
          <ng-icon name="lucideBell" />
          Notifications
        </z-dropdown-menu-item>
      </z-dropdown-menu-group>

      <z-dropdown-menu-separator />

      <z-dropdown-menu-item>
        <ng-icon name="lucideLogOut" />
        Log out
      </z-dropdown-menu-item>
    </z-dropdown-menu-content>
  </li>
</ul>
`,
      language: 'html',
    },
    {
      name: 'sidebar-07-nav-user.component.ts',
      path: 'src/components/sidebar-07/sidebar-07-nav-user.component.ts',
      content: `import { ChangeDetectionStrategy, Component, computed, inject, input } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import {
  lucideBadgeCheck,
  lucideBell,
  lucideChevronsUpDown,
  lucideCreditCard,
  lucideLogOut,
  lucideSparkles,
} from '@ng-icons/lucide';

import { ZardAvatarComponent } from '@zard/components/avatar/avatar.component';
import type { ZardDropdownSide } from '@zard/components/dropdown/dropdown-positions';
import { ZardDropdownImports } from '@zard/components/dropdown/dropdown.imports';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';
import { ZardSidebarService } from '@zard/components/sidebar/sidebar.service';

export interface Sidebar07User {
  readonly name: string;
  readonly email: string;
  readonly avatar: string;
}

@Component({
  selector: 'lib-sidebar-07-nav-user',
  standalone: true,
  imports: [...ZardSidebarImports, ...ZardDropdownImports, ZardAvatarComponent, NgIcon],
  viewProviders: [
    provideIcons({
      lucideBadgeCheck,
      lucideBell,
      lucideChevronsUpDown,
      lucideCreditCard,
      lucideLogOut,
      lucideSparkles,
    }),
  ],
  templateUrl: './sidebar-07-nav-user.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Sidebar07NavUserComponent {
  private readonly sidebar = inject(ZardSidebarService);
  /** shadcn opens these menus to the side of the sidebar on desktop and below the trigger on mobile. */
  protected readonly menuSide = computed<ZardDropdownSide>(() => (this.sidebar.isMobile() ? 'bottom' : 'right'));

  readonly user = input.required<Sidebar07User>();
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-07-team-switcher.component.html',
      path: 'src/components/sidebar-07/sidebar-07-team-switcher.component.html',
      content: `<ul z-sidebar-menu>
  <li z-sidebar-menu-item>
    <button
      z-sidebar-menu-button
      zSize="lg"
      z-dropdown
      [zDropdownMenu]="teamMenu"
      class="data-[state=open]:bg-sidebar-accent data-[state=open]:text-sidebar-accent-foreground"
    >
      <div
        class="bg-sidebar-primary text-sidebar-primary-foreground flex aspect-square size-8 items-center justify-center rounded-lg"
      >
        <ng-icon [name]="activeTeam()?.logo ?? ''" class="size-4" />
      </div>
      <div class="grid flex-1 text-left text-sm leading-tight">
        <span class="truncate font-medium">{{ activeTeam()?.name }}</span>
        <span class="truncate text-xs">{{ activeTeam()?.plan }}</span>
      </div>
      <ng-icon name="lucideChevronsUpDown" class="ml-auto" />
    </button>

    <z-dropdown-menu-content
      #teamMenu="zDropdownMenuContent"
      class="w-(--z-dropdown-menu-trigger-width) min-w-56 rounded-lg"
      [zSide]="menuSide()"
      zAlign="start"
    >
      <z-dropdown-menu-label class="text-muted-foreground text-xs">Teams</z-dropdown-menu-label>

      @for (team of teams(); track team.name; let index = $index) {
        <z-dropdown-menu-item class="gap-2 p-2" (click)="selectedTeam.set(team)">
          <div class="flex size-6 items-center justify-center rounded-md border">
            <ng-icon [name]="team.logo" class="size-3.5 shrink-0" />
          </div>
          {{ team.name }}
          <z-dropdown-menu-shortcut>⌘{{ index + 1 }}</z-dropdown-menu-shortcut>
        </z-dropdown-menu-item>
      }

      <z-dropdown-menu-separator />

      <z-dropdown-menu-item class="gap-2 p-2">
        <div class="flex size-6 items-center justify-center rounded-md border bg-transparent">
          <ng-icon name="lucidePlus" class="size-4" />
        </div>
        <div class="text-muted-foreground font-medium">Add team</div>
      </z-dropdown-menu-item>
    </z-dropdown-menu-content>
  </li>
</ul>
`,
      language: 'html',
    },
    {
      name: 'sidebar-07-team-switcher.component.ts',
      path: 'src/components/sidebar-07/sidebar-07-team-switcher.component.ts',
      content: `import { ChangeDetectionStrategy, Component, computed, inject, input, signal } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import {
  lucideAudioWaveform,
  lucideChevronsUpDown,
  lucideCommand,
  lucideGalleryVerticalEnd,
  lucidePlus,
} from '@ng-icons/lucide';

import type { ZardDropdownSide } from '@zard/components/dropdown/dropdown-positions';
import { ZardDropdownImports } from '@zard/components/dropdown/dropdown.imports';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';
import { ZardSidebarService } from '@zard/components/sidebar/sidebar.service';

export interface Sidebar07Team {
  readonly name: string;
  readonly logo: string;
  readonly plan: string;
}

@Component({
  selector: 'lib-sidebar-07-team-switcher',
  standalone: true,
  imports: [...ZardSidebarImports, ...ZardDropdownImports, NgIcon],
  viewProviders: [
    provideIcons({ lucideAudioWaveform, lucideChevronsUpDown, lucideCommand, lucideGalleryVerticalEnd, lucidePlus }),
  ],
  templateUrl: './sidebar-07-team-switcher.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Sidebar07TeamSwitcherComponent {
  private readonly sidebar = inject(ZardSidebarService);
  /** shadcn opens these menus to the side of the sidebar on desktop and below the trigger on mobile. */
  protected readonly menuSide = computed<ZardDropdownSide>(() => (this.sidebar.isMobile() ? 'bottom' : 'right'));

  readonly teams = input<readonly Sidebar07Team[]>([]);

  protected readonly selectedTeam = signal<Sidebar07Team | null>(null);

  protected activeTeam(): Sidebar07Team | undefined {
    return this.selectedTeam() ?? this.teams()[0];
  }
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-07.component.html',
      path: 'src/components/sidebar-07/sidebar-07.component.html',
      content: `<z-sidebar-provider>
  <lib-sidebar-07-app-sidebar />

  <main z-sidebar-inset>
    <header
      class="flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-data-[collapsible=icon]/sidebar-wrapper:h-12"
    >
      <div class="flex items-center gap-2 px-4">
        <button z-sidebar-trigger class="-ml-1" aria-label="Toggle Sidebar"></button>

        <z-separator
          zOrientation="vertical"
          class="mr-2 data-[orientation=vertical]:h-4 data-[orientation=vertical]:self-center"
        />

        <z-breadcrumb>
          <z-breadcrumb-item class="hidden md:block">
            <a z-breadcrumb-link href="#">Build Your Application</a>
          </z-breadcrumb-item>
          <z-breadcrumb-separator class="hidden md:block" />
          <z-breadcrumb-item>
            <span z-breadcrumb-page>Data Fetching</span>
          </z-breadcrumb-item>
        </z-breadcrumb>
      </div>
    </header>

    <div class="flex flex-1 flex-col gap-4 p-4 pt-0">
      <div class="grid auto-rows-min gap-4 md:grid-cols-3">
        <div class="bg-muted/50 aspect-video rounded-xl"></div>
        <div class="bg-muted/50 aspect-video rounded-xl"></div>
        <div class="bg-muted/50 aspect-video rounded-xl"></div>
      </div>
      <div class="bg-muted/50 min-h-[100vh] flex-1 rounded-xl md:min-h-min"></div>
    </div>
  </main>
</z-sidebar-provider>
`,
      language: 'html',
    },
    {
      name: 'sidebar-07.component.ts',
      path: 'src/components/sidebar-07/sidebar-07.component.ts',
      content: `import { ChangeDetectionStrategy, Component } from '@angular/core';

import { ZardBreadcrumbImports } from '@zard/components/breadcrumb/breadcrumb.imports';
import { ZardSeparatorComponent } from '@zard/components/separator/separator.component';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

import { Sidebar07AppSidebarComponent } from './sidebar-07-app-sidebar.component';

@Component({
  selector: 'lib-sidebar-07',
  standalone: true,
  imports: [...ZardSidebarImports, ...ZardBreadcrumbImports, ZardSeparatorComponent, Sidebar07AppSidebarComponent],
  templateUrl: './sidebar-07.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Sidebar07Component {}
`,
      language: 'typescript',
    },
  ],
};
