import { ChangeDetectionStrategy, Component, inject, type OnInit } from '@angular/core';

import {
  BLOCK_0 as GENERATE_BLOCK,
  BLOCK_1 as BLOCK_METADATA_BLOCK,
  BLOCK_2 as REGISTRY_BLOCK,
  BLOCK_3 as FINISH_BLOCK,
} from '@generated/pages/contribute/blocks';
import { CodeBlockComponent } from '@highlight/components/code-block/code-block.component';
import type { CodeBlockData } from '@highlight/types';

import { CalloutComponent } from '@doc/domain/components/callout/callout.component';
import { DocContentComponent } from '@doc/domain/components/doc-content/doc-content.component';
import { DocHeadingComponent } from '@doc/domain/components/doc-heading/doc-heading.component';
import { NavigationConfig } from '@doc/domain/components/dynamic-anchor/dynamic-anchor.component';
import { ScrollSpyItemDirective } from '@doc/domain/directives/scroll-spy-item.directive';
import { ScrollSpyDirective } from '@doc/domain/directives/scroll-spy.directive';
import { SeoService } from '@doc/shared/services/seo.service';

interface FieldEntry {
  field: string;
  type: string;
  description: string;
}

interface ManualStep {
  step: string;
  title: string;
  description: string;
}

@Component({
  selector: 'z-contribute-blocks',
  imports: [
    CodeBlockComponent,
    CalloutComponent,
    DocContentComponent,
    DocHeadingComponent,
    ScrollSpyDirective,
    ScrollSpyItemDirective,
  ],
  templateUrl: './blocks.page.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ContributeBlocksPage implements OnInit {
  activeAnchor?: string;

  private readonly seoService = inject(SeoService);

  readonly generateBlock: CodeBlockData = GENERATE_BLOCK;
  readonly blockMetadataBlock: CodeBlockData = BLOCK_METADATA_BLOCK;
  readonly registryBlock: CodeBlockData = REGISTRY_BLOCK;
  readonly finishBlock: CodeBlockData = FINISH_BLOCK;

  readonly navigationConfig: NavigationConfig = {
    items: [
      { id: 'overview', label: 'Overview', type: 'core' },
      { id: 'generator', label: 'Run the Generator', type: 'custom' },
      { id: 'metadata', label: 'Block Metadata', type: 'custom' },
      { id: 'registry', label: 'Registry & Categories', type: 'custom' },
      { id: 'manual-steps', label: 'What You Must Add', type: 'custom' },
    ],
  };

  readonly metadataFields: FieldEntry[] = [
    { field: 'id', type: 'string', description: 'The folder name. Used in the preview route /blocks/preview/:id.' },
    { field: 'title', type: 'string', description: 'The heading shown on the block card.' },
    { field: 'description', type: 'string', description: 'One sentence describing what the screen does.' },
    { field: 'component', type: 'Type', description: 'The Angular component rendered in the live preview.' },
    {
      field: 'category',
      type: 'string',
      description: "A display label such as 'Authentication'. It is not the registry key.",
    },
    {
      field: 'image',
      type: '{ light, dark }',
      description: 'Paths to the two screenshots served from apps/web/public/blocks/<id>/.',
    },
    {
      field: 'files',
      type: 'BlockFile[]',
      description: 'The copyable sources. Generated by npm run sync:blocks — never edit by hand.',
    },
  ];

  readonly registryCategories: string[] = ['featured', 'sidebar', 'login', 'signup', 'otp', 'calendar'];

  readonly manualSteps: ManualStep[] = [
    {
      step: '1',
      title: 'Build the screen',
      description:
        'Compose existing Zard components in <name>.component.ts and its template. A block should not introduce new primitives — if you need one, add it to libs/zard first.',
    },
    {
      step: '2',
      title: 'Sync the sources',
      description:
        'Run npm run sync:blocks. It rewrites files[] from every .ts and .html in the folder except block.ts, so the code tab always matches the running preview.',
    },
    {
      step: '3',
      title: 'Add the screenshots',
      description:
        'Save light.png and dark.png under apps/web/public/blocks/<name>/. The generator prints the exact paths; without them the card renders a broken image.',
    },
    {
      step: '4',
      title: 'Rebuild the registry',
      description: 'Run npm run build:registry so zard-cli and the MCP server can install the new block.',
    },
  ];

  ngOnInit(): void {
    this.seoService.setDocsSeo(
      'Contributing Blocks',
      'How to scaffold, sync and register a Zard UI block, including the screenshots and registry entries you must provide yourself.',
      '/docs/contribute/blocks',
      'og-contribute-blocks.jpg',
    );
  }
}
