import type { Block } from '@doc/domain/components/block-container/block-container.component';

import { Sidebar03Component } from './sidebar-03.component';

export const sidebar03Block: Block = {
  id: 'sidebar-03',
  title: 'Sidebar 03',
  description: 'A sidebar with submenus.',
  component: Sidebar03Component,
  category: 'Sidebar',
  image: {
    light: '/blocks/sidebar-03/light.png',
    dark: '/blocks/sidebar-03/dark.png',
  },
  // Generated by `npm run sync:blocks` from the sibling component files — do not edit by hand.
  files: [
    {
      name: 'sidebar-03-app-sidebar.component.html',
      path: 'src/components/sidebar-03/sidebar-03-app-sidebar.component.html',
      content: `<z-sidebar>
  <div z-sidebar-header>
    <ul z-sidebar-menu>
      <li z-sidebar-menu-item>
        <a z-sidebar-menu-button zSize="lg" href="#">
          <div
            class="bg-sidebar-primary text-sidebar-primary-foreground flex aspect-square size-8 items-center justify-center rounded-lg"
          >
            <ng-icon name="lucideGalleryVerticalEnd" class="size-4" />
          </div>
          <div class="flex flex-col gap-0.5 leading-none">
            <span class="font-medium">Documentation</span>
            <span>v1.0.0</span>
          </div>
        </a>
      </li>
    </ul>
  </div>

  <z-sidebar-content>
    <div z-sidebar-group>
      <ul z-sidebar-menu>
        @for (group of navMain; track group.title) {
          <li z-sidebar-menu-item>
            <a z-sidebar-menu-button [href]="group.url" class="font-medium">{{ group.title }}</a>

            @if (group.items.length) {
              <ul z-sidebar-menu-sub>
                @for (item of group.items; track item.title) {
                  <li z-sidebar-menu-sub-item>
                    <a z-sidebar-menu-sub-button [href]="item.url" [zActive]="!!item.isActive">{{ item.title }}</a>
                  </li>
                }
              </ul>
            }
          </li>
        }
      </ul>
    </div>
  </z-sidebar-content>

  <button z-sidebar-rail aria-label="Toggle Sidebar"></button>
</z-sidebar>
`,
      language: 'html',
    },
    {
      name: 'sidebar-03-app-sidebar.component.ts',
      path: 'src/components/sidebar-03/sidebar-03-app-sidebar.component.ts',
      content: `import { ChangeDetectionStrategy, Component } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideGalleryVerticalEnd } from '@ng-icons/lucide';

import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

interface NavItem {
  readonly title: string;
  readonly url: string;
  readonly isActive?: boolean;
}

interface NavGroup {
  readonly title: string;
  readonly url: string;
  readonly items: readonly NavItem[];
}

@Component({
  selector: 'lib-sidebar-03-app-sidebar',
  standalone: true,
  imports: [...ZardSidebarImports, NgIcon],
  viewProviders: [provideIcons({ lucideGalleryVerticalEnd })],
  templateUrl: './sidebar-03-app-sidebar.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Sidebar03AppSidebarComponent {
  // This is sample data.
  protected readonly navMain: readonly NavGroup[] = [
    {
      title: 'Getting Started',
      url: '#',
      items: [
        { title: 'Installation', url: '#' },
        { title: 'Project Structure', url: '#' },
      ],
    },
    {
      title: 'Build Your Application',
      url: '#',
      items: [
        { title: 'Routing', url: '#' },
        { title: 'Data Fetching', url: '#', isActive: true },
        { title: 'Rendering', url: '#' },
        { title: 'Caching', url: '#' },
        { title: 'Styling', url: '#' },
        { title: 'Optimizing', url: '#' },
        { title: 'Configuring', url: '#' },
        { title: 'Testing', url: '#' },
        { title: 'Authentication', url: '#' },
        { title: 'Deploying', url: '#' },
        { title: 'Upgrading', url: '#' },
        { title: 'Examples', url: '#' },
      ],
    },
    {
      title: 'API Reference',
      url: '#',
      items: [
        { title: 'Components', url: '#' },
        { title: 'Style Guide', url: '#' },
        { title: 'Functions', url: '#' },
        { title: 'angular.json Options', url: '#' },
        { title: 'CLI', url: '#' },
        { title: 'Hydration', url: '#' },
      ],
    },
    {
      title: 'Architecture',
      url: '#',
      items: [
        { title: 'Accessibility', url: '#' },
        { title: 'Hot Module Replacement', url: '#' },
        { title: 'Angular Compiler', url: '#' },
        { title: 'Supported Browsers', url: '#' },
        { title: 'esbuild', url: '#' },
      ],
    },
    {
      title: 'Community',
      url: '#',
      items: [{ title: 'Contribution Guide', url: '#' }],
    },
  ];
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-03.component.html',
      path: 'src/components/sidebar-03/sidebar-03.component.html',
      content: `<z-sidebar-provider>
  <lib-sidebar-03-app-sidebar />

  <main z-sidebar-inset>
    <header class="flex h-16 shrink-0 items-center gap-2 border-b">
      <div class="flex items-center gap-2 px-3">
        <button z-sidebar-trigger aria-label="Toggle Sidebar"></button>

        <z-separator
          zOrientation="vertical"
          class="mr-2 data-[orientation=vertical]:h-4 data-[orientation=vertical]:self-center"
        />

        <z-breadcrumb>
          <z-breadcrumb-item class="hidden md:block">
            <a z-breadcrumb-link href="#">Build Your Application</a>
          </z-breadcrumb-item>
          <z-breadcrumb-separator class="hidden md:block" />
          <z-breadcrumb-item>
            <span z-breadcrumb-page>Data Fetching</span>
          </z-breadcrumb-item>
        </z-breadcrumb>
      </div>
    </header>

    <div class="flex flex-1 flex-col gap-4 p-4">
      <div class="grid auto-rows-min gap-4 md:grid-cols-3">
        <div class="bg-muted/50 aspect-video rounded-xl"></div>
        <div class="bg-muted/50 aspect-video rounded-xl"></div>
        <div class="bg-muted/50 aspect-video rounded-xl"></div>
      </div>
      <div class="bg-muted/50 min-h-[100vh] flex-1 rounded-xl md:min-h-min"></div>
    </div>
  </main>
</z-sidebar-provider>
`,
      language: 'html',
    },
    {
      name: 'sidebar-03.component.ts',
      path: 'src/components/sidebar-03/sidebar-03.component.ts',
      content: `import { ChangeDetectionStrategy, Component } from '@angular/core';

import { ZardBreadcrumbImports } from '@zard/components/breadcrumb/breadcrumb.imports';
import { ZardSeparatorComponent } from '@zard/components/separator/separator.component';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

import { Sidebar03AppSidebarComponent } from './sidebar-03-app-sidebar.component';

@Component({
  selector: 'lib-sidebar-03',
  standalone: true,
  imports: [...ZardSidebarImports, ...ZardBreadcrumbImports, ZardSeparatorComponent, Sidebar03AppSidebarComponent],
  templateUrl: './sidebar-03.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Sidebar03Component {}
`,
      language: 'typescript',
    },
  ],
};
