import type { Block } from '@doc/domain/components/block-container/block-container.component';

import { Sidebar02Component } from './sidebar-02.component';

export const sidebar02Block: Block = {
  id: 'sidebar-02',
  title: 'Sidebar 02',
  description: 'A sidebar with collapsible sections.',
  component: Sidebar02Component,
  category: 'Sidebar',
  image: {
    light: '/blocks/sidebar-02/light.png',
    dark: '/blocks/sidebar-02/dark.png',
  },
  // Generated by `npm run sync:blocks` from the sibling component files — do not edit by hand.
  files: [
    {
      name: 'sidebar-02-app-sidebar.component.html',
      path: 'src/components/sidebar-02/sidebar-02-app-sidebar.component.html',
      content: `<z-sidebar>
  <div z-sidebar-header>
    <lib-sidebar-02-version-switcher [versions]="versions" [defaultVersion]="versions[0]" />
    <lib-sidebar-02-search-form />
  </div>

  <z-sidebar-content class="gap-0">
    <!-- We create a collapsible z-sidebar-group for each parent. -->
    @for (group of navMain; track group.title) {
      <z-collapsible class="group/collapsible" zOpen>
        <div z-sidebar-group>
          <button
            z-collapsible-trigger
            z-sidebar-group-label
            class="group/label text-sidebar-foreground hover:bg-sidebar-accent hover:text-sidebar-accent-foreground w-full text-sm"
          >
            {{ group.title }}
            <ng-icon
              name="lucideChevronRight"
              class="ml-auto transition-transform group-data-[state=open]/collapsible:rotate-90"
            />
          </button>

          <z-collapsible-content>
            <div z-sidebar-group-content>
              <ul z-sidebar-menu>
                @for (item of group.items; track item.title) {
                  <li z-sidebar-menu-item>
                    <a z-sidebar-menu-button [href]="item.url" [zActive]="!!item.isActive">{{ item.title }}</a>
                  </li>
                }
              </ul>
            </div>
          </z-collapsible-content>
        </div>
      </z-collapsible>
    }
  </z-sidebar-content>

  <button z-sidebar-rail aria-label="Toggle Sidebar"></button>
</z-sidebar>
`,
      language: 'html',
    },
    {
      name: 'sidebar-02-app-sidebar.component.ts',
      path: 'src/components/sidebar-02/sidebar-02-app-sidebar.component.ts',
      content: `import { ChangeDetectionStrategy, Component } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideChevronRight } from '@ng-icons/lucide';

import { ZardCollapsibleImports } from '@zard/components/collapsible/collapsible.imports';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

import { Sidebar02SearchFormComponent } from './sidebar-02-search-form.component';
import { Sidebar02VersionSwitcherComponent } from './sidebar-02-version-switcher.component';

interface NavItem {
  readonly title: string;
  readonly url: string;
  readonly isActive?: boolean;
}

interface NavGroup {
  readonly title: string;
  readonly url: string;
  readonly items: readonly NavItem[];
}

@Component({
  selector: 'lib-sidebar-02-app-sidebar',
  standalone: true,
  imports: [
    ...ZardSidebarImports,
    ...ZardCollapsibleImports,
    Sidebar02VersionSwitcherComponent,
    Sidebar02SearchFormComponent,
    NgIcon,
  ],
  viewProviders: [provideIcons({ lucideChevronRight })],
  templateUrl: './sidebar-02-app-sidebar.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Sidebar02AppSidebarComponent {
  // This is sample data.
  protected readonly versions = ['1.0.1', '1.1.0-alpha', '2.0.0-beta1'];

  protected readonly navMain: readonly NavGroup[] = [
    {
      title: 'Getting Started',
      url: '#',
      items: [
        { title: 'Installation', url: '#' },
        { title: 'Project Structure', url: '#' },
      ],
    },
    {
      title: 'Build Your Application',
      url: '#',
      items: [
        { title: 'Routing', url: '#' },
        { title: 'Data Fetching', url: '#', isActive: true },
        { title: 'Rendering', url: '#' },
        { title: 'Caching', url: '#' },
        { title: 'Styling', url: '#' },
        { title: 'Optimizing', url: '#' },
        { title: 'Configuring', url: '#' },
        { title: 'Testing', url: '#' },
        { title: 'Authentication', url: '#' },
        { title: 'Deploying', url: '#' },
        { title: 'Upgrading', url: '#' },
        { title: 'Examples', url: '#' },
      ],
    },
    {
      title: 'API Reference',
      url: '#',
      items: [
        { title: 'Components', url: '#' },
        { title: 'File Conventions', url: '#' },
        { title: 'Functions', url: '#' },
        { title: 'next.config.js Options', url: '#' },
        { title: 'CLI', url: '#' },
        { title: 'Edge Runtime', url: '#' },
      ],
    },
    {
      title: 'Architecture',
      url: '#',
      items: [
        { title: 'Accessibility', url: '#' },
        { title: 'Fast Refresh', url: '#' },
        { title: 'Next.js Compiler', url: '#' },
        { title: 'Supported Browsers', url: '#' },
        { title: 'Turbopack', url: '#' },
      ],
    },
    {
      title: 'Community',
      url: '#',
      items: [{ title: 'Contribution Guide', url: '#' }],
    },
  ];
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-02-search-form.component.html',
      path: 'src/components/sidebar-02/sidebar-02-search-form.component.html',
      content: `<form>
  <div z-sidebar-group class="py-0">
    <div z-sidebar-group-content class="relative">
      <label z-field-label for="search" class="sr-only">Search</label>

      <input z-input z-sidebar-input id="search" placeholder="Search the docs..." class="pl-8" />

      <ng-icon
        name="lucideSearch"
        class="pointer-events-none absolute top-1/2 left-2 size-4 -translate-y-1/2 opacity-50 select-none"
      />
    </div>
  </div>
</form>
`,
      language: 'html',
    },
    {
      name: 'sidebar-02-search-form.component.ts',
      path: 'src/components/sidebar-02/sidebar-02-search-form.component.ts',
      content: `import { ChangeDetectionStrategy, Component } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideSearch } from '@ng-icons/lucide';

import { ZardFieldImports } from '@zard/components/field/field.imports';
import { ZardInputComponent } from '@zard/components/input/input.component';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

@Component({
  selector: 'lib-sidebar-02-search-form',
  standalone: true,
  imports: [...ZardSidebarImports, ...ZardFieldImports, ZardInputComponent, NgIcon],
  viewProviders: [provideIcons({ lucideSearch })],
  templateUrl: './sidebar-02-search-form.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Sidebar02SearchFormComponent {}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-02-version-switcher.component.html',
      path: 'src/components/sidebar-02/sidebar-02-version-switcher.component.html',
      content: `<ul z-sidebar-menu>
  <li z-sidebar-menu-item>
    <button
      z-sidebar-menu-button
      zSize="lg"
      z-dropdown
      [zDropdownMenu]="versionMenu"
      class="data-[state=open]:bg-sidebar-accent data-[state=open]:text-sidebar-accent-foreground"
    >
      <div
        class="bg-sidebar-primary text-sidebar-primary-foreground flex aspect-square size-8 items-center justify-center rounded-lg"
      >
        <ng-icon name="lucideGalleryVerticalEnd" class="size-4" />
      </div>
      <div class="flex flex-col gap-0.5 leading-none">
        <span class="font-medium">Documentation</span>
        <span>v{{ activeVersion() }}</span>
      </div>
      <ng-icon name="lucideChevronsUpDown" class="ml-auto" />
    </button>

    <z-dropdown-menu-content #versionMenu="zDropdownMenuContent" class="w-(--sidebar-width)">
      @for (version of versions(); track version) {
        <z-dropdown-menu-item (click)="selectedVersion.set(version)">
          v{{ version }}
          @if (version === activeVersion()) {
            <ng-icon name="lucideCheck" class="ml-auto" />
          }
        </z-dropdown-menu-item>
      }
    </z-dropdown-menu-content>
  </li>
</ul>
`,
      language: 'html',
    },
    {
      name: 'sidebar-02-version-switcher.component.ts',
      path: 'src/components/sidebar-02/sidebar-02-version-switcher.component.ts',
      content: `import { ChangeDetectionStrategy, Component, input, signal } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideCheck, lucideChevronsUpDown, lucideGalleryVerticalEnd } from '@ng-icons/lucide';

import { ZardDropdownImports } from '@zard/components/dropdown/dropdown.imports';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

@Component({
  selector: 'lib-sidebar-02-version-switcher',
  standalone: true,
  imports: [...ZardSidebarImports, ...ZardDropdownImports, NgIcon],
  viewProviders: [provideIcons({ lucideCheck, lucideChevronsUpDown, lucideGalleryVerticalEnd })],
  templateUrl: './sidebar-02-version-switcher.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Sidebar02VersionSwitcherComponent {
  readonly versions = input<readonly string[]>([]);
  readonly defaultVersion = input<string>('');

  protected readonly selectedVersion = signal<string | null>(null);

  protected readonly activeVersion = () => this.selectedVersion() ?? this.defaultVersion();
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-02.component.html',
      path: 'src/components/sidebar-02/sidebar-02.component.html',
      content: `<z-sidebar-provider>
  <lib-sidebar-02-app-sidebar />

  <main z-sidebar-inset>
    <header class="flex h-16 shrink-0 items-center gap-2 border-b px-4">
      <button z-sidebar-trigger class="-ml-1" aria-label="Toggle Sidebar"></button>

      <z-separator zOrientation="vertical" class="mr-2 data-[orientation=vertical]:h-4 data-[orientation=vertical]:self-center" />

      <z-breadcrumb>
        <z-breadcrumb-item class="hidden md:block">
          <a z-breadcrumb-link href="#">Build Your Application</a>
        </z-breadcrumb-item>
        <z-breadcrumb-separator class="hidden md:block" />
        <z-breadcrumb-item>
          <span z-breadcrumb-page>Data Fetching</span>
        </z-breadcrumb-item>
      </z-breadcrumb>
    </header>

    <div class="flex flex-1 flex-col gap-4 p-4">
      <div class="grid auto-rows-min gap-4 md:grid-cols-3">
        <div class="bg-muted/50 aspect-video rounded-xl"></div>
        <div class="bg-muted/50 aspect-video rounded-xl"></div>
        <div class="bg-muted/50 aspect-video rounded-xl"></div>
      </div>
      <div class="bg-muted/50 min-h-[100vh] flex-1 rounded-xl md:min-h-min"></div>
    </div>
  </main>
</z-sidebar-provider>
`,
      language: 'html',
    },
    {
      name: 'sidebar-02.component.ts',
      path: 'src/components/sidebar-02/sidebar-02.component.ts',
      content: `import { ChangeDetectionStrategy, Component } from '@angular/core';

import { ZardBreadcrumbImports } from '@zard/components/breadcrumb/breadcrumb.imports';
import { ZardSeparatorComponent } from '@zard/components/separator/separator.component';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

import { Sidebar02AppSidebarComponent } from './sidebar-02-app-sidebar.component';

@Component({
  selector: 'lib-sidebar-02',
  standalone: true,
  imports: [...ZardSidebarImports, ...ZardBreadcrumbImports, ZardSeparatorComponent, Sidebar02AppSidebarComponent],
  templateUrl: './sidebar-02.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Sidebar02Component {}
`,
      language: 'typescript',
    },
  ],
};
