import type { Block } from '@doc/domain/components/block-container/block-container.component';

import { Sidebar05Component } from './sidebar-05.component';

export const sidebar05Block: Block = {
  id: 'sidebar-05',
  title: 'Sidebar 05',
  description: 'A sidebar with collapsible submenus.',
  component: Sidebar05Component,
  category: 'Sidebar',
  image: {
    light: '/blocks/sidebar-05/light.png',
    dark: '/blocks/sidebar-05/dark.png',
  },
  // Generated by `npm run sync:blocks` from the sibling component files — do not edit by hand.
  files: [
    {
      name: 'sidebar-05.component.html',
      path: 'src/components/sidebar-05/sidebar-05.component.html',
      content: `<div class="flex min-h-screen items-center justify-center">
  <p>Sidebar 05</p>
</div>
`,
      language: 'html',
    },
    {
      name: 'sidebar-05.component.ts',
      path: 'src/components/sidebar-05/sidebar-05.component.ts',
      content: `import { Component } from '@angular/core';

@Component({
  selector: 'lib-sidebar-05',
  standalone: true,
  imports: [],
  templateUrl: './sidebar-05.component.html',
})
export class Sidebar05Component {}
`,
      language: 'typescript',
    },
  ],
};
