import type { Block } from '@doc/domain/components/block-container/block-container.component';

import { Signup02Component } from './signup-02.component';

export const signup02Block: Block = {
  id: 'signup-02',
  title: 'Signup with cover image',
  description: 'A two column signup page with a cover image.',
  component: Signup02Component,
  category: 'Signup',
  image: {
    light: '/blocks/signup-02/light.png',
    dark: '/blocks/signup-02/dark.png',
  },
  // Generated by `npm run sync:blocks` from the sibling component files — do not edit by hand.
  files: [
    {
      name: 'signup-02.component.html',
      path: 'src/components/signup-02/signup-02.component.html',
      content: `<div class="grid min-h-svh lg:grid-cols-2">
  <div class="flex flex-col gap-4 p-6 md:p-10">
    <div class="flex justify-center gap-2 md:justify-start">
      <a href="#" class="flex items-center gap-2 font-medium">
        <div class="bg-primary text-primary-foreground flex size-6 items-center justify-center rounded-md">
          <ng-icon name="lucideGalleryVerticalEnd" class="size-4" />
        </div>
        Acme Inc.
      </a>
    </div>
    <div class="flex flex-1 items-center justify-center">
      <div class="w-full max-w-xs">
        <form [formGroup]="signupForm" (ngSubmit)="onSubmit()" class="flex flex-col gap-6">
          <div z-field-group>
            <div class="flex flex-col items-center gap-1 text-center">
              <h1 class="text-2xl font-bold">Create your account</h1>
              <p class="text-muted-foreground text-sm text-balance">Fill in the form below to create your account</p>
            </div>
            <div z-field>
              <label z-field-label for="name">Full Name</label>
              <input z-input id="name" type="text" placeholder="John Doe" formControlName="name" required />
            </div>
            <div z-field>
              <label z-field-label for="email">Email</label>
              <input z-input id="email" type="email" placeholder="m@example.com" formControlName="email" required />
              <p z-field-description>We'll use this to contact you. We will not share your email with anyone else.</p>
            </div>
            <div z-field>
              <label z-field-label for="password">Password</label>
              <input z-input id="password" type="password" formControlName="password" required />
              <p z-field-description>Must be at least 8 characters long.</p>
            </div>
            <div z-field>
              <label z-field-label for="confirm-password">Confirm Password</label>
              <input z-input id="confirm-password" type="password" formControlName="confirmPassword" required />
              <p z-field-description>Please confirm your password.</p>
            </div>
            <div z-field>
              <button z-button type="submit" [zLoading]="isLoading()" [zDisabled]="isLoading()">Create Account</button>
            </div>
            <z-field-separator zContent="Or continue with" />
            <div z-field>
              <button z-button zType="outline" type="button">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                  <path
                    d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12"
                    fill="currentColor"
                  />
                </svg>
                Sign up with GitHub
              </button>
              <p z-field-description class="px-6 text-center">
                Already have an account?
                <a href="#">Sign in</a>
              </p>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
  <div class="bg-muted relative hidden lg:block">
    <img
      src="/images/placeholder.svg"
      alt="Image"
      class="absolute inset-0 h-full w-full object-cover dark:brightness-[0.2] dark:grayscale"
    />
  </div>
</div>
`,
      language: 'html',
    },
    {
      name: 'signup-02.component.ts',
      path: 'src/components/signup-02/signup-02.component.ts',
      content: `import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';

import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideGalleryVerticalEnd } from '@ng-icons/lucide';

import { ZardButtonComponent } from '@zard/components/button/button.component';
import { ZardFieldImports } from '@zard/components/field/field.imports';
import { ZardInputComponent } from '@zard/components/input/input.component';

@Component({
  selector: 'lib-signup-02',
  standalone: true,
  imports: [ReactiveFormsModule, NgIcon, ZardButtonComponent, ZardInputComponent, ...ZardFieldImports],
  templateUrl: './signup-02.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  viewProviders: [provideIcons({ lucideGalleryVerticalEnd })],
})
export class Signup02Component {
  protected readonly isLoading = signal(false);

  protected readonly signupForm = new FormGroup({
    name: new FormControl('', [Validators.required]),
    email: new FormControl('', [Validators.required, Validators.email]),
    password: new FormControl('', [Validators.required, Validators.minLength(8)]),
    confirmPassword: new FormControl('', [Validators.required, Validators.minLength(8)]),
  });

  protected onSubmit(): void {
    if (this.signupForm.invalid) {
      this.signupForm.markAllAsTouched();
      return;
    }
    this.isLoading.set(true);
  }
}
`,
      language: 'typescript',
    },
  ],
};
