import type { Block } from '@doc/domain/components/block-container/block-container.component';

import { Sidebar13Component } from './sidebar-13.component';

export const sidebar13Block: Block = {
  id: 'sidebar-13',
  title: 'Sidebar 13',
  description: 'A sidebar in a dialog.',
  component: Sidebar13Component,
  category: 'Sidebar',
  image: {
    light: '/blocks/sidebar-13/light.png',
    dark: '/blocks/sidebar-13/dark.png',
  },
  // Generated by `npm run sync:blocks` from the sibling component files — do not edit by hand.
  files: [
    {
      name: 'sidebar-13.component.html',
      path: 'src/components/sidebar-13/sidebar-13.component.html',
      content: `<div class="flex min-h-screen items-center justify-center">
  <p>Sidebar 13</p>
</div>
`,
      language: 'html',
    },
    {
      name: 'sidebar-13.component.ts',
      path: 'src/components/sidebar-13/sidebar-13.component.ts',
      content: `import { Component } from '@angular/core';

@Component({
  selector: 'lib-sidebar-13',
  standalone: true,
  imports: [],
  templateUrl: './sidebar-13.component.html',
})
export class Sidebar13Component {}
`,
      language: 'typescript',
    },
  ],
};
