import type { Block } from '@doc/domain/components/block-container/block-container.component';

import { Sidebar13Component } from './sidebar-13.component';

export const sidebar13Block: Block = {
  id: 'sidebar-13',
  title: 'Sidebar 13',
  description: 'A sidebar in a dialog.',
  component: Sidebar13Component,
  category: 'Sidebar',
  image: {
    light: '/blocks/sidebar-13/light.png',
    dark: '/blocks/sidebar-13/dark.png',
  },
  // Generated by `npm run sync:blocks` from the sibling component files — do not edit by hand.
  files: [
    {
      name: 'sidebar-13-settings-dialog.component.html',
      path: 'src/components/sidebar-13/sidebar-13-settings-dialog.component.html',
      content: `<button z-button zSize="sm" (click)="openSettings()">Open Dialog</button>

<ng-template #settings>
  <z-sidebar-provider class="min-h-0 items-start">
    <z-sidebar zCollapsible="none" class="hidden md:flex">
      <z-sidebar-content>
        <div z-sidebar-group>
          <div z-sidebar-group-content>
            <ul z-sidebar-menu>
              @for (item of nav; track item.name) {
                <li z-sidebar-menu-item>
                  <a z-sidebar-menu-button href="#" [zActive]="item.name === 'Messages &amp; media'">
                    <ng-icon [name]="item.icon" />
                    <span>{{ item.name }}</span>
                  </a>
                </li>
              }
            </ul>
          </div>
        </div>
      </z-sidebar-content>
    </z-sidebar>

    <main class="flex h-[480px] flex-1 flex-col overflow-hidden">
      <header
        class="flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-data-[collapsible=icon]/sidebar-wrapper:h-12"
      >
        <div class="flex items-center gap-2 px-4">
          <z-breadcrumb>
            <z-breadcrumb-item class="hidden md:block">
              <a z-breadcrumb-link href="#">Settings</a>
            </z-breadcrumb-item>
            <z-breadcrumb-separator class="hidden md:block" />
            <z-breadcrumb-item>
              <span z-breadcrumb-page>Messages &amp; media</span>
            </z-breadcrumb-item>
          </z-breadcrumb>
        </div>
      </header>

      <div class="flex flex-1 flex-col gap-4 overflow-y-auto p-4 pt-0">
        @for (item of placeholders; track item) {
          <div class="bg-muted/50 aspect-video max-w-3xl rounded-xl"></div>
        }
      </div>
    </main>
  </z-sidebar-provider>
</ng-template>
`,
      language: 'html',
    },
    {
      name: 'sidebar-13-settings-dialog.component.ts',
      path: 'src/components/sidebar-13/sidebar-13-settings-dialog.component.ts',
      content: `import { ChangeDetectionStrategy, Component, inject, type TemplateRef, viewChild } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import {
  lucideBell,
  lucideCheck,
  lucideGlobe,
  lucideKeyboard,
  lucideLink,
  lucideLock,
  lucideMenu,
  lucideMessageCircle,
  lucidePaintbrush,
  lucideSettings,
  lucideVideo,
} from '@ng-icons/lucide';

import { ZardBreadcrumbImports } from '@zard/components/breadcrumb/breadcrumb.imports';
import { ZardButtonComponent } from '@zard/components/button/button.component';
import { ZardDialogService } from '@zard/components/dialog/dialog.service';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

interface NavItem {
  readonly name: string;
  readonly icon: string;
}

/**
 * shadcn drives this with a declarative \`<Dialog>\`. The Zard dialog is imperative
 * (\`ZardDialogService\`), so the settings layout lives in a \`<ng-template>\` that is handed to the
 * service as the dialog content.
 */
@Component({
  selector: 'lib-sidebar-13-settings-dialog',
  standalone: true,
  imports: [...ZardSidebarImports, ...ZardBreadcrumbImports, ZardButtonComponent, NgIcon],
  viewProviders: [
    provideIcons({
      lucideBell,
      lucideCheck,
      lucideGlobe,
      lucideKeyboard,
      lucideLink,
      lucideLock,
      lucideMenu,
      lucideMessageCircle,
      lucidePaintbrush,
      lucideSettings,
      lucideVideo,
    }),
  ],
  templateUrl: './sidebar-13-settings-dialog.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Sidebar13SettingsDialogComponent {
  private readonly dialogService = inject(ZardDialogService);

  private readonly settingsTemplate = viewChild.required<TemplateRef<unknown>>('settings');

  // This is sample data.
  protected readonly nav: readonly NavItem[] = [
    { name: 'Notifications', icon: 'lucideBell' },
    { name: 'Navigation', icon: 'lucideMenu' },
    { name: 'Home', icon: 'lucideSettings' },
    { name: 'Appearance', icon: 'lucidePaintbrush' },
    { name: 'Messages & media', icon: 'lucideMessageCircle' },
    { name: 'Language & region', icon: 'lucideGlobe' },
    { name: 'Accessibility', icon: 'lucideKeyboard' },
    { name: 'Mark as read', icon: 'lucideCheck' },
    { name: 'Audio & video', icon: 'lucideVideo' },
    { name: 'Connected accounts', icon: 'lucideLink' },
    { name: 'Privacy & visibility', icon: 'lucideLock' },
    { name: 'Advanced', icon: 'lucideSettings' },
  ];

  protected readonly placeholders = Array.from({ length: 10 }, (_, index) => index);

  protected openSettings(): void {
    this.dialogService.create({
      zTitle: 'Settings',
      zDescription: 'Customize your settings here.',
      zContent: this.settingsTemplate(),
      zHideFooter: true,
      // The Zard dialog caps itself at \`sm:max-w-sm\`; the sidebar layout needs shadcn's wider frame.
      zCustomClasses: 'overflow-hidden md:max-h-[500px] sm:max-w-[700px] lg:max-w-[800px]',
    });
  }
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-13.component.html',
      path: 'src/components/sidebar-13/sidebar-13.component.html',
      content: `<div class="flex h-svh items-center justify-center">
  <lib-sidebar-13-settings-dialog />
</div>
`,
      language: 'html',
    },
    {
      name: 'sidebar-13.component.ts',
      path: 'src/components/sidebar-13/sidebar-13.component.ts',
      content: `import { ChangeDetectionStrategy, Component } from '@angular/core';

import { Sidebar13SettingsDialogComponent } from './sidebar-13-settings-dialog.component';

@Component({
  selector: 'lib-sidebar-13',
  standalone: true,
  imports: [Sidebar13SettingsDialogComponent],
  templateUrl: './sidebar-13.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Sidebar13Component {}
`,
      language: 'typescript',
    },
  ],
};
