import type { Block } from '@doc/domain/components/block-container/block-container.component';

import { Sidebar12Component } from './sidebar-12.component';

export const sidebar12Block: Block = {
  id: 'sidebar-12',
  title: 'Sidebar 12',
  description: 'A sidebar with a calendar.',
  component: Sidebar12Component,
  category: 'Sidebar',
  image: {
    light: '/blocks/sidebar-12/light.png',
    dark: '/blocks/sidebar-12/dark.png',
  },
  // Generated by `npm run sync:blocks` from the sibling component files — do not edit by hand.
  files: [
    {
      name: 'sidebar-12.component.html',
      path: 'src/components/sidebar-12/sidebar-12.component.html',
      content: `<div class="flex min-h-screen items-center justify-center">
  <p>Sidebar 12</p>
</div>
`,
      language: 'html',
    },
    {
      name: 'sidebar-12.component.ts',
      path: 'src/components/sidebar-12/sidebar-12.component.ts',
      content: `import { Component } from '@angular/core';

@Component({
  selector: 'lib-sidebar-12',
  standalone: true,
  imports: [],
  templateUrl: './sidebar-12.component.html',
})
export class Sidebar12Component {}
`,
      language: 'typescript',
    },
  ],
};
