import type { Block } from '@doc/domain/components/block-container/block-container.component';

import { Sidebar12Component } from './sidebar-12.component';

export const sidebar12Block: Block = {
  id: 'sidebar-12',
  title: 'Sidebar 12',
  description: 'A sidebar with a calendar.',
  component: Sidebar12Component,
  category: 'Sidebar',
  image: {
    light: '/blocks/sidebar-12/light.png',
    dark: '/blocks/sidebar-12/dark.png',
  },
  // Generated by `npm run sync:blocks` from the sibling component files — do not edit by hand.
  files: [
    {
      name: 'sidebar-12-app-sidebar.component.html',
      path: 'src/components/sidebar-12/sidebar-12-app-sidebar.component.html',
      content: `<z-sidebar>
  <div z-sidebar-header class="border-sidebar-border h-16 border-b">
    <lib-sidebar-12-nav-user [user]="user" />
  </div>

  <z-sidebar-content>
    <lib-sidebar-12-date-picker />
    <z-sidebar-separator class="mx-0" />
    <lib-sidebar-12-calendars [calendars]="calendars" />
  </z-sidebar-content>

  <div z-sidebar-footer>
    <ul z-sidebar-menu>
      <li z-sidebar-menu-item>
        <button z-sidebar-menu-button>
          <ng-icon name="lucidePlus" />
          <span>New Calendar</span>
        </button>
      </li>
    </ul>
  </div>

  <button z-sidebar-rail aria-label="Toggle Sidebar"></button>
</z-sidebar>
`,
      language: 'html',
    },
    {
      name: 'sidebar-12-app-sidebar.component.ts',
      path: 'src/components/sidebar-12/sidebar-12-app-sidebar.component.ts',
      content: `import { ChangeDetectionStrategy, Component } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucidePlus } from '@ng-icons/lucide';

import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

import { Sidebar12CalendarsComponent, type Sidebar12Calendar } from './sidebar-12-calendars.component';
import { Sidebar12DatePickerComponent } from './sidebar-12-date-picker.component';
import { Sidebar12NavUserComponent, type Sidebar12User } from './sidebar-12-nav-user.component';

@Component({
  selector: 'lib-sidebar-12-app-sidebar',
  standalone: true,
  imports: [
    ...ZardSidebarImports,
    Sidebar12NavUserComponent,
    Sidebar12DatePickerComponent,
    Sidebar12CalendarsComponent,
    NgIcon,
  ],
  viewProviders: [provideIcons({ lucidePlus })],
  templateUrl: './sidebar-12-app-sidebar.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Sidebar12AppSidebarComponent {
  // This is sample data.
  protected readonly user: Sidebar12User = {
    name: 'zard ui',
    email: 'm@example.com',
    avatar: 'https://github.com/zard-ui.png',
  };

  protected readonly calendars: readonly Sidebar12Calendar[] = [
    { name: 'My Calendars', items: ['Personal', 'Work', 'Family'] },
    { name: 'Favorites', items: ['Holidays', 'Birthdays'] },
    { name: 'Other', items: ['Travel', 'Reminders', 'Deadlines'] },
  ];
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-12-calendars.component.html',
      path: 'src/components/sidebar-12/sidebar-12-calendars.component.html',
      content: `@for (calendar of calendars(); track calendar.name; let groupIndex = $index) {
  <div z-sidebar-group class="py-0">
    <div z-collapsible class="group/collapsible" [zOpen]="groupIndex === 0">
      <button
        z-collapsible-trigger
        z-sidebar-group-label
        class="group/label text-sidebar-foreground hover:bg-sidebar-accent hover:text-sidebar-accent-foreground w-full text-sm"
      >
        {{ calendar.name }}
        <ng-icon
          name="lucideChevronRight"
          class="ml-auto transition-transform group-data-[state=open]/collapsible:rotate-90"
        />
      </button>

      <z-collapsible-content>
        <div z-sidebar-group-content>
          <ul z-sidebar-menu>
            @for (item of calendar.items; track item; let itemIndex = $index) {
              <li z-sidebar-menu-item>
                <button z-sidebar-menu-button>
                  <div
                    [attr.data-active]="itemIndex < 2"
                    class="group/calendar-item border-sidebar-border text-sidebar-primary-foreground data-[active=true]:border-sidebar-primary data-[active=true]:bg-sidebar-primary flex aspect-square size-4 shrink-0 items-center justify-center rounded-sm border"
                  >
                    <!-- \`hidden!\`/\`block!\`: NgIcon's host \`display\` is declared outside any cascade
                         layer, so unprefixed display utilities cannot override it. -->
                    <ng-icon name="lucideCheck" class="hidden! size-3 group-data-[active=true]/calendar-item:block!" />
                  </div>
                  {{ item }}
                </button>
              </li>
            }
          </ul>
        </div>
      </z-collapsible-content>
    </div>
  </div>

  <z-sidebar-separator class="mx-0" />
}
`,
      language: 'html',
    },
    {
      name: 'sidebar-12-calendars.component.ts',
      path: 'src/components/sidebar-12/sidebar-12-calendars.component.ts',
      content: `import { ChangeDetectionStrategy, Component, input } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideCheck, lucideChevronRight } from '@ng-icons/lucide';

import { ZardCollapsibleImports } from '@zard/components/collapsible/collapsible.imports';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

export interface Sidebar12Calendar {
  readonly name: string;
  readonly items: readonly string[];
}

@Component({
  selector: 'lib-sidebar-12-calendars',
  standalone: true,
  imports: [...ZardSidebarImports, ...ZardCollapsibleImports, NgIcon],
  viewProviders: [provideIcons({ lucideCheck, lucideChevronRight })],
  templateUrl: './sidebar-12-calendars.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Sidebar12CalendarsComponent {
  readonly calendars = input<readonly Sidebar12Calendar[]>([]);
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-12-date-picker.component.html',
      path: 'src/components/sidebar-12/sidebar-12-date-picker.component.html',
      content: `<div z-sidebar-group class="px-0">
  <div z-sidebar-group-content>
    <!-- shadcn hooks the highlight onto react-day-picker's \`.bg-accent\` gridcell; the Zard calendar
         marks the same cell with \`data-today\`, so the selector is retargeted, not redesigned. -->
    <z-calendar
      class="[&_[role=gridcell][data-today]]:bg-sidebar-primary [&_[role=gridcell][data-today]]:text-sidebar-primary-foreground [&_[role=gridcell]]:w-[33px]"
    />
  </div>
</div>
`,
      language: 'html',
    },
    {
      name: 'sidebar-12-date-picker.component.ts',
      path: 'src/components/sidebar-12/sidebar-12-date-picker.component.ts',
      content: `import { ChangeDetectionStrategy, Component } from '@angular/core';

import { ZardCalendarComponent } from '@zard/components/calendar/calendar.component';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

@Component({
  selector: 'lib-sidebar-12-date-picker',
  standalone: true,
  imports: [...ZardSidebarImports, ZardCalendarComponent],
  templateUrl: './sidebar-12-date-picker.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'contents' },
})
export class Sidebar12DatePickerComponent {}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-12-nav-user.component.html',
      path: 'src/components/sidebar-12/sidebar-12-nav-user.component.html',
      content: `<ul z-sidebar-menu>
  <li z-sidebar-menu-item>
    <button
      z-sidebar-menu-button
      zSize="lg"
      z-dropdown
      [zDropdownMenu]="userMenu"
      class="data-[state=open]:bg-sidebar-accent data-[state=open]:text-sidebar-accent-foreground"
    >
      <z-avatar class="size-8 rounded-lg" [zSrc]="user().avatar" [zAlt]="user().name" zFallback="ZU" />

      <div class="grid flex-1 text-left text-sm leading-tight">
        <span class="truncate font-medium">{{ user().name }}</span>
        <span class="truncate text-xs">{{ user().email }}</span>
      </div>

      <ng-icon name="lucideChevronsUpDown" class="ml-auto size-4" />
    </button>

    <z-dropdown-menu-content
      #userMenu="zDropdownMenuContent"
      class="w-(--z-dropdown-menu-trigger-width) min-w-56 rounded-lg"
      [zSide]="menuSide()"
      zAlign="end"
    >
      <z-dropdown-menu-label class="p-0 font-normal">
        <div class="flex items-center gap-2 px-1 py-1.5 text-left text-sm">
          <z-avatar class="size-8 rounded-lg" [zSrc]="user().avatar" [zAlt]="user().name" zFallback="ZU" />

          <div class="grid flex-1 text-left text-sm leading-tight">
            <span class="truncate font-medium">{{ user().name }}</span>
            <span class="truncate text-xs">{{ user().email }}</span>
          </div>
        </div>
      </z-dropdown-menu-label>

      <z-dropdown-menu-separator />

      <z-dropdown-menu-group>
        <z-dropdown-menu-item>
          <ng-icon name="lucideSparkles" />
          Upgrade to Pro
        </z-dropdown-menu-item>
      </z-dropdown-menu-group>

      <z-dropdown-menu-separator />

      <z-dropdown-menu-group>
        <z-dropdown-menu-item>
          <ng-icon name="lucideBadgeCheck" />
          Account
        </z-dropdown-menu-item>
        <z-dropdown-menu-item>
          <ng-icon name="lucideCreditCard" />
          Billing
        </z-dropdown-menu-item>
        <z-dropdown-menu-item>
          <ng-icon name="lucideBell" />
          Notifications
        </z-dropdown-menu-item>
      </z-dropdown-menu-group>

      <z-dropdown-menu-separator />

      <z-dropdown-menu-item>
        <ng-icon name="lucideLogOut" />
        Log out
      </z-dropdown-menu-item>
    </z-dropdown-menu-content>
  </li>
</ul>
`,
      language: 'html',
    },
    {
      name: 'sidebar-12-nav-user.component.ts',
      path: 'src/components/sidebar-12/sidebar-12-nav-user.component.ts',
      content: `import { ChangeDetectionStrategy, Component, computed, inject, input } from '@angular/core';

import { NgIcon, provideIcons } from '@ng-icons/core';
import {
  lucideBadgeCheck,
  lucideBell,
  lucideChevronsUpDown,
  lucideCreditCard,
  lucideLogOut,
  lucideSparkles,
} from '@ng-icons/lucide';

import { ZardAvatarComponent } from '@zard/components/avatar/avatar.component';
import type { ZardDropdownSide } from '@zard/components/dropdown/dropdown-positions';
import { ZardDropdownImports } from '@zard/components/dropdown/dropdown.imports';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';
import { ZardSidebarService } from '@zard/components/sidebar/sidebar.service';

export interface Sidebar12User {
  readonly name: string;
  readonly email: string;
  readonly avatar: string;
}

@Component({
  selector: 'lib-sidebar-12-nav-user',
  standalone: true,
  imports: [...ZardSidebarImports, ...ZardDropdownImports, ZardAvatarComponent, NgIcon],
  viewProviders: [
    provideIcons({
      lucideBadgeCheck,
      lucideBell,
      lucideChevronsUpDown,
      lucideCreditCard,
      lucideLogOut,
      lucideSparkles,
    }),
  ],
  templateUrl: './sidebar-12-nav-user.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Sidebar12NavUserComponent {
  private readonly sidebar = inject(ZardSidebarService);
  /** shadcn opens these menus to the side of the sidebar on desktop and below the trigger on mobile. */
  protected readonly menuSide = computed<ZardDropdownSide>(() => (this.sidebar.isMobile() ? 'bottom' : 'right'));

  readonly user = input.required<Sidebar12User>();
}
`,
      language: 'typescript',
    },
    {
      name: 'sidebar-12.component.html',
      path: 'src/components/sidebar-12/sidebar-12.component.html',
      content: `<z-sidebar-provider>
  <lib-sidebar-12-app-sidebar />

  <main z-sidebar-inset>
    <header class="bg-background sticky top-0 flex h-16 shrink-0 items-center gap-2 border-b px-4">
      <button z-sidebar-trigger class="-ml-1" aria-label="Toggle Sidebar"></button>

      <z-separator
        zOrientation="vertical"
        class="mr-2 data-[orientation=vertical]:h-4 data-[orientation=vertical]:self-center"
      />

      <z-breadcrumb>
        <z-breadcrumb-item>
          <span z-breadcrumb-page>October 2024</span>
        </z-breadcrumb-item>
      </z-breadcrumb>
    </header>

    <div class="flex flex-1 flex-col gap-4 p-4">
      <div class="grid auto-rows-min gap-4 md:grid-cols-5">
        @for (cell of placeholders; track cell) {
          <div class="bg-muted/50 aspect-square rounded-xl"></div>
        }
      </div>
    </div>
  </main>
</z-sidebar-provider>
`,
      language: 'html',
    },
    {
      name: 'sidebar-12.component.ts',
      path: 'src/components/sidebar-12/sidebar-12.component.ts',
      content: `import { ChangeDetectionStrategy, Component } from '@angular/core';

import { ZardBreadcrumbImports } from '@zard/components/breadcrumb/breadcrumb.imports';
import { ZardSeparatorComponent } from '@zard/components/separator/separator.component';
import { ZardSidebarImports } from '@zard/components/sidebar/sidebar.imports';

import { Sidebar12AppSidebarComponent } from './sidebar-12-app-sidebar.component';

@Component({
  selector: 'lib-sidebar-12',
  standalone: true,
  imports: [...ZardSidebarImports, ...ZardBreadcrumbImports, ZardSeparatorComponent, Sidebar12AppSidebarComponent],
  templateUrl: './sidebar-12.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Sidebar12Component {
  protected readonly placeholders = Array.from({ length: 20 }, (_, index) => index);
}
`,
      language: 'typescript',
    },
  ],
};
