name: "Documentation Deploy to PROD"
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Install dependencies
        run: npm install

      - name: Build documentation
        run: npm run build:doc

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project=zard-6fc39
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      