import {
  lucideActivity,
  lucideArchive,
  lucideArrowLeft,
  lucideArrowRight,
  lucideArrowUp,
  lucideArrowUpRight,
  lucideBadgeCheck,
  lucideBan,
  lucideBell,
  lucideBold,
  lucideBookOpen,
  lucideBookOpenText,
  lucideCalendar,
  lucideCalendarPlus,
  lucideCheck,
  lucideChevronDown,
  lucideChevronLeft,
  lucideChevronRight,
  lucideChevronsUpDown,
  lucideChevronUp,
  lucideCircle,
  lucideCircleAlert,
  lucideCircleCheck,
  lucideCircleDollarSign,
  lucideCircleSmall,
  lucideCircleX,
  lucideClipboard,
  lucideClock,
  lucideCode,
  lucideCodeXml,
  lucideCopy,
  lucideCreditCard,
  lucideDollarSign,
  lucideEllipsis,
  lucideExternalLink,
  lucideEye,
  lucideFile,
  lucideFileText,
  lucideFolder,
  lucideFolderCode,
  lucideFolderOpen,
  lucideFolderPlus,
  lucideGalleryHorizontal,
  lucideGithub,
  lucideHeart,
  lucideHouse,
  lucideInbox,
  lucideInfo,
  lucideItalic,
  lucideLayers,
  lucideLayers2,
  lucideLayoutDashboard,
  lucideLightbulb,
  lucideLightbulbOff,
  lucideListFilterPlus,
  lucideLoaderCircle,
  lucideLogOut,
  lucideMail,
  lucideMinus,
  lucideMonitor,
  lucideMoon,
  lucideMoveRight,
  lucidePalette,
  lucidePanelLeft,
  lucidePlus,
  lucidePopcorn,
  lucidePuzzle,
  lucideSave,
  lucideSearch,
  lucideSettings,
  lucideShield,
  lucideSmartphone,
  lucideSparkles,
  lucideSquare,
  lucideSquareLibrary,
  lucideStar,
  lucideSun,
  lucideSunMoon,
  lucideTablet,
  lucideTag,
  lucideTerminal,
  lucideTextAlignCenter,
  lucideTextAlignEnd,
  lucideTextAlignStart,
  lucideTrash2,
  lucideTriangleAlert,
  lucideUnderline,
  lucideUser,
  lucideUserPlus,
  lucideUsers,
  lucideX,
  lucideZap,
} from '@ng-icons/lucide';

const DarkModeSvg = `
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
  <path d="M12 12m-9 0a9 9 0 1 0 18 0a9 9 0 1 0 -18 0"/>
  <path d="M12 3l0 18"/>
  <path d="M12 9l4.65 -4.65"/>
  <path d="M12 14.3l7.37 -7.37"/>
  <path d="M12 19.6l8.85 -8.85"/>
</svg>
`;

export const ZardIconRegistry = {
  activity: lucideActivity,
  archive: lucideArchive,
  'arrow-left': lucideArrowLeft,
  'arrow-right': lucideArrowRight,
  'arrow-up': lucideArrowUp,
  'arrow-up-right': lucideArrowUpRight,
  ban: lucideBan,
  'badge-check': lucideBadgeCheck,
  bell: lucideBell,
  bold: lucideBold,
  'book-open': lucideBookOpen,
  'book-open-text': lucideBookOpenText,
  calendar: lucideCalendar,
  'calendar-plus': lucideCalendarPlus,
  check: lucideCheck,
  'chevron-down': lucideChevronDown,
  'chevron-left': lucideChevronLeft,
  'chevron-right': lucideChevronRight,
  'chevrons-up-down': lucideChevronsUpDown,
  'chevron-up': lucideChevronUp,
  circle: lucideCircle,
  'circle-alert': lucideCircleAlert,
  'circle-check': lucideCircleCheck,
  'circle-dollar-sign': lucideCircleDollarSign,
  'circle-small': lucideCircleSmall,
  'circle-x': lucideCircleX,
  clipboard: lucideClipboard,
  clock: lucideClock,
  code: lucideCode,
  'code-xml': lucideCodeXml,
  copy: lucideCopy,
  'credit-card': lucideCreditCard,
  'dark-mode': DarkModeSvg,
  'dollar-sign': lucideDollarSign,
  ellipsis: lucideEllipsis,
  'external-link': lucideExternalLink,
  eye: lucideEye,
  file: lucideFile,
  'file-text': lucideFileText,
  folder: lucideFolder,
  'folder-code': lucideFolderCode,
  'folder-open': lucideFolderOpen,
  'folder-plus': lucideFolderPlus,
  'gallery-horizontal': lucideGalleryHorizontal,
  github: lucideGithub,
  heart: lucideHeart,
  house: lucideHouse,
  inbox: lucideInbox,
  info: lucideInfo,
  italic: lucideItalic,
  layers: lucideLayers,
  'layers-2': lucideLayers2,
  'layout-dashboard': lucideLayoutDashboard,
  lightbulb: lucideLightbulb,
  'lightbulb-off': lucideLightbulbOff,
  'list-filter-plus': lucideListFilterPlus,
  'loader-circle': lucideLoaderCircle,
  'log-out': lucideLogOut,
  mail: lucideMail,
  minus: lucideMinus,
  monitor: lucideMonitor,
  moon: lucideMoon,
  'move-right': lucideMoveRight,
  palette: lucidePalette,
  'panel-left': lucidePanelLeft,
  plus: lucidePlus,
  popcorn: lucidePopcorn,
  puzzle: lucidePuzzle,
  save: lucideSave,
  search: lucideSearch,
  settings: lucideSettings,
  shield: lucideShield,
  smartphone: lucideSmartphone,
  sparkles: lucideSparkles,
  square: lucideSquare,
  'square-library': lucideSquareLibrary,
  star: lucideStar,
  sun: lucideSun,
  'sun-moon': lucideSunMoon,
  tablet: lucideTablet,
  tag: lucideTag,
  terminal: lucideTerminal,
  'text-align-center': lucideTextAlignCenter,
  'text-align-end': lucideTextAlignEnd,
  'text-align-start': lucideTextAlignStart,
  trash: lucideTrash2,
  'triangle-alert': lucideTriangleAlert,
  underline: lucideUnderline,
  user: lucideUser,
  'user-plus': lucideUserPlus,
  users: lucideUsers,
  x: lucideX,
  zap: lucideZap,
} as const;

export type ZardIconName = keyof typeof ZardIconRegistry;
